.TH "_lQueue" 3 "2022年 十一月 24日 星期四" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_lQueue \- 链表方式队列的节点  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <STL_Queue\&.h>\fP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "struct \fB_lQueue\fP * \fBback\fP"
.br
.RI "后一个节点的指针 "
.ti -1c
.RI "void * \fBdat\fP"
.br
.RI "数据的指针 "
.ti -1c
.RI "\fBu32\fP \fBsize\fP"
.br
.RI "该数据的大小 "
.in -1c
.SH "详细描述"
.PP 
链表方式队列的节点 
.PP
在文件 \fBSTL_Queue\&.h\fP 第 \fB87\fP 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "struct \fB_lQueue\fP* _lQueue::back"

.PP
后一个节点的指针 
.PP
在文件 \fBSTL_Queue\&.h\fP 第 \fB88\fP 行定义\&.
.SS "void* _lQueue::dat"

.PP
数据的指针 
.PP
在文件 \fBSTL_Queue\&.h\fP 第 \fB89\fP 行定义\&.
.SS "\fBu32\fP _lQueue::size"

.PP
该数据的大小 
.PP
在文件 \fBSTL_Queue\&.h\fP 第 \fB90\fP 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
