.TH "D:/gitt/MicrochipFor32/bsp_Device/bsp_PrintArt.h" 3 "2022年 十一月 27日 星期日" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/MicrochipFor32/bsp_Device/bsp_PrintArt.h \- print重定向的艺术  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'varint\&.h'\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "class \fBbsp_PrintArt\fP"
.br
.RI "创造一个print的重定向对象 "
.in -1c
.SH "详细描述"
.PP 
print重定向的艺术 


.PP
在文件 \fBbsp_PrintArt\&.h\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
