.TH "D:/gitt/MicrochipFor32/bsp_Device/bsp_IIC/bsp_IIC.h" 3 "2022年 十一月 27日 星期日" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/MicrochipFor32/bsp_Device/bsp_IIC/bsp_IIC.h \- 本类实现软件IIC功能 依此类派生出其他软件IIC功能  

.SH SYNOPSIS
.br
.PP
\fC#include 'varint\&.h'\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "class \fBbsp_IIC\fP"
.br
.RI "IIC的基础实现方法 留下三个保护性接口需要实现,分别是控制时钟,控制数据,延时函数 "
.in -1c
.SS "枚举"

.in +1c
.ti -1c
.RI "enum { \fBIIC_RESET\fP, \fBIIC_SET\fP, \fBIIC_READ\fP }"
.br
.RI "控制管脚的三种状态(置位,复位,读取) "
.in -1c
.SH "详细描述"
.PP 
本类实现软件IIC功能 依此类派生出其他软件IIC功能 


.PP
在文件 \fBbsp_IIC\&.h\fP 中定义\&.
.SH "枚举类型说明"
.PP 
.SS "anonymous enum"

.PP
控制管脚的三种状态(置位,复位,读取) 
.PP
\fB枚举值\fP
.in +1c
.TP
\fB\fIIIC_RESET \fP\fP
管脚复位状态 
.TP
\fB\fIIIC_SET \fP\fP
管脚置位状态 
.TP
\fB\fIIIC_READ \fP\fP
读取管脚状态 
.PP
在文件 \fBbsp_IIC\&.h\fP 第 \fB44\fP 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
