.TH "D:/gitt/MicrochipFor32/bsp_Device/bsp_SD.cpp" 3 "2022年 十一月 24日 星期四" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/MicrochipFor32/bsp_Device/bsp_SD.cpp \- 操作SD卡的库  

.SH SYNOPSIS
.br
.PP
\fC#include 'bsp_SD\&.h'\fP
.br

.SH "详细描述"
.PP 
操作SD卡的库 


.PP
在文件 \fBbsp_SD\&.cpp\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
