.TH "D:/gitt/MicrochipFor32/bsp_Device/bsp_IIC/bsp_AT24C00.h" 3 "2022年 十一月 27日 星期日" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/MicrochipFor32/bsp_Device/bsp_IIC/bsp_AT24C00.h \- 本类实现AT24C00的通讯  

.SH SYNOPSIS
.br
.PP
\fC#include 'varint\&.h'\fP
.br
\fC#include 'bsp_IIC_STM32\&.h'\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "class \fBbsp_STM32_AT24C00\fP"
.br
.RI "一个AT24设备,基于STM32的IIC总线 "
.in -1c
.SH "详细描述"
.PP 
本类实现AT24C00的通讯 


.PP
在文件 \fBbsp_AT24C00\&.h\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
