.TH "bsp_Position_PID" 3 "2022年 十一月 22日 星期二" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bsp_Position_PID \- 位置法为基础的PID算法  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bsp_PID\&.h>\fP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBbsp_Position_PID\fP (void)"
.br
.ti -1c
.RI "\fBbsp_Position_PID\fP (float \fBKp\fP, float \fBKi\fP, float \fBKd\fP, float \fBtarget\fP, float \fBresult_H\fP, float \fBresult_L\fP)"
.br
.RI "PID算法 "
.ti -1c
.RI "\fB~bsp_Position_PID\fP (void)"
.br
.ti -1c
.RI "float \fBPID\fP (float temp)"
.br
.RI "PID算法 "
.ti -1c
.RI "void \fBclean\fP (void)"
.br
.RI "清理历史数据 "
.ti -1c
.RI "void \fBset\fP (float P, float I, float D)"
.br
.RI "PID参数设置 "
.in -1c
.SS "Public 属性"

.in +1c
.ti -1c
.RI "float \fBtarget\fP"
.br
.RI "设定值 "
.ti -1c
.RI "float \fBKp\fP"
.br
.RI "比例系数 "
.ti -1c
.RI "float \fBKd\fP"
.br
.RI "积分系数 "
.ti -1c
.RI "float \fBKi\fP"
.br
.RI "微分系数 "
.ti -1c
.RI "float \fBresult\fP"
.br
.RI "输出值 "
.in -1c
.SS "Private 属性"

.in +1c
.ti -1c
.RI "float \fBintegral\fP"
.br
.RI "积分值 "
.ti -1c
.RI "float \fBlasterror\fP"
.br
.RI "前一拍偏差 "
.ti -1c
.RI "float \fBresult_H\fP"
.br
.RI "输出最高值 "
.ti -1c
.RI "float \fBresult_L\fP"
.br
.RI "输出最低值 "
.in -1c
.SH "详细描述"
.PP 
位置法为基础的PID算法 
.PP
在文件 \fBbsp_PID\&.h\fP 第 \fB43\fP 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "bsp_Position_PID::bsp_Position_PID (void)"

.PP
在文件 \fBbsp_PID\&.cpp\fP 第 \fB134\fP 行定义\&.
.SS "bsp_Position_PID::bsp_Position_PID (float Kp, float Ki, float Kd, float target, float result_H, float result_L)"

.PP
PID算法 
.PP
\fB参数\fP
.RS 4
\fIKp\fP P参数 
.br
\fIKi\fP I参数 
.br
\fIKd\fP D参数 
.br
\fItarget\fP 目标值 
.br
\fIresult_H\fP 输出最大值 
.br
\fIresult_L\fP 输出最小值 
.RE
.PP

.PP
在文件 \fBbsp_PID\&.cpp\fP 第 \fB155\fP 行定义\&.
.SS "bsp_Position_PID::~bsp_Position_PID (void)"

.PP
在文件 \fBbsp_PID\&.cpp\fP 第 \fB169\fP 行定义\&.
.SH "成员函数说明"
.PP 
.SS "void bsp_Position_PID::clean (void)"

.PP
清理历史数据 
.PP
\fB返回\fP
.RS 4
清除PID运算数据 
.RE
.PP

.PP
在文件 \fBbsp_PID\&.cpp\fP 第 \fB96\fP 行定义\&.
.SS "float bsp_Position_PID::PID (float temp)"

.PP
PID算法 
.PP
\fB参数\fP
.RS 4
\fItemp\fP 目前变量 
.RE
.PP
\fB返回\fP
.RS 4
返回调整量 
.RE
.PP

.PP
在文件 \fBbsp_PID\&.cpp\fP 第 \fB48\fP 行定义\&.
.SS "void bsp_Position_PID::set (float P, float I, float D)"

.PP
PID参数设置 
.PP
\fB参数\fP
.RS 4
\fIP\fP P参数 
.br
\fII\fP I参数 
.br
\fID\fP D参数 
.RE
.PP

.PP
在文件 \fBbsp_PID\&.cpp\fP 第 \fB119\fP 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "float bsp_Position_PID::integral\fC [private]\fP"

.PP
积分值 
.PP
在文件 \fBbsp_PID\&.h\fP 第 \fB61\fP 行定义\&.
.SS "float bsp_Position_PID::Kd"

.PP
积分系数 
.PP
在文件 \fBbsp_PID\&.h\fP 第 \fB57\fP 行定义\&.
.SS "float bsp_Position_PID::Ki"

.PP
微分系数 
.PP
在文件 \fBbsp_PID\&.h\fP 第 \fB58\fP 行定义\&.
.SS "float bsp_Position_PID::Kp"

.PP
比例系数 
.PP
在文件 \fBbsp_PID\&.h\fP 第 \fB56\fP 行定义\&.
.SS "float bsp_Position_PID::lasterror\fC [private]\fP"

.PP
前一拍偏差 
.PP
在文件 \fBbsp_PID\&.h\fP 第 \fB62\fP 行定义\&.
.SS "float bsp_Position_PID::result"

.PP
输出值 
.PP
在文件 \fBbsp_PID\&.h\fP 第 \fB59\fP 行定义\&.
.SS "float bsp_Position_PID::result_H\fC [private]\fP"

.PP
输出最高值 
.PP
在文件 \fBbsp_PID\&.h\fP 第 \fB64\fP 行定义\&.
.SS "float bsp_Position_PID::result_L\fC [private]\fP"

.PP
输出最低值 
.PP
在文件 \fBbsp_PID\&.h\fP 第 \fB65\fP 行定义\&.
.SS "float bsp_Position_PID::target"

.PP
设定值 
.PP
在文件 \fBbsp_PID\&.h\fP 第 \fB55\fP 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
