.TH "D:/gitt/MicrochipFor32/bsp_Device/bsp_BMP.cpp" 3 "2022年 十一月 25日 星期五" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/MicrochipFor32/bsp_Device/bsp_BMP.cpp \- 用来构造BMP图片  

.SH SYNOPSIS
.br
.PP
\fC#include 'bsp_BMP\&.h'\fP
.br

.SH "详细描述"
.PP 
用来构造BMP图片 


.PP
在文件 \fBbsp_BMP\&.cpp\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
