.TH "D:/gitt/MicrochipFor32/bsp_Device/bsp_PrintArt.cpp" 3 "2022年 十一月 27日 星期日" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/MicrochipFor32/bsp_Device/bsp_PrintArt.cpp \- print重定向的艺术  

.SH SYNOPSIS
.br
.PP
\fC#include 'bsp_PrintArt\&.h'\fP
.br

.SH "详细描述"
.PP 
print重定向的艺术 


.PP
在文件 \fBbsp_PrintArt\&.cpp\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
