.TH "D:/gitt/MicrochipFor32/bsp_Device/bsp_math/bsp_Calculus.h" 3 "2022年 十一月 27日 星期日" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/MicrochipFor32/bsp_Device/bsp_math/bsp_Calculus.h \- 离散微积分  

.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'varint\&.h'\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "class \fBbsp_Differential\fP"
.br
.RI "一个微分对象 "
.ti -1c
.RI "class \fBbsp_Integral\fP"
.br
.RI "一个积分对象 "
.in -1c
.SH "详细描述"
.PP 
离散微积分 


.PP
在文件 \fBbsp_Calculus\&.h\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
