.TH "bsp_AT" 3 "2022年 十一月 25日 星期五" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bsp_AT \- AT协议的基类  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bsp_AT\&.h>\fP
.PP
被 \fBbsp_ATKESP8266\fP 继承\&.
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "void \fBcom\fP (const char *dat)"
.br
.RI "发送一条AT指令,已加AT+与\\r
.br
尾 "
.in -1c
.SS "Protected 成员函数"

.in +1c
.ti -1c
.RI "virtual void \fBTransmit\fP (\fBu8\fP *dat, \fBu16\fP len)=0"
.br
.RI "发送数据到端口 "
.in -1c
.SH "详细描述"
.PP 
AT协议的基类 
.PP
在文件 \fBbsp_AT\&.h\fP 第 \fB43\fP 行定义\&.
.SH "成员函数说明"
.PP 
.SS "void bsp_AT::com (const char * dat)"

.PP
发送一条AT指令,已加AT+与\\r
.br
尾 
.PP
\fB参数\fP
.RS 4
\fIdat\fP 带发射数据 
.RE
.PP

.PP
在文件 \fBbsp_AT\&.cpp\fP 第 \fB44\fP 行定义\&.
.SS "virtual void bsp_AT::Transmit (\fBu8\fP * dat, \fBu16\fP len)\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
发送数据到端口 
.PP
\fB参数\fP
.RS 4
\fIdat\fP 数据头 
.br
\fIlen\fP 数据长度 
.RE
.PP

.PP
在 \fBbsp_ATKESP8266\fP 内被实现\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
