.TH "D:/gitt/MicrochipFor32/bsp_Device/bsp_PID.h" 3 "2022年 十一月 24日 星期四" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/MicrochipFor32/bsp_Device/bsp_PID.h \- 实现了PID算法  

.SH SYNOPSIS
.br
.PP
\fC#include 'varint\&.h'\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "class \fBbsp_Position_PID\fP"
.br
.RI "位置法为基础的PID算法 "
.ti -1c
.RI "class \fBbsp_Increment_PID\fP"
.br
.RI "增量法为基础的PID算法 "
.in -1c
.SH "详细描述"
.PP 
实现了PID算法 


.PP
在文件 \fBbsp_PID\&.h\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
