.TH "bsp_Digit" 3 "2022年 十一月 24日 星期四" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bsp_Digit \- 一个面向数码管的类,使用级联的HC595  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bsp_Digit\&.h>\fP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBbsp_Digit\fP (GPIO_TypeDef *\fBGPIOx_MOSIO\fP, uint16_t \fBGPIO_Pin_MOSIO\fP, GPIO_TypeDef *\fBGPIOx_S_CLK\fP, uint16_t \fBGPIO_Pin_S_CLK\fP, GPIO_TypeDef *\fBGPIOx_R_CLK\fP, uint16_t \fBGPIO_Pin_R_CLK\fP, bool \fBPolarity\fP)"
.br
.ti -1c
.RI "void \fBDatCom\fP (\fBu8\fP SendVal, \fBu8\fP cha)"
.br
.RI "在某位显示一个数字 "
.ti -1c
.RI "void \fBnum\fP (\fBu16\fP num)"
.br
.RI "显示一个四位数据 "
.ti -1c
.RI "void \fBdop\fP (\fBu8\fP cha)"
.br
.RI "显示一个小数点 "
.ti -1c
.RI "void \fBnumdop\fP (\fBu16\fP \fBnum\fP, \fBu8\fP cha)"
.br
.RI "显示数据与一个像素点 "
.in -1c
.SS "Public 属性"

.in +1c
.ti -1c
.RI "\fBu16\fP \fBdivision\fP"
.br
.RI "分频系数,越大越慢 "
.in -1c
.SS "Protected 成员函数"

.in +1c
.ti -1c
.RI "void \fBdat\fP (\fBu8\fP SendVal)"
.br
.ti -1c
.RI "void \fBcom\fP (void)"
.br
.in -1c
.SS "Private 属性"

.in +1c
.ti -1c
.RI "bool \fBPolarity\fP"
.br
.RI "共阴或共阳 "
.ti -1c
.RI "GPIO_TypeDef * \fBGPIOx_MOSIO\fP"
.br
.ti -1c
.RI "uint16_t \fBGPIO_Pin_MOSIO\fP"
.br
.ti -1c
.RI "GPIO_TypeDef * \fBGPIOx_S_CLK\fP"
.br
.ti -1c
.RI "uint16_t \fBGPIO_Pin_S_CLK\fP"
.br
.ti -1c
.RI "GPIO_TypeDef * \fBGPIOx_R_CLK\fP"
.br
.ti -1c
.RI "uint16_t \fBGPIO_Pin_R_CLK\fP"
.br
.in -1c
.SH "详细描述"
.PP 
一个面向数码管的类,使用级联的HC595 
.PP
在文件 \fBbsp_Digit\&.h\fP 第 \fB67\fP 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "bsp_Digit::bsp_Digit (GPIO_TypeDef * GPIOx_MOSIO, uint16_t GPIO_Pin_MOSIO, GPIO_TypeDef * GPIOx_S_CLK, uint16_t GPIO_Pin_S_CLK, GPIO_TypeDef * GPIOx_R_CLK, uint16_t GPIO_Pin_R_CLK, bool Polarity)"

.PP
在文件 \fBbsp_Digit\&.cpp\fP 第 \fB77\fP 行定义\&.
.SH "成员函数说明"
.PP 
.SS "void bsp_Digit::com (void)\fC [protected]\fP"

.PP
在文件 \fBbsp_Digit\&.cpp\fP 第 \fB47\fP 行定义\&.
.SS "void bsp_Digit::dat (\fBu8\fP SendVal)\fC [protected]\fP"

.PP
在文件 \fBbsp_Digit\&.cpp\fP 第 \fB41\fP 行定义\&.
.SS "void bsp_Digit::DatCom (\fBu8\fP SendVal, \fBu8\fP cha)"

.PP
在某位显示一个数字 
.PP
在文件 \fBbsp_Digit\&.cpp\fP 第 \fB51\fP 行定义\&.
.SS "void bsp_Digit::dop (\fBu8\fP cha)"

.PP
显示一个小数点 
.PP
在文件 \fBbsp_Digit\&.cpp\fP 第 \fB64\fP 行定义\&.
.SS "void bsp_Digit::num (\fBu16\fP num)"

.PP
显示一个四位数据 
.PP
在文件 \fBbsp_Digit\&.cpp\fP 第 \fB58\fP 行定义\&.
.SS "void bsp_Digit::numdop (\fBu16\fP num, \fBu8\fP cha)"

.PP
显示数据与一个像素点 
.PP
在文件 \fBbsp_Digit\&.cpp\fP 第 \fB71\fP 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "\fBu16\fP bsp_Digit::division"

.PP
分频系数,越大越慢 
.PP
在文件 \fBbsp_Digit\&.h\fP 第 \fB78\fP 行定义\&.
.SS "uint16_t bsp_Digit::GPIO_Pin_MOSIO\fC [private]\fP"

.PP
在文件 \fBbsp_Digit\&.h\fP 第 \fB87\fP 行定义\&.
.SS "uint16_t bsp_Digit::GPIO_Pin_R_CLK\fC [private]\fP"

.PP
在文件 \fBbsp_Digit\&.h\fP 第 \fB91\fP 行定义\&.
.SS "uint16_t bsp_Digit::GPIO_Pin_S_CLK\fC [private]\fP"

.PP
在文件 \fBbsp_Digit\&.h\fP 第 \fB89\fP 行定义\&.
.SS "GPIO_TypeDef* bsp_Digit::GPIOx_MOSIO\fC [private]\fP"

.PP
在文件 \fBbsp_Digit\&.h\fP 第 \fB86\fP 行定义\&.
.SS "GPIO_TypeDef* bsp_Digit::GPIOx_R_CLK\fC [private]\fP"

.PP
在文件 \fBbsp_Digit\&.h\fP 第 \fB90\fP 行定义\&.
.SS "GPIO_TypeDef* bsp_Digit::GPIOx_S_CLK\fC [private]\fP"

.PP
在文件 \fBbsp_Digit\&.h\fP 第 \fB88\fP 行定义\&.
.SS "bool bsp_Digit::Polarity\fC [private]\fP"

.PP
共阴或共阳 
.PP
在文件 \fBbsp_Digit\&.h\fP 第 \fB85\fP 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
