.TH "D:/gitt/MicrochipFor32/bsp_Device/bsp_PID.cpp" 3 "2022年 十一月 22日 星期二" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/MicrochipFor32/bsp_Device/bsp_PID.cpp \- 实现了PID算法  

.SH SYNOPSIS
.br
.PP
\fC#include 'bsp_PID\&.h'\fP
.br

.SH "详细描述"
.PP 
实现了PID算法 


.PP
在文件 \fBbsp_PID\&.cpp\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
