.TH "D:/gitt/MicrochipFor32/bsp_Device/bsp_ModBus.cpp" 3 "2022年 十一月 25日 星期五" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/MicrochipFor32/bsp_Device/bsp_ModBus.cpp \- ModBus通信函数  

.SH SYNOPSIS
.br
.PP
\fC#include 'bsp_ModBus\&.h'\fP
.br
\fC#include 'bsp_CRC\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SH "详细描述"
.PP 
ModBus通信函数 


.PP
在文件 \fBbsp_ModBus\&.cpp\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
