.TH "D:/gitt/MicrochipFor32/bsp_Device/bsp_ModBus_STM32.h" 3 "2022年 十一月 22日 星期二" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/MicrochipFor32/bsp_Device/bsp_ModBus_STM32.h \- ModBus通信基于STM32  

.SH SYNOPSIS
.br
.PP
\fC#include 'bsp_ModBus\&.h'\fP
.br
\fC#include 'usart\&.h'\fP
.br
\fC#include 'varint\&.h'\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "class \fBbsp_ModBus_STM32\fP"
.br
.RI "STM32用串口的ModBus发送器 "
.in -1c
.SH "详细描述"
.PP 
ModBus通信基于STM32 


.PP
在文件 \fBbsp_ModBus_STM32\&.h\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
