.TH "D:/gitt/MicrochipFor32/bsp_Device/bsp_AT24C00.cpp" 3 "2022年 十一月 25日 星期五" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/MicrochipFor32/bsp_Device/bsp_AT24C00.cpp \- 本类实现AT24C00的通讯  

.SH SYNOPSIS
.br
.PP
\fC#include 'varint\&.h'\fP
.br
\fC#include 'main\&.h'\fP
.br
\fC#include 'bsp_AT24C00\&.h'\fP
.br

.SH "详细描述"
.PP 
本类实现AT24C00的通讯 


.PP
在文件 \fBbsp_AT24C00\&.cpp\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
