.TH "bsp_MAX6675" 3 "2022年 十一月 27日 星期日" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bsp_MAX6675 \- MAX6675的一个对象类  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bsp_MAX6675\&.h>\fP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBbsp_MAX6675\fP (SPI_HandleTypeDef *\fBhspi\fP, GPIO_TypeDef *\fBGPIOx_CS\fP, uint16_t \fBGPIO_Pin_CS\fP)"
.br
.RI "构造一个MAX6675对象 "
.ti -1c
.RI "float \fBReadTemperature\fP (void)"
.br
.RI "访问目前温度 "
.in -1c
.SS "Protected 属性"

.in +1c
.ti -1c
.RI "SPI_HandleTypeDef * \fBhspi\fP"
.br
.ti -1c
.RI "GPIO_TypeDef * \fBGPIOx_CS\fP"
.br
.ti -1c
.RI "uint16_t \fBGPIO_Pin_CS\fP"
.br
.in -1c
.SH "详细描述"
.PP 
MAX6675的一个对象类 


.PP
\fB注解\fP
.RS 4
硬件SPI需要设置如下 Date Size:16 Bits MSB First 分频速度合适即可 需要准备一个CS管脚以控制选通 
.RE
.PP

.PP
在文件 \fBbsp_MAX6675\&.h\fP 第 \fB49\fP 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "bsp_MAX6675::bsp_MAX6675 (SPI_HandleTypeDef * hspi, GPIO_TypeDef * GPIOx_CS, uint16_t GPIO_Pin_CS)"

.PP
构造一个MAX6675对象 
.PP
\fB参数\fP
.RS 4
\fI*hspi\fP 设置的hspi,举例输入:&hspi1 
.br
\fI*GPIOx_CS\fP 设置的选通端口,举例输入:GPIOA 
.br
\fIGPIO_Pin_CS\fP 设置的选通针脚,举例输入:GPIO_PIN_0 
.RE
.PP
\fB返回\fP
.RS 4
无返回 
.RE
.PP

.PP
在文件 \fBbsp_MAX6675\&.cpp\fP 第 \fB49\fP 行定义\&.
.SH "成员函数说明"
.PP 
.SS "float bsp_MAX6675::ReadTemperature (void)"

.PP
访问目前温度 
.PP
\fB返回\fP
.RS 4
返回浮点类型温度 
.RE
.PP

.PP
在文件 \fBbsp_MAX6675\&.cpp\fP 第 \fB64\fP 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "uint16_t bsp_MAX6675::GPIO_Pin_CS\fC [protected]\fP"

.PP
在文件 \fBbsp_MAX6675\&.h\fP 第 \fB59\fP 行定义\&.
.SS "GPIO_TypeDef* bsp_MAX6675::GPIOx_CS\fC [protected]\fP"

.PP
在文件 \fBbsp_MAX6675\&.h\fP 第 \fB58\fP 行定义\&.
.SS "SPI_HandleTypeDef* bsp_MAX6675::hspi\fC [protected]\fP"

.PP
在文件 \fBbsp_MAX6675\&.h\fP 第 \fB57\fP 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
