.TH "bsp_PrintArt" 3 "2022年 十一月 27日 星期日" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bsp_PrintArt \- 创造一个print的重定向对象  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bsp_PrintArt\&.h>\fP
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBbsp_PrintArt\fP (void)"
.br
.ti -1c
.RI "\fBbsp_PrintArt\fP (\fBu32\fP len)"
.br
.RI "重定向后的发射数据 "
.ti -1c
.RI "int \fBprint\fP (const char *format,\&.\&.\&.)"
.br
.RI "重定向后的发射数据 "
.in -1c
.SS "Private 成员函数"

.in +1c
.ti -1c
.RI "virtual void \fBTransmit\fP (\fBu8\fP *dat, \fBu32\fP len)=0"
.br
.in -1c
.SS "Private 属性"

.in +1c
.ti -1c
.RI "\fBu32\fP \fBBufflen\fP"
.br
.in -1c
.SH "详细描述"
.PP 
创造一个print的重定向对象 
.PP
在文件 \fBbsp_PrintArt\&.h\fP 第 \fB46\fP 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "bsp_PrintArt::bsp_PrintArt (void)"

.PP
在文件 \fBbsp_PrintArt\&.cpp\fP 第 \fB60\fP 行定义\&.
.SS "bsp_PrintArt::bsp_PrintArt (\fBu32\fP len)"

.PP
重定向后的发射数据 
.PP
\fB参数\fP
.RS 4
\fIlen\fP 缓冲区大小 
.RE
.PP

.PP
在文件 \fBbsp_PrintArt\&.cpp\fP 第 \fB66\fP 行定义\&.
.SH "成员函数说明"
.PP 
.SS "int bsp_PrintArt::print (const char * format,  \&.\&.\&.)"

.PP
重定向后的发射数据 
.PP
\fB参数\fP
.RS 4
\fIformat\fP 格式化的字符串 
.br
\fI\&.\&.\&.\fP 其参数 
.RE
.PP
\fB返回\fP
.RS 4
成功与否 
.RE
.PP

.PP
在文件 \fBbsp_PrintArt\&.cpp\fP 第 \fB46\fP 行定义\&.
.SS "virtual void bsp_PrintArt::Transmit (\fBu8\fP * dat, \fBu32\fP len)\fC [private]\fP, \fC [pure virtual]\fP"

.SH "类成员变量说明"
.PP 
.SS "\fBu32\fP bsp_PrintArt::Bufflen\fC [private]\fP"

.PP
在文件 \fBbsp_PrintArt\&.h\fP 第 \fB52\fP 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
