.TH "D:/gitt/MicrochipFor32/bsp_Device/bsp_ATKESP8266.h" 3 "2022年 十一月 25日 星期五" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/MicrochipFor32/bsp_Device/bsp_ATKESP8266.h \- ATK-ESP8266模块  

.SH SYNOPSIS
.br
.PP
\fC#include 'bsp_AT\&.h'\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "class \fBbsp_ATKESP8266\fP"
.br
.RI "实现驱动ATKESP8266的类 "
.in -1c
.SH "详细描述"
.PP 
ATK-ESP8266模块 


.PP
在文件 \fBbsp_ATKESP8266\&.h\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
