.TH "D:/gitt/MicrochipFor32/bsp_Device/bsp_OLED_STM32.cpp" 3 "2022年 十一月 25日 星期五" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/MicrochipFor32/bsp_Device/bsp_OLED_STM32.cpp \- 在STM32下实现OLED通信  

.SH SYNOPSIS
.br
.PP
\fC#include 'bsp_IIC_STM32\&.h'\fP
.br
\fC#include 'bsp_OLED_STM32\&.h'\fP
.br

.SS "变量"

.in +1c
.ti -1c
.RI "const \fBu8\fP \fBOLED_WORD_ASCII\fP []"
.br
.RI "OLED的ASCII字符集 "
.in -1c
.SH "详细描述"
.PP 
在STM32下实现OLED通信 


.PP
在文件 \fBbsp_OLED_STM32\&.cpp\fP 中定义\&.
.SH "变量说明"
.PP 
.SS "const \fBu8\fP OLED_WORD_ASCII[]\fC [extern]\fP"

.PP
OLED的ASCII字符集 
.PP
在文件 \fBbsp_OLED_STM32\&.h\fP 第 \fB110\fP 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
