.TH "D:/gitt/MicrochipFor32/bsp_Device/bsp_flash.h" 3 "2022年 十一月 25日 星期五" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/MicrochipFor32/bsp_Device/bsp_flash.h \- 写STM32的Flash库  

.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br

.SS "函数"

.in +1c
.ti -1c
.RI "uint32_t \fBbsp_WriteFlashOnePage\fP (uint32_t *dat, uint32_t num)"
.br
.RI "写入一页Flash空间 "
.ti -1c
.RI "void \fBbsp_ReadFlash\fP (uint32_t *dat, uint32_t num)"
.br
.RI "读取一页Flash空间 "
.ti -1c
.RI "void \fBbsp_WriteFlash_Pack\fP (void)"
.br
.RI "将一包数据存入Flash "
.ti -1c
.RI "void \fBbsp_ReadFlash_Pack\fP (void)"
.br
.RI "从Flash读取一包数据 "
.in -1c
.SH "详细描述"
.PP 
写STM32的Flash库 


.PP
在文件 \fBbsp_flash\&.h\fP 中定义\&.
.SH "函数说明"
.PP 
.SS "void bsp_ReadFlash (uint32_t * dat, uint32_t num)"

.PP
读取一页Flash空间 
.PP
\fB参数\fP
.RS 4
\fI*dat\fP 读取数据的缓冲区 
.br
\fInum\fP 读取数量 
.RE
.PP
\fB返回\fP
.RS 4
无返回 
.RE
.PP

.PP
在文件 \fBbsp_flash\&.c\fP 第 \fB75\fP 行定义\&.
.SS "void bsp_ReadFlash_Pack (void)"

.PP
从Flash读取一包数据 
.PP
\fB返回\fP
.RS 4
无返回 
.RE
.PP

.PP
在文件 \fBbsp_flash\&.c\fP 第 \fB91\fP 行定义\&.
.SS "void bsp_WriteFlash_Pack (void)"

.PP
将一包数据存入Flash 
.PP
\fB返回\fP
.RS 4
无返回 
.RE
.PP

.PP
在文件 \fBbsp_flash\&.c\fP 第 \fB83\fP 行定义\&.
.SS "uint32_t bsp_WriteFlashOnePage (uint32_t * dat, uint32_t num)"

.PP
写入一页Flash空间 
.PP
\fB参数\fP
.RS 4
\fI*dat\fP 要写入的数据 
.br
\fInum\fP 要写入的数量 
.RE
.PP
\fB返回\fP
.RS 4
返回0则成功 
.RE
.PP

.PP
在文件 \fBbsp_flash\&.c\fP 第 \fB56\fP 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
