.TH "D:/gitt/MicrochipFor32/bsp_Device/bsp_AT/bsp_AT.h" 3 "2022年 十一月 27日 星期日" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/MicrochipFor32/bsp_Device/bsp_AT/bsp_AT.h \- AT指令集  

.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include 'varint\&.h'\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "class \fBbsp_AT\fP"
.br
.RI "AT协议的基类 "
.in -1c
.SH "详细描述"
.PP 
AT指令集 


.PP
在文件 \fBbsp_AT\&.h\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
