.TH "D:/gitt/MicrochipFor32/bsp_Device/bsp_BMP.h" 3 "2022年 十一月 24日 星期四" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/MicrochipFor32/bsp_Device/bsp_BMP.h \- 用来构造BMP图片  

.SH SYNOPSIS
.br
.PP
\fC#include 'varint\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "struct \fB_BITMAPFILEHEADER\fP"
.br
.RI "位图文件头 "
.ti -1c
.RI "struct \fB_BITMAPINFOHEADER\fP"
.br
.RI "位图信息头 "
.ti -1c
.RI "struct \fB_RGBQUAD\fP"
.br
.RI "调色板 "
.ti -1c
.RI "struct \fB_BITMAPINFO\fP"
.br
.RI "BMP文件头 "
.ti -1c
.RI "class \fBbsp_BMP\fP"
.br
.RI "构建一个BMP类 "
.in -1c
.SH "详细描述"
.PP 
用来构造BMP图片 


.PP
在文件 \fBbsp_BMP\&.h\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
