.TH "D:/gitt/MicrochipFor32/bsp_System/Callback.cpp" 3 "2022年 十一月 22日 星期二" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/MicrochipFor32/bsp_System/Callback.cpp \- 全局中断在此实现  

.SH SYNOPSIS
.br
.PP
\fC#include 'vartable\&.h'\fP
.br

.SH "详细描述"
.PP 
全局中断在此实现 


.PP
在文件 \fBCallback\&.cpp\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
