.TH "chip_cfg_s" 3 "2022年 十一月 22日 星期二" "Version 1.0.0" "Bscpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chip_cfg_s
.SH SYNOPSIS
.br
.PP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "unsigned char \fBgyro_fsr\fP"
.br
.ti -1c
.RI "unsigned char \fBaccel_fsr\fP"
.br
.ti -1c
.RI "unsigned char \fBsensors\fP"
.br
.ti -1c
.RI "unsigned char \fBlpf\fP"
.br
.ti -1c
.RI "unsigned char \fBclk_src\fP"
.br
.ti -1c
.RI "unsigned short \fBsample_rate\fP"
.br
.ti -1c
.RI "unsigned char \fBfifo_enable\fP"
.br
.ti -1c
.RI "unsigned char \fBint_enable\fP"
.br
.ti -1c
.RI "unsigned char \fBbypass_mode\fP"
.br
.ti -1c
.RI "unsigned char \fBaccel_half\fP"
.br
.ti -1c
.RI "unsigned char \fBlp_accel_mode\fP"
.br
.ti -1c
.RI "unsigned char \fBint_motion_only\fP"
.br
.ti -1c
.RI "struct \fBmotion_int_cache_s\fP \fBcache\fP"
.br
.ti -1c
.RI "unsigned char \fBactive_low_int\fP"
.br
.ti -1c
.RI "unsigned char \fBlatched_int\fP"
.br
.ti -1c
.RI "unsigned char \fBdmp_on\fP"
.br
.ti -1c
.RI "unsigned char \fBdmp_loaded\fP"
.br
.ti -1c
.RI "unsigned short \fBdmp_sample_rate\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 \fBinv_mpu\&.c\fP 第 \fB234\fP 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Bscpp 的 源代码自动生成\&.
