.TH "D:/gitt/MicrochipFor32/bsp_Device/bsp_math 目录参考" 3 "2022年 十一月 27日 星期日" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/MicrochipFor32/bsp_Device/bsp_math 目录参考
.SH SYNOPSIS
.br
.PP
.SS "文件"

.in +1c
.ti -1c
.RI "文件 \fBbsp_BMP\&.cpp\fP"
.br
.RI "用来构造BMP图片 "
.ti -1c
.RI "文件 \fBbsp_BMP\&.h\fP"
.br
.RI "用来构造BMP图片 "
.ti -1c
.RI "文件 \fBbsp_Calculus\&.cpp\fP"
.br
.RI "离散微积分 "
.ti -1c
.RI "文件 \fBbsp_Calculus\&.h\fP"
.br
.RI "离散微积分 "
.ti -1c
.RI "文件 \fBbsp_CRC\&.cpp\fP"
.br
.RI "CRC16校验 "
.ti -1c
.RI "文件 \fBbsp_CRC\&.h\fP"
.br
.RI "CRC16校验 "
.ti -1c
.RI "文件 \fBbsp_PID\&.cpp\fP"
.br
.RI "实现了PID算法 "
.ti -1c
.RI "文件 \fBbsp_PID\&.h\fP"
.br
.RI "实现了PID算法 "
.in -1c
