.TH "D:/gitt/MicrochipFor32/bsp_Device 目录参考" 3 "2022年 十一月 22日 星期二" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/MicrochipFor32/bsp_Device 目录参考
.SH SYNOPSIS
.br
.PP
.SS "文件"

.in +1c
.ti -1c
.RI "文件 \fBbsp_AT24C00\&.cpp\fP"
.br
.RI "本类实现AT24C00的通讯 "
.ti -1c
.RI "文件 \fBbsp_AT24C00\&.h\fP"
.br
.RI "本类实现AT24C00的通讯 "
.ti -1c
.RI "文件 \fBbsp_CRC\&.cpp\fP"
.br
.RI "CRC16校验 "
.ti -1c
.RI "文件 \fBbsp_CRC\&.h\fP"
.br
.RI "CRC16校验 "
.ti -1c
.RI "文件 \fBbsp_Digit\&.cpp\fP"
.br
.RI "数码管显示类 "
.ti -1c
.RI "文件 \fBbsp_Digit\&.h\fP"
.br
.RI "数码管显示类 "
.ti -1c
.RI "文件 \fBbsp_IIC\&.cpp\fP"
.br
.RI "本类实现软件IIC功能 依此类派生出其他软件IIC功能 "
.ti -1c
.RI "文件 \fBbsp_IIC\&.h\fP"
.br
.RI "本类实现软件IIC功能 依此类派生出其他软件IIC功能 "
.ti -1c
.RI "文件 \fBbsp_IIC_STM32\&.cpp\fP"
.br
.RI "实现针对STM32的软件IIC类 "
.ti -1c
.RI "文件 \fBbsp_IIC_STM32\&.h\fP"
.br
.RI "实现针对STM32的软件IIC类 "
.ti -1c
.RI "文件 \fBbsp_MAX6675\&.cpp\fP"
.br
.RI "实现了MAX6675的驱动 "
.ti -1c
.RI "文件 \fBbsp_MAX6675\&.h\fP"
.br
.RI "实现了MAX6675的驱动 "
.ti -1c
.RI "文件 \fBbsp_ModBus\&.cpp\fP"
.br
.RI "ModBus通信函数 "
.ti -1c
.RI "文件 \fBbsp_ModBus\&.h\fP"
.br
.RI "ModBus通信函数 "
.ti -1c
.RI "文件 \fBbsp_ModBus_STM32\&.cpp\fP"
.br
.RI "ModBus通信基于STM32 "
.ti -1c
.RI "文件 \fBbsp_ModBus_STM32\&.h\fP"
.br
.RI "ModBus通信基于STM32 "
.ti -1c
.RI "文件 \fBbsp_OLED_STM32\&.cpp\fP"
.br
.RI "在STM32下实现OLED通信 "
.ti -1c
.RI "文件 \fBbsp_OLED_STM32\&.h\fP"
.br
.RI "在STM32下实现OLED通信 "
.ti -1c
.RI "文件 \fBbsp_PID\&.cpp\fP"
.br
.RI "实现了PID算法 "
.ti -1c
.RI "文件 \fBbsp_PID\&.h\fP"
.br
.RI "实现了PID算法 "
.ti -1c
.RI "文件 \fBbsp_SD\&.cpp\fP"
.br
.RI "操作SD卡的库 "
.ti -1c
.RI "文件 \fBbsp_SD\&.h\fP"
.br
.ti -1c
.RI "文件 \fBvarint\&.h\fP"
.br
.in -1c
