.TH "D:/gitt/MicrochipFor32/bsp_Device/bsp_SPI 目录参考" 3 "2022年 十一月 27日 星期日" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/MicrochipFor32/bsp_Device/bsp_SPI 目录参考
.SH SYNOPSIS
.br
.PP
.SS "文件"

.in +1c
.ti -1c
.RI "文件 \fBbsp_MAX6675\&.cpp\fP"
.br
.RI "实现了MAX6675的驱动 "
.ti -1c
.RI "文件 \fBbsp_MAX6675\&.h\fP"
.br
.RI "实现了MAX6675的驱动 "
.ti -1c
.RI "文件 \fBbsp_SD\&.cpp\fP"
.br
.RI "操作SD卡的库 "
.ti -1c
.RI "文件 \fBbsp_SD\&.h\fP"
.br
.RI "操作SD卡的库 "
.in -1c
