.TH "D:/gitt/MicrochipFor32/bsp_Device 目录参考" 3 "2022年 十一月 27日 星期日" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/MicrochipFor32/bsp_Device 目录参考
.SH SYNOPSIS
.br
.PP
.SS "目录"

.in +1c
.ti -1c
.RI "目录 \fBbsp_AT\fP"
.br
.ti -1c
.RI "目录 \fBbsp_IIC\fP"
.br
.ti -1c
.RI "目录 \fBbsp_math\fP"
.br
.ti -1c
.RI "目录 \fBbsp_ModBus\fP"
.br
.ti -1c
.RI "目录 \fBbsp_SPI\fP"
.br
.in -1c
.SS "文件"

.in +1c
.ti -1c
.RI "文件 \fBbsp_Digit\&.cpp\fP"
.br
.RI "数码管显示类 "
.ti -1c
.RI "文件 \fBbsp_Digit\&.h\fP"
.br
.RI "数码管显示类 "
.ti -1c
.RI "文件 \fBbsp_flash\&.c\fP"
.br
.RI "写STM32的Flash库 "
.ti -1c
.RI "文件 \fBbsp_flash\&.h\fP"
.br
.RI "写STM32的Flash库 "
.ti -1c
.RI "文件 \fBbsp_PrintArt\&.cpp\fP"
.br
.RI "print重定向的艺术 "
.ti -1c
.RI "文件 \fBbsp_PrintArt\&.h\fP"
.br
.RI "print重定向的艺术 "
.ti -1c
.RI "文件 \fBvarint\&.h\fP"
.br
.RI "全局共用的标准类型表 "
.in -1c
