.TH "D:/gitt/MicrochipFor32/bsp_MPU6050 目录参考" 3 "2022年 十一月 25日 星期五" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/MicrochipFor32/bsp_MPU6050 目录参考
.SH SYNOPSIS
.br
.PP
.SS "文件"

.in +1c
.ti -1c
.RI "文件 \fBmpu6050\&.cpp\fP"
.br
.ti -1c
.RI "文件 \fBmpu6050\&.h\fP"
.br
.in -1c
