.TH "D:/gitt/MicrochipFor32/bsp_Device/bsp_IIC 目录参考" 3 "2022年 十一月 27日 星期日" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/MicrochipFor32/bsp_Device/bsp_IIC 目录参考
.SH SYNOPSIS
.br
.PP
.SS "文件"

.in +1c
.ti -1c
.RI "文件 \fBbsp_AT24C00\&.cpp\fP"
.br
.RI "本类实现AT24C00的通讯 "
.ti -1c
.RI "文件 \fBbsp_AT24C00\&.h\fP"
.br
.RI "本类实现AT24C00的通讯 "
.ti -1c
.RI "文件 \fBbsp_IIC\&.cpp\fP"
.br
.RI "本类实现软件IIC功能 依此类派生出其他软件IIC功能 "
.ti -1c
.RI "文件 \fBbsp_IIC\&.h\fP"
.br
.RI "本类实现软件IIC功能 依此类派生出其他软件IIC功能 "
.ti -1c
.RI "文件 \fBbsp_IIC_STM32\&.cpp\fP"
.br
.RI "实现针对STM32的软件IIC类 "
.ti -1c
.RI "文件 \fBbsp_IIC_STM32\&.h\fP"
.br
.RI "实现针对STM32的软件IIC类 "
.ti -1c
.RI "文件 \fBbsp_OLED_STM32\&.cpp\fP"
.br
.RI "在STM32下实现OLED通信 "
.ti -1c
.RI "文件 \fBbsp_OLED_STM32\&.h\fP"
.br
.RI "在STM32下实现OLED通信 "
.in -1c
