.TH "dmp_s" 3 "2022年 十一月 22日 星期二" "Version 1.0.0" "Bscpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dmp_s
.SH SYNOPSIS
.br
.PP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "void(* \fBtap_cb\fP )(unsigned char count, unsigned char direction)"
.br
.ti -1c
.RI "void(* \fBandroid_orient_cb\fP )(unsigned char orientation)"
.br
.ti -1c
.RI "unsigned short \fBorient\fP"
.br
.ti -1c
.RI "unsigned short \fBfeature_mask\fP"
.br
.ti -1c
.RI "unsigned short \fBfifo_rate\fP"
.br
.ti -1c
.RI "unsigned char \fBpacket_length\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 \fBinv_mpu_dmp_motion_driver\&.c\fP 第 \fB481\fP 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "void(* dmp_s::android_orient_cb) (unsigned char orientation)"

.PP
在文件 \fBinv_mpu_dmp_motion_driver\&.c\fP 第 \fB483\fP 行定义\&.
.SS "unsigned short dmp_s::feature_mask"

.PP
在文件 \fBinv_mpu_dmp_motion_driver\&.c\fP 第 \fB485\fP 行定义\&.
.SS "unsigned short dmp_s::fifo_rate"

.PP
在文件 \fBinv_mpu_dmp_motion_driver\&.c\fP 第 \fB486\fP 行定义\&.
.SS "unsigned short dmp_s::orient"

.PP
在文件 \fBinv_mpu_dmp_motion_driver\&.c\fP 第 \fB484\fP 行定义\&.
.SS "unsigned char dmp_s::packet_length"

.PP
在文件 \fBinv_mpu_dmp_motion_driver\&.c\fP 第 \fB487\fP 行定义\&.
.SS "void(* dmp_s::tap_cb) (unsigned char count, unsigned char direction)"

.PP
在文件 \fBinv_mpu_dmp_motion_driver\&.c\fP 第 \fB482\fP 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Bscpp 的 源代码自动生成\&.
