.TH "D:/gitt/MicrochipFor32/bsp_MPU6050/dmpKey.h" 3 "2022年 十一月 22日 星期二" "Version 1.0.0" "Bscpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/MicrochipFor32/bsp_MPU6050/dmpKey.h
.SH SYNOPSIS
.br
.PP
.SS "类"

.in +1c
.ti -1c
.RI "struct \fBtKeyLabel\fP"
.br
.in -1c
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBKEY_CFG_25\fP   (0)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_24\fP   (\fBKEY_CFG_25\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_26\fP   (\fBKEY_CFG_24\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_27\fP   (\fBKEY_CFG_26\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_21\fP   (\fBKEY_CFG_27\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_20\fP   (\fBKEY_CFG_21\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_TAP4\fP   (\fBKEY_CFG_20\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_TAP5\fP   (\fBKEY_CFG_TAP4\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_TAP6\fP   (\fBKEY_CFG_TAP5\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_TAP7\fP   (\fBKEY_CFG_TAP6\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_TAP0\fP   (\fBKEY_CFG_TAP7\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_TAP1\fP   (\fBKEY_CFG_TAP0\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_TAP2\fP   (\fBKEY_CFG_TAP1\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_TAP3\fP   (\fBKEY_CFG_TAP2\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_TAP_QUANTIZE\fP   (\fBKEY_CFG_TAP3\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_TAP_JERK\fP   (\fBKEY_CFG_TAP_QUANTIZE\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_DR_INT\fP   (\fBKEY_CFG_TAP_JERK\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_AUTH\fP   (\fBKEY_CFG_DR_INT\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_TAP_SAVE_ACCB\fP   (\fBKEY_CFG_AUTH\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_TAP_CLEAR_STICKY\fP   (\fBKEY_CFG_TAP_SAVE_ACCB\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_FIFO_ON_EVENT\fP   (\fBKEY_CFG_TAP_CLEAR_STICKY\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_FCFG_ACCEL_INPUT\fP   (\fBKEY_CFG_FIFO_ON_EVENT\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_FCFG_ACCEL_INIT\fP   (\fBKEY_FCFG_ACCEL_INPUT\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_23\fP   (\fBKEY_FCFG_ACCEL_INIT\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_FCFG_1\fP   (\fBKEY_CFG_23\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_FCFG_3\fP   (\fBKEY_FCFG_1\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_FCFG_2\fP   (\fBKEY_FCFG_3\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_3D\fP   (\fBKEY_FCFG_2\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_3B\fP   (\fBKEY_CFG_3D\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_3C\fP   (\fBKEY_CFG_3B\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_FCFG_5\fP   (\fBKEY_CFG_3C\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_FCFG_4\fP   (\fBKEY_FCFG_5\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_FCFG_7\fP   (\fBKEY_FCFG_4\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_FCFG_FSCALE\fP   (\fBKEY_FCFG_7\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_FCFG_AZ\fP   (\fBKEY_FCFG_FSCALE\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_FCFG_6\fP   (\fBKEY_FCFG_AZ\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_FCFG_LSB4\fP   (\fBKEY_FCFG_6\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_12\fP   (\fBKEY_FCFG_LSB4\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_14\fP   (\fBKEY_CFG_12\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_15\fP   (\fBKEY_CFG_14\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_16\fP   (\fBKEY_CFG_15\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_18\fP   (\fBKEY_CFG_16\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_6\fP   (\fBKEY_CFG_18\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_7\fP   (\fBKEY_CFG_6\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_4\fP   (\fBKEY_CFG_7\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_5\fP   (\fBKEY_CFG_4\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_2\fP   (\fBKEY_CFG_5\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_3\fP   (\fBKEY_CFG_2\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_1\fP   (\fBKEY_CFG_3\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_EXTERNAL\fP   (\fBKEY_CFG_1\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_8\fP   (\fBKEY_CFG_EXTERNAL\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_9\fP   (\fBKEY_CFG_8\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_ORIENT_3\fP   (\fBKEY_CFG_9\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_ORIENT_2\fP   (\fBKEY_CFG_ORIENT_3\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_ORIENT_1\fP   (\fBKEY_CFG_ORIENT_2\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_GYRO_SOURCE\fP   (\fBKEY_CFG_ORIENT_1\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_ORIENT_IRQ_1\fP   (\fBKEY_CFG_GYRO_SOURCE\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_ORIENT_IRQ_2\fP   (\fBKEY_CFG_ORIENT_IRQ_1\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_ORIENT_IRQ_3\fP   (\fBKEY_CFG_ORIENT_IRQ_2\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_FCFG_MAG_VAL\fP   (\fBKEY_CFG_ORIENT_IRQ_3\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_FCFG_MAG_MOV\fP   (\fBKEY_FCFG_MAG_VAL\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_LP_QUAT\fP   (\fBKEY_FCFG_MAG_MOV\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_ACCEL_FILTER\fP   (\fBKEY_CFG_LP_QUAT\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_MOTION_BIAS\fP   (\fBKEY_CFG_ACCEL_FILTER\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_TEMPLABEL\fP   (\fBKEY_CFG_MOTION_BIAS\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_0_22\fP   (\fBKEY_TEMPLABEL\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_0_24\fP   (\fBKEY_D_0_22\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_0_36\fP   (\fBKEY_D_0_24\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_0_52\fP   (\fBKEY_D_0_36\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_0_96\fP   (\fBKEY_D_0_52\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_0_104\fP   (\fBKEY_D_0_96\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_0_108\fP   (\fBKEY_D_0_104\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_0_163\fP   (\fBKEY_D_0_108\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_0_188\fP   (\fBKEY_D_0_163\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_0_192\fP   (\fBKEY_D_0_188\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_0_224\fP   (\fBKEY_D_0_192\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_0_228\fP   (\fBKEY_D_0_224\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_0_232\fP   (\fBKEY_D_0_228\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_0_236\fP   (\fBKEY_D_0_232\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_PREVPTAT\fP   (\fBKEY_D_0_236\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_2\fP   (\fBKEY_DMP_PREVPTAT\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_4\fP   (\fBKEY_D_1_2\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_8\fP   (\fBKEY_D_1_4\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_10\fP   (\fBKEY_D_1_8\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_24\fP   (\fBKEY_D_1_10\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_28\fP   (\fBKEY_D_1_24\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_36\fP   (\fBKEY_D_1_28\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_40\fP   (\fBKEY_D_1_36\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_44\fP   (\fBKEY_D_1_40\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_72\fP   (\fBKEY_D_1_44\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_74\fP   (\fBKEY_D_1_72\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_79\fP   (\fBKEY_D_1_74\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_88\fP   (\fBKEY_D_1_79\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_90\fP   (\fBKEY_D_1_88\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_92\fP   (\fBKEY_D_1_90\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_96\fP   (\fBKEY_D_1_92\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_98\fP   (\fBKEY_D_1_96\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_100\fP   (\fBKEY_D_1_98\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_106\fP   (\fBKEY_D_1_100\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_108\fP   (\fBKEY_D_1_106\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_112\fP   (\fBKEY_D_1_108\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_128\fP   (\fBKEY_D_1_112\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_152\fP   (\fBKEY_D_1_128\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_160\fP   (\fBKEY_D_1_152\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_168\fP   (\fBKEY_D_1_160\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_175\fP   (\fBKEY_D_1_168\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_176\fP   (\fBKEY_D_1_175\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_178\fP   (\fBKEY_D_1_176\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_179\fP   (\fBKEY_D_1_178\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_218\fP   (\fBKEY_D_1_179\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_232\fP   (\fBKEY_D_1_218\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_236\fP   (\fBKEY_D_1_232\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_240\fP   (\fBKEY_D_1_236\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_244\fP   (\fBKEY_D_1_240\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_250\fP   (\fBKEY_D_1_244\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_1_252\fP   (\fBKEY_D_1_250\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_2_12\fP   (\fBKEY_D_1_252\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_2_96\fP   (\fBKEY_D_2_12\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_2_108\fP   (\fBKEY_D_2_96\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_2_208\fP   (\fBKEY_D_2_108\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_FLICK_MSG\fP   (\fBKEY_D_2_208\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_FLICK_COUNTER\fP   (\fBKEY_FLICK_MSG\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_FLICK_LOWER\fP   (\fBKEY_FLICK_COUNTER\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_FLICK_IN\fP   (\fBKEY_FLICK_LOWER\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_FLICK_UPPER\fP   (\fBKEY_CFG_FLICK_IN\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CGNOTICE_INTR\fP   (\fBKEY_FLICK_UPPER\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_2_224\fP   (\fBKEY_CGNOTICE_INTR\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_2_244\fP   (\fBKEY_D_2_224\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_2_248\fP   (\fBKEY_D_2_244\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_2_252\fP   (\fBKEY_D_2_248\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_GYRO_BIAS_X\fP   (\fBKEY_D_2_252\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_GYRO_BIAS_Y\fP   (\fBKEY_D_GYRO_BIAS_X\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_GYRO_BIAS_Z\fP   (\fBKEY_D_GYRO_BIAS_Y\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_ACC_BIAS_X\fP   (\fBKEY_D_GYRO_BIAS_Z\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_ACC_BIAS_Y\fP   (\fBKEY_D_ACC_BIAS_X\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_ACC_BIAS_Z\fP   (\fBKEY_D_ACC_BIAS_Y\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_GYRO_ENABLE\fP   (\fBKEY_D_ACC_BIAS_Z\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_ACCEL_ENABLE\fP   (\fBKEY_D_GYRO_ENABLE\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_QUAT_ENABLE\fP   (\fBKEY_D_ACCEL_ENABLE\fP +1)"
.br
.ti -1c
.RI "#define \fBKEY_D_OUTPUT_ENABLE\fP   (\fBKEY_D_QUAT_ENABLE\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_CR_TIME_G\fP   (\fBKEY_D_OUTPUT_ENABLE\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_CR_TIME_A\fP   (\fBKEY_D_CR_TIME_G\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_CR_TIME_Q\fP   (\fBKEY_D_CR_TIME_A\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_CS_TAX\fP   (\fBKEY_D_CR_TIME_Q\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_CS_TAY\fP   (\fBKEY_D_CS_TAX\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_CS_TAZ\fP   (\fBKEY_D_CS_TAY\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_CS_TGX\fP   (\fBKEY_D_CS_TAZ\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_CS_TGY\fP   (\fBKEY_D_CS_TGX\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_CS_TGZ\fP   (\fBKEY_D_CS_TGY\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_CS_TQ0\fP   (\fBKEY_D_CS_TGZ\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_CS_TQ1\fP   (\fBKEY_D_CS_TQ0\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_CS_TQ2\fP   (\fBKEY_D_CS_TQ1\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_CS_TQ3\fP   (\fBKEY_D_CS_TQ2\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CPASS_BIAS_X\fP   (\fBKEY_D_CS_TQ3\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CPASS_BIAS_Y\fP   (\fBKEY_CPASS_BIAS_X\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CPASS_BIAS_Z\fP   (\fBKEY_CPASS_BIAS_Y\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CPASS_MTX_00\fP   (\fBKEY_CPASS_BIAS_Z\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CPASS_MTX_01\fP   (\fBKEY_CPASS_MTX_00\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CPASS_MTX_02\fP   (\fBKEY_CPASS_MTX_01\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CPASS_MTX_10\fP   (\fBKEY_CPASS_MTX_02\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CPASS_MTX_11\fP   (\fBKEY_CPASS_MTX_10\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CPASS_MTX_12\fP   (\fBKEY_CPASS_MTX_11\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CPASS_MTX_20\fP   (\fBKEY_CPASS_MTX_12\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CPASS_MTX_21\fP   (\fBKEY_CPASS_MTX_20\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CPASS_MTX_22\fP   (\fBKEY_CPASS_MTX_21\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_TAPW_MIN\fP   (\fBKEY_CPASS_MTX_22\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_TAP_THR_X\fP   (\fBKEY_DMP_TAPW_MIN\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_TAP_THR_Y\fP   (\fBKEY_DMP_TAP_THR_X\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_TAP_THR_Z\fP   (\fBKEY_DMP_TAP_THR_Y\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_SH_TH_Y\fP   (\fBKEY_DMP_TAP_THR_Z\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_SH_TH_X\fP   (\fBKEY_DMP_SH_TH_Y\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_SH_TH_Z\fP   (\fBKEY_DMP_SH_TH_X\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_ORIENT\fP   (\fBKEY_DMP_SH_TH_Z\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_ACT0\fP   (\fBKEY_DMP_ORIENT\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_ACSX\fP   (\fBKEY_D_ACT0\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_ACSY\fP   (\fBKEY_D_ACSX\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_ACSZ\fP   (\fBKEY_D_ACSY\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_X_GRT_Y_TMP\fP   (\fBKEY_D_ACSZ\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_SKIP_X_GRT_Y_TMP\fP   (\fBKEY_X_GRT_Y_TMP\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_SKIP_END_COMPARE\fP   (\fBKEY_SKIP_X_GRT_Y_TMP\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_END_COMPARE_Y_X_TMP2\fP   (\fBKEY_SKIP_END_COMPARE\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_CFG_ANDROID_ORIENT_INT\fP   (\fBKEY_END_COMPARE_Y_X_TMP2\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_NO_ORIENT_INTERRUPT\fP   (\fBKEY_CFG_ANDROID_ORIENT_INT\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_END_COMPARE_Y_X_TMP\fP   (\fBKEY_NO_ORIENT_INTERRUPT\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_END_ORIENT_1\fP   (\fBKEY_END_COMPARE_Y_X_TMP\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_END_COMPARE_Y_X\fP   (\fBKEY_END_ORIENT_1\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_END_ORIENT\fP   (\fBKEY_END_COMPARE_Y_X\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_X_GRT_Y\fP   (\fBKEY_END_ORIENT\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_NOT_TIME_MINUS_1\fP   (\fBKEY_X_GRT_Y\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_END_COMPARE_Y_X_TMP3\fP   (\fBKEY_NOT_TIME_MINUS_1\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_X_GRT_Y_TMP2\fP   (\fBKEY_END_COMPARE_Y_X_TMP3\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_AUTH_OUT\fP   (\fBKEY_X_GRT_Y_TMP2\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_AUTH_IN\fP   (\fBKEY_D_AUTH_OUT\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_AUTH_A\fP   (\fBKEY_D_AUTH_IN\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_AUTH_B\fP   (\fBKEY_D_AUTH_A\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_PEDSTD_BP_B\fP   (\fBKEY_D_AUTH_B\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_PEDSTD_HP_A\fP   (\fBKEY_D_PEDSTD_BP_B\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_PEDSTD_HP_B\fP   (\fBKEY_D_PEDSTD_HP_A\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_PEDSTD_BP_A4\fP   (\fBKEY_D_PEDSTD_HP_B\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_PEDSTD_BP_A3\fP   (\fBKEY_D_PEDSTD_BP_A4\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_PEDSTD_BP_A2\fP   (\fBKEY_D_PEDSTD_BP_A3\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_PEDSTD_BP_A1\fP   (\fBKEY_D_PEDSTD_BP_A2\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_PEDSTD_INT_THRSH\fP   (\fBKEY_D_PEDSTD_BP_A1\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_PEDSTD_CLIP\fP   (\fBKEY_D_PEDSTD_INT_THRSH\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_PEDSTD_SB\fP   (\fBKEY_D_PEDSTD_CLIP\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_PEDSTD_SB_TIME\fP   (\fBKEY_D_PEDSTD_SB\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_PEDSTD_PEAKTHRSH\fP   (\fBKEY_D_PEDSTD_SB_TIME\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_PEDSTD_TIML\fP   (\fBKEY_D_PEDSTD_PEAKTHRSH\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_PEDSTD_TIMH\fP   (\fBKEY_D_PEDSTD_TIML\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_PEDSTD_PEAK\fP   (\fBKEY_D_PEDSTD_TIMH\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_PEDSTD_TIMECTR\fP   (\fBKEY_D_PEDSTD_PEAK\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_PEDSTD_STEPCTR\fP   (\fBKEY_D_PEDSTD_TIMECTR\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_PEDSTD_WALKTIME\fP   (\fBKEY_D_PEDSTD_STEPCTR\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_PEDSTD_DECI\fP   (\fBKEY_D_PEDSTD_WALKTIME\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_D_HOST_NO_MOT\fP   (\fBKEY_D_PEDSTD_DECI\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_P_EIS_FIFO_FOOTER\fP   (\fBKEY_D_HOST_NO_MOT\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_P_EIS_FIFO_YSHIFT\fP   (\fBKEY_P_EIS_FIFO_FOOTER\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_P_EIS_DATA_RATE\fP   (\fBKEY_P_EIS_FIFO_YSHIFT\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_P_EIS_FIFO_XSHIFT\fP   (\fBKEY_P_EIS_DATA_RATE\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_P_EIS_FIFO_SYNC\fP   (\fBKEY_P_EIS_FIFO_XSHIFT\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_P_EIS_FIFO_ZSHIFT\fP   (\fBKEY_P_EIS_FIFO_SYNC\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_P_EIS_FIFO_READY\fP   (\fBKEY_P_EIS_FIFO_ZSHIFT\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_FOOTER\fP   (\fBKEY_P_EIS_FIFO_READY\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_INTX_HC\fP   (\fBKEY_DMP_FOOTER\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_INTX_PH\fP   (\fBKEY_DMP_INTX_HC\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_INTX_SH\fP   (\fBKEY_DMP_INTX_PH\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_AINV_SH\fP   (\fBKEY_DMP_INTX_SH\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_A_INV_XH\fP   (\fBKEY_DMP_AINV_SH\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_AINV_PH\fP   (\fBKEY_DMP_A_INV_XH\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_CTHX_H\fP   (\fBKEY_DMP_AINV_PH\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_CTHY_H\fP   (\fBKEY_DMP_CTHX_H\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_CTHZ_H\fP   (\fBKEY_DMP_CTHY_H\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_NCTHX_H\fP   (\fBKEY_DMP_CTHZ_H\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_NCTHY_H\fP   (\fBKEY_DMP_NCTHX_H\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_NCTHZ_H\fP   (\fBKEY_DMP_NCTHY_H\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_CTSQ_XH\fP   (\fBKEY_DMP_NCTHZ_H\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_CTSQ_YH\fP   (\fBKEY_DMP_CTSQ_XH\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_CTSQ_ZH\fP   (\fBKEY_DMP_CTSQ_YH\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_INTX_H\fP   (\fBKEY_DMP_CTSQ_ZH\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_INTY_H\fP   (\fBKEY_DMP_INTX_H\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_DMP_INTZ_H\fP   (\fBKEY_DMP_INTY_H\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_STREAM_P_GYRO_Z\fP   (\fBKEY_DMP_INTZ_H\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_STREAM_P_GYRO_Y\fP   (\fBKEY_STREAM_P_GYRO_Z\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_STREAM_P_GYRO_X\fP   (\fBKEY_STREAM_P_GYRO_Y\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_STREAM_P_TEMP\fP   (\fBKEY_STREAM_P_GYRO_X\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_STREAM_P_AUX_Y\fP   (\fBKEY_STREAM_P_TEMP\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_STREAM_P_AUX_X\fP   (\fBKEY_STREAM_P_AUX_Y\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_STREAM_P_AUX_Z\fP   (\fBKEY_STREAM_P_AUX_X\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_STREAM_P_ACCEL_Y\fP   (\fBKEY_STREAM_P_AUX_Z\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_STREAM_P_ACCEL_X\fP   (\fBKEY_STREAM_P_ACCEL_Y\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_STREAM_P_FOOTER\fP   (\fBKEY_STREAM_P_ACCEL_X\fP + 1)"
.br
.ti -1c
.RI "#define \fBKEY_STREAM_P_ACCEL_Z\fP   (\fBKEY_STREAM_P_FOOTER\fP + 1)"
.br
.ti -1c
.RI "#define \fBNUM_KEYS\fP   (\fBKEY_STREAM_P_ACCEL_Z\fP + 1)"
.br
.ti -1c
.RI "#define \fBDINA0A\fP   0x0a"
.br
.ti -1c
.RI "#define \fBDINA22\fP   0x22"
.br
.ti -1c
.RI "#define \fBDINA42\fP   0x42"
.br
.ti -1c
.RI "#define \fBDINA5A\fP   0x5a"
.br
.ti -1c
.RI "#define \fBDINA06\fP   0x06"
.br
.ti -1c
.RI "#define \fBDINA0E\fP   0x0e"
.br
.ti -1c
.RI "#define \fBDINA16\fP   0x16"
.br
.ti -1c
.RI "#define \fBDINA1E\fP   0x1e"
.br
.ti -1c
.RI "#define \fBDINA26\fP   0x26"
.br
.ti -1c
.RI "#define \fBDINA2E\fP   0x2e"
.br
.ti -1c
.RI "#define \fBDINA36\fP   0x36"
.br
.ti -1c
.RI "#define \fBDINA3E\fP   0x3e"
.br
.ti -1c
.RI "#define \fBDINA46\fP   0x46"
.br
.ti -1c
.RI "#define \fBDINA4E\fP   0x4e"
.br
.ti -1c
.RI "#define \fBDINA56\fP   0x56"
.br
.ti -1c
.RI "#define \fBDINA5E\fP   0x5e"
.br
.ti -1c
.RI "#define \fBDINA66\fP   0x66"
.br
.ti -1c
.RI "#define \fBDINA6E\fP   0x6e"
.br
.ti -1c
.RI "#define \fBDINA76\fP   0x76"
.br
.ti -1c
.RI "#define \fBDINA7E\fP   0x7e"
.br
.ti -1c
.RI "#define \fBDINA00\fP   0x00"
.br
.ti -1c
.RI "#define \fBDINA08\fP   0x08"
.br
.ti -1c
.RI "#define \fBDINA10\fP   0x10"
.br
.ti -1c
.RI "#define \fBDINA18\fP   0x18"
.br
.ti -1c
.RI "#define \fBDINA20\fP   0x20"
.br
.ti -1c
.RI "#define \fBDINA28\fP   0x28"
.br
.ti -1c
.RI "#define \fBDINA30\fP   0x30"
.br
.ti -1c
.RI "#define \fBDINA38\fP   0x38"
.br
.ti -1c
.RI "#define \fBDINA40\fP   0x40"
.br
.ti -1c
.RI "#define \fBDINA48\fP   0x48"
.br
.ti -1c
.RI "#define \fBDINA50\fP   0x50"
.br
.ti -1c
.RI "#define \fBDINA58\fP   0x58"
.br
.ti -1c
.RI "#define \fBDINA60\fP   0x60"
.br
.ti -1c
.RI "#define \fBDINA68\fP   0x68"
.br
.ti -1c
.RI "#define \fBDINA70\fP   0x70"
.br
.ti -1c
.RI "#define \fBDINA78\fP   0x78"
.br
.ti -1c
.RI "#define \fBDINA04\fP   0x04"
.br
.ti -1c
.RI "#define \fBDINA0C\fP   0x0c"
.br
.ti -1c
.RI "#define \fBDINA14\fP   0x14"
.br
.ti -1c
.RI "#define \fBDINA1C\fP   0x1C"
.br
.ti -1c
.RI "#define \fBDINA24\fP   0x24"
.br
.ti -1c
.RI "#define \fBDINA2C\fP   0x2c"
.br
.ti -1c
.RI "#define \fBDINA34\fP   0x34"
.br
.ti -1c
.RI "#define \fBDINA3C\fP   0x3c"
.br
.ti -1c
.RI "#define \fBDINA44\fP   0x44"
.br
.ti -1c
.RI "#define \fBDINA4C\fP   0x4c"
.br
.ti -1c
.RI "#define \fBDINA54\fP   0x54"
.br
.ti -1c
.RI "#define \fBDINA5C\fP   0x5c"
.br
.ti -1c
.RI "#define \fBDINA64\fP   0x64"
.br
.ti -1c
.RI "#define \fBDINA6C\fP   0x6c"
.br
.ti -1c
.RI "#define \fBDINA74\fP   0x74"
.br
.ti -1c
.RI "#define \fBDINA7C\fP   0x7c"
.br
.ti -1c
.RI "#define \fBDINA01\fP   0x01"
.br
.ti -1c
.RI "#define \fBDINA09\fP   0x09"
.br
.ti -1c
.RI "#define \fBDINA11\fP   0x11"
.br
.ti -1c
.RI "#define \fBDINA19\fP   0x19"
.br
.ti -1c
.RI "#define \fBDINA21\fP   0x21"
.br
.ti -1c
.RI "#define \fBDINA29\fP   0x29"
.br
.ti -1c
.RI "#define \fBDINA31\fP   0x31"
.br
.ti -1c
.RI "#define \fBDINA39\fP   0x39"
.br
.ti -1c
.RI "#define \fBDINA41\fP   0x41"
.br
.ti -1c
.RI "#define \fBDINA49\fP   0x49"
.br
.ti -1c
.RI "#define \fBDINA51\fP   0x51"
.br
.ti -1c
.RI "#define \fBDINA59\fP   0x59"
.br
.ti -1c
.RI "#define \fBDINA61\fP   0x61"
.br
.ti -1c
.RI "#define \fBDINA69\fP   0x69"
.br
.ti -1c
.RI "#define \fBDINA71\fP   0x71"
.br
.ti -1c
.RI "#define \fBDINA79\fP   0x79"
.br
.ti -1c
.RI "#define \fBDINA25\fP   0x25"
.br
.ti -1c
.RI "#define \fBDINA2D\fP   0x2d"
.br
.ti -1c
.RI "#define \fBDINA35\fP   0x35"
.br
.ti -1c
.RI "#define \fBDINA3D\fP   0x3d"
.br
.ti -1c
.RI "#define \fBDINA4D\fP   0x4d"
.br
.ti -1c
.RI "#define \fBDINA55\fP   0x55"
.br
.ti -1c
.RI "#define \fBDINA5D\fP   0x5D"
.br
.ti -1c
.RI "#define \fBDINA6D\fP   0x6d"
.br
.ti -1c
.RI "#define \fBDINA75\fP   0x75"
.br
.ti -1c
.RI "#define \fBDINA7D\fP   0x7d"
.br
.ti -1c
.RI "#define \fBDINADC\fP   0xdc"
.br
.ti -1c
.RI "#define \fBDINAF2\fP   0xf2"
.br
.ti -1c
.RI "#define \fBDINAAB\fP   0xab"
.br
.ti -1c
.RI "#define \fBDINAAA\fP   0xaa"
.br
.ti -1c
.RI "#define \fBDINAF1\fP   0xf1"
.br
.ti -1c
.RI "#define \fBDINADF\fP   0xdf"
.br
.ti -1c
.RI "#define \fBDINADA\fP   0xda"
.br
.ti -1c
.RI "#define \fBDINAB1\fP   0xb1"
.br
.ti -1c
.RI "#define \fBDINAB9\fP   0xb9"
.br
.ti -1c
.RI "#define \fBDINAF3\fP   0xf3"
.br
.ti -1c
.RI "#define \fBDINA8B\fP   0x8b"
.br
.ti -1c
.RI "#define \fBDINAA3\fP   0xa3"
.br
.ti -1c
.RI "#define \fBDINA91\fP   0x91"
.br
.ti -1c
.RI "#define \fBDINAB6\fP   0xb6"
.br
.ti -1c
.RI "#define \fBDINAB4\fP   0xb4"
.br
.ti -1c
.RI "#define \fBDINC00\fP   0x00"
.br
.ti -1c
.RI "#define \fBDINC01\fP   0x01"
.br
.ti -1c
.RI "#define \fBDINC02\fP   0x02"
.br
.ti -1c
.RI "#define \fBDINC03\fP   0x03"
.br
.ti -1c
.RI "#define \fBDINC08\fP   0x08"
.br
.ti -1c
.RI "#define \fBDINC09\fP   0x09"
.br
.ti -1c
.RI "#define \fBDINC0A\fP   0x0a"
.br
.ti -1c
.RI "#define \fBDINC0B\fP   0x0b"
.br
.ti -1c
.RI "#define \fBDINC10\fP   0x10"
.br
.ti -1c
.RI "#define \fBDINC11\fP   0x11"
.br
.ti -1c
.RI "#define \fBDINC12\fP   0x12"
.br
.ti -1c
.RI "#define \fBDINC13\fP   0x13"
.br
.ti -1c
.RI "#define \fBDINC18\fP   0x18"
.br
.ti -1c
.RI "#define \fBDINC19\fP   0x19"
.br
.ti -1c
.RI "#define \fBDINC1A\fP   0x1a"
.br
.ti -1c
.RI "#define \fBDINC1B\fP   0x1b"
.br
.ti -1c
.RI "#define \fBDINC20\fP   0x20"
.br
.ti -1c
.RI "#define \fBDINC21\fP   0x21"
.br
.ti -1c
.RI "#define \fBDINC22\fP   0x22"
.br
.ti -1c
.RI "#define \fBDINC23\fP   0x23"
.br
.ti -1c
.RI "#define \fBDINC28\fP   0x28"
.br
.ti -1c
.RI "#define \fBDINC29\fP   0x29"
.br
.ti -1c
.RI "#define \fBDINC2A\fP   0x2a"
.br
.ti -1c
.RI "#define \fBDINC2B\fP   0x2b"
.br
.ti -1c
.RI "#define \fBDINC30\fP   0x30"
.br
.ti -1c
.RI "#define \fBDINC31\fP   0x31"
.br
.ti -1c
.RI "#define \fBDINC32\fP   0x32"
.br
.ti -1c
.RI "#define \fBDINC33\fP   0x33"
.br
.ti -1c
.RI "#define \fBDINC38\fP   0x38"
.br
.ti -1c
.RI "#define \fBDINC39\fP   0x39"
.br
.ti -1c
.RI "#define \fBDINC3A\fP   0x3a"
.br
.ti -1c
.RI "#define \fBDINC3B\fP   0x3b"
.br
.ti -1c
.RI "#define \fBDINC40\fP   0x40"
.br
.ti -1c
.RI "#define \fBDINC41\fP   0x41"
.br
.ti -1c
.RI "#define \fBDINC42\fP   0x42"
.br
.ti -1c
.RI "#define \fBDINC43\fP   0x43"
.br
.ti -1c
.RI "#define \fBDINC48\fP   0x48"
.br
.ti -1c
.RI "#define \fBDINC49\fP   0x49"
.br
.ti -1c
.RI "#define \fBDINC4A\fP   0x4a"
.br
.ti -1c
.RI "#define \fBDINC4B\fP   0x4b"
.br
.ti -1c
.RI "#define \fBDINC50\fP   0x50"
.br
.ti -1c
.RI "#define \fBDINC51\fP   0x51"
.br
.ti -1c
.RI "#define \fBDINC52\fP   0x52"
.br
.ti -1c
.RI "#define \fBDINC53\fP   0x53"
.br
.ti -1c
.RI "#define \fBDINC58\fP   0x58"
.br
.ti -1c
.RI "#define \fBDINC59\fP   0x59"
.br
.ti -1c
.RI "#define \fBDINC5A\fP   0x5a"
.br
.ti -1c
.RI "#define \fBDINC5B\fP   0x5b"
.br
.ti -1c
.RI "#define \fBDINC60\fP   0x60"
.br
.ti -1c
.RI "#define \fBDINC61\fP   0x61"
.br
.ti -1c
.RI "#define \fBDINC62\fP   0x62"
.br
.ti -1c
.RI "#define \fBDINC63\fP   0x63"
.br
.ti -1c
.RI "#define \fBDINC68\fP   0x68"
.br
.ti -1c
.RI "#define \fBDINC69\fP   0x69"
.br
.ti -1c
.RI "#define \fBDINC6A\fP   0x6a"
.br
.ti -1c
.RI "#define \fBDINC6B\fP   0x6b"
.br
.ti -1c
.RI "#define \fBDINC70\fP   0x70"
.br
.ti -1c
.RI "#define \fBDINC71\fP   0x71"
.br
.ti -1c
.RI "#define \fBDINC72\fP   0x72"
.br
.ti -1c
.RI "#define \fBDINC73\fP   0x73"
.br
.ti -1c
.RI "#define \fBDINC78\fP   0x78"
.br
.ti -1c
.RI "#define \fBDINC79\fP   0x79"
.br
.ti -1c
.RI "#define \fBDINC7A\fP   0x7a"
.br
.ti -1c
.RI "#define \fBDINC7B\fP   0x7b"
.br
.ti -1c
.RI "#define \fBDIND40\fP   0x40"
.br
.ti -1c
.RI "#define \fBDINA80\fP   0x80"
.br
.ti -1c
.RI "#define \fBDINA90\fP   0x90"
.br
.ti -1c
.RI "#define \fBDINAA0\fP   0xa0"
.br
.ti -1c
.RI "#define \fBDINAC9\fP   0xc9"
.br
.ti -1c
.RI "#define \fBDINACB\fP   0xcb"
.br
.ti -1c
.RI "#define \fBDINACD\fP   0xcd"
.br
.ti -1c
.RI "#define \fBDINACF\fP   0xcf"
.br
.ti -1c
.RI "#define \fBDINAC8\fP   0xc8"
.br
.ti -1c
.RI "#define \fBDINACA\fP   0xca"
.br
.ti -1c
.RI "#define \fBDINACC\fP   0xcc"
.br
.ti -1c
.RI "#define \fBDINACE\fP   0xce"
.br
.ti -1c
.RI "#define \fBDINAD8\fP   0xd8"
.br
.ti -1c
.RI "#define \fBDINADD\fP   0xdd"
.br
.ti -1c
.RI "#define \fBDINAF8\fP   0xf0"
.br
.ti -1c
.RI "#define \fBDINAFE\fP   0xfe"
.br
.ti -1c
.RI "#define \fBDINBF8\fP   0xf8"
.br
.ti -1c
.RI "#define \fBDINAC0\fP   0xb0"
.br
.ti -1c
.RI "#define \fBDINAC1\fP   0xb1"
.br
.ti -1c
.RI "#define \fBDINAC2\fP   0xb4"
.br
.ti -1c
.RI "#define \fBDINAC3\fP   0xb5"
.br
.ti -1c
.RI "#define \fBDINAC4\fP   0xb8"
.br
.ti -1c
.RI "#define \fBDINAC5\fP   0xb9"
.br
.ti -1c
.RI "#define \fBDINBC0\fP   0xc0"
.br
.ti -1c
.RI "#define \fBDINBC2\fP   0xc2"
.br
.ti -1c
.RI "#define \fBDINBC4\fP   0xc4"
.br
.ti -1c
.RI "#define \fBDINBC6\fP   0xc6"
.br
.in -1c
.SH "宏定义说明"
.PP 
.SS "#define DINA00   0x00"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB314\fP 行定义\&.
.SS "#define DINA01   0x01"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB348\fP 行定义\&.
.SS "#define DINA04   0x04"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB331\fP 行定义\&.
.SS "#define DINA06   0x06"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB297\fP 行定义\&.
.SS "#define DINA08   0x08"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB315\fP 行定义\&.
.SS "#define DINA09   0x09"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB349\fP 行定义\&.
.SS "#define DINA0A   0x0a"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB292\fP 行定义\&.
.SS "#define DINA0C   0x0c"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB332\fP 行定义\&.
.SS "#define DINA0E   0x0e"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB298\fP 行定义\&.
.SS "#define DINA10   0x10"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB316\fP 行定义\&.
.SS "#define DINA11   0x11"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB350\fP 行定义\&.
.SS "#define DINA14   0x14"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB333\fP 行定义\&.
.SS "#define DINA16   0x16"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB299\fP 行定义\&.
.SS "#define DINA18   0x18"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB317\fP 行定义\&.
.SS "#define DINA19   0x19"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB351\fP 行定义\&.
.SS "#define DINA1C   0x1C"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB334\fP 行定义\&.
.SS "#define DINA1E   0x1e"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB300\fP 行定义\&.
.SS "#define DINA20   0x20"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB318\fP 行定义\&.
.SS "#define DINA21   0x21"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB352\fP 行定义\&.
.SS "#define DINA22   0x22"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB293\fP 行定义\&.
.SS "#define DINA24   0x24"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB335\fP 行定义\&.
.SS "#define DINA25   0x25"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB365\fP 行定义\&.
.SS "#define DINA26   0x26"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB301\fP 行定义\&.
.SS "#define DINA28   0x28"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB319\fP 行定义\&.
.SS "#define DINA29   0x29"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB353\fP 行定义\&.
.SS "#define DINA2C   0x2c"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB336\fP 行定义\&.
.SS "#define DINA2D   0x2d"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB366\fP 行定义\&.
.SS "#define DINA2E   0x2e"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB302\fP 行定义\&.
.SS "#define DINA30   0x30"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB320\fP 行定义\&.
.SS "#define DINA31   0x31"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB354\fP 行定义\&.
.SS "#define DINA34   0x34"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB337\fP 行定义\&.
.SS "#define DINA35   0x35"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB367\fP 行定义\&.
.SS "#define DINA36   0x36"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB303\fP 行定义\&.
.SS "#define DINA38   0x38"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB321\fP 行定义\&.
.SS "#define DINA39   0x39"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB355\fP 行定义\&.
.SS "#define DINA3C   0x3c"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB338\fP 行定义\&.
.SS "#define DINA3D   0x3d"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB368\fP 行定义\&.
.SS "#define DINA3E   0x3e"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB304\fP 行定义\&.
.SS "#define DINA40   0x40"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB322\fP 行定义\&.
.SS "#define DINA41   0x41"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB356\fP 行定义\&.
.SS "#define DINA42   0x42"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB294\fP 行定义\&.
.SS "#define DINA44   0x44"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB339\fP 行定义\&.
.SS "#define DINA46   0x46"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB305\fP 行定义\&.
.SS "#define DINA48   0x48"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB323\fP 行定义\&.
.SS "#define DINA49   0x49"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB357\fP 行定义\&.
.SS "#define DINA4C   0x4c"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB340\fP 行定义\&.
.SS "#define DINA4D   0x4d"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB369\fP 行定义\&.
.SS "#define DINA4E   0x4e"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB306\fP 行定义\&.
.SS "#define DINA50   0x50"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB324\fP 行定义\&.
.SS "#define DINA51   0x51"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB358\fP 行定义\&.
.SS "#define DINA54   0x54"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB341\fP 行定义\&.
.SS "#define DINA55   0x55"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB370\fP 行定义\&.
.SS "#define DINA56   0x56"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB307\fP 行定义\&.
.SS "#define DINA58   0x58"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB325\fP 行定义\&.
.SS "#define DINA59   0x59"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB359\fP 行定义\&.
.SS "#define DINA5A   0x5a"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB295\fP 行定义\&.
.SS "#define DINA5C   0x5c"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB342\fP 行定义\&.
.SS "#define DINA5D   0x5D"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB371\fP 行定义\&.
.SS "#define DINA5E   0x5e"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB308\fP 行定义\&.
.SS "#define DINA60   0x60"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB326\fP 行定义\&.
.SS "#define DINA61   0x61"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB360\fP 行定义\&.
.SS "#define DINA64   0x64"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB343\fP 行定义\&.
.SS "#define DINA66   0x66"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB309\fP 行定义\&.
.SS "#define DINA68   0x68"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB327\fP 行定义\&.
.SS "#define DINA69   0x69"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB361\fP 行定义\&.
.SS "#define DINA6C   0x6c"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB344\fP 行定义\&.
.SS "#define DINA6D   0x6d"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB372\fP 行定义\&.
.SS "#define DINA6E   0x6e"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB310\fP 行定义\&.
.SS "#define DINA70   0x70"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB328\fP 行定义\&.
.SS "#define DINA71   0x71"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB362\fP 行定义\&.
.SS "#define DINA74   0x74"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB345\fP 行定义\&.
.SS "#define DINA75   0x75"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB373\fP 行定义\&.
.SS "#define DINA76   0x76"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB311\fP 行定义\&.
.SS "#define DINA78   0x78"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB329\fP 行定义\&.
.SS "#define DINA79   0x79"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB363\fP 行定义\&.
.SS "#define DINA7C   0x7c"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB346\fP 行定义\&.
.SS "#define DINA7D   0x7d"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB374\fP 行定义\&.
.SS "#define DINA7E   0x7e"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB312\fP 行定义\&.
.SS "#define DINA80   0x80"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB464\fP 行定义\&.
.SS "#define DINA8B   0x8b"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB386\fP 行定义\&.
.SS "#define DINA90   0x90"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB465\fP 行定义\&.
.SS "#define DINA91   0x91"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB388\fP 行定义\&.
.SS "#define DINAA0   0xa0"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB466\fP 行定义\&.
.SS "#define DINAA3   0xa3"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB387\fP 行定义\&.
.SS "#define DINAAA   0xaa"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB379\fP 行定义\&.
.SS "#define DINAAB   0xab"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB378\fP 行定义\&.
.SS "#define DINAB1   0xb1"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB383\fP 行定义\&.
.SS "#define DINAB4   0xb4"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB390\fP 行定义\&.
.SS "#define DINAB6   0xb6"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB389\fP 行定义\&.
.SS "#define DINAB9   0xb9"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB384\fP 行定义\&.
.SS "#define DINAC0   0xb0"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB481\fP 行定义\&.
.SS "#define DINAC1   0xb1"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB482\fP 行定义\&.
.SS "#define DINAC2   0xb4"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB483\fP 行定义\&.
.SS "#define DINAC3   0xb5"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB484\fP 行定义\&.
.SS "#define DINAC4   0xb8"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB485\fP 行定义\&.
.SS "#define DINAC5   0xb9"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB486\fP 行定义\&.
.SS "#define DINAC8   0xc8"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB471\fP 行定义\&.
.SS "#define DINAC9   0xc9"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB467\fP 行定义\&.
.SS "#define DINACA   0xca"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB472\fP 行定义\&.
.SS "#define DINACB   0xcb"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB468\fP 行定义\&.
.SS "#define DINACC   0xcc"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB473\fP 行定义\&.
.SS "#define DINACD   0xcd"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB469\fP 行定义\&.
.SS "#define DINACE   0xce"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB474\fP 行定义\&.
.SS "#define DINACF   0xcf"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB470\fP 行定义\&.
.SS "#define DINAD8   0xd8"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB475\fP 行定义\&.
.SS "#define DINADA   0xda"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB382\fP 行定义\&.
.SS "#define DINADC   0xdc"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB376\fP 行定义\&.
.SS "#define DINADD   0xdd"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB476\fP 行定义\&.
.SS "#define DINADF   0xdf"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB381\fP 行定义\&.
.SS "#define DINAF1   0xf1"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB380\fP 行定义\&.
.SS "#define DINAF2   0xf2"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB377\fP 行定义\&.
.SS "#define DINAF3   0xf3"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB385\fP 行定义\&.
.SS "#define DINAF8   0xf0"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB477\fP 行定义\&.
.SS "#define DINAFE   0xfe"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB478\fP 行定义\&.
.SS "#define DINBC0   0xc0"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB487\fP 行定义\&.
.SS "#define DINBC2   0xc2"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB488\fP 行定义\&.
.SS "#define DINBC4   0xc4"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB489\fP 行定义\&.
.SS "#define DINBC6   0xc6"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB490\fP 行定义\&.
.SS "#define DINBF8   0xf8"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB480\fP 行定义\&.
.SS "#define DINC00   0x00"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB393\fP 行定义\&.
.SS "#define DINC01   0x01"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB394\fP 行定义\&.
.SS "#define DINC02   0x02"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB395\fP 行定义\&.
.SS "#define DINC03   0x03"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB396\fP 行定义\&.
.SS "#define DINC08   0x08"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB397\fP 行定义\&.
.SS "#define DINC09   0x09"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB398\fP 行定义\&.
.SS "#define DINC0A   0x0a"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB399\fP 行定义\&.
.SS "#define DINC0B   0x0b"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB400\fP 行定义\&.
.SS "#define DINC10   0x10"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB401\fP 行定义\&.
.SS "#define DINC11   0x11"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB402\fP 行定义\&.
.SS "#define DINC12   0x12"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB403\fP 行定义\&.
.SS "#define DINC13   0x13"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB404\fP 行定义\&.
.SS "#define DINC18   0x18"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB405\fP 行定义\&.
.SS "#define DINC19   0x19"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB406\fP 行定义\&.
.SS "#define DINC1A   0x1a"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB407\fP 行定义\&.
.SS "#define DINC1B   0x1b"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB408\fP 行定义\&.
.SS "#define DINC20   0x20"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB410\fP 行定义\&.
.SS "#define DINC21   0x21"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB411\fP 行定义\&.
.SS "#define DINC22   0x22"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB412\fP 行定义\&.
.SS "#define DINC23   0x23"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB413\fP 行定义\&.
.SS "#define DINC28   0x28"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB414\fP 行定义\&.
.SS "#define DINC29   0x29"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB415\fP 行定义\&.
.SS "#define DINC2A   0x2a"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB416\fP 行定义\&.
.SS "#define DINC2B   0x2b"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB417\fP 行定义\&.
.SS "#define DINC30   0x30"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB418\fP 行定义\&.
.SS "#define DINC31   0x31"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB419\fP 行定义\&.
.SS "#define DINC32   0x32"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB420\fP 行定义\&.
.SS "#define DINC33   0x33"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB421\fP 行定义\&.
.SS "#define DINC38   0x38"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB422\fP 行定义\&.
.SS "#define DINC39   0x39"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB423\fP 行定义\&.
.SS "#define DINC3A   0x3a"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB424\fP 行定义\&.
.SS "#define DINC3B   0x3b"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB425\fP 行定义\&.
.SS "#define DINC40   0x40"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB427\fP 行定义\&.
.SS "#define DINC41   0x41"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB428\fP 行定义\&.
.SS "#define DINC42   0x42"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB429\fP 行定义\&.
.SS "#define DINC43   0x43"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB430\fP 行定义\&.
.SS "#define DINC48   0x48"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB431\fP 行定义\&.
.SS "#define DINC49   0x49"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB432\fP 行定义\&.
.SS "#define DINC4A   0x4a"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB433\fP 行定义\&.
.SS "#define DINC4B   0x4b"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB434\fP 行定义\&.
.SS "#define DINC50   0x50"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB435\fP 行定义\&.
.SS "#define DINC51   0x51"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB436\fP 行定义\&.
.SS "#define DINC52   0x52"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB437\fP 行定义\&.
.SS "#define DINC53   0x53"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB438\fP 行定义\&.
.SS "#define DINC58   0x58"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB439\fP 行定义\&.
.SS "#define DINC59   0x59"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB440\fP 行定义\&.
.SS "#define DINC5A   0x5a"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB441\fP 行定义\&.
.SS "#define DINC5B   0x5b"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB442\fP 行定义\&.
.SS "#define DINC60   0x60"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB444\fP 行定义\&.
.SS "#define DINC61   0x61"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB445\fP 行定义\&.
.SS "#define DINC62   0x62"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB446\fP 行定义\&.
.SS "#define DINC63   0x63"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB447\fP 行定义\&.
.SS "#define DINC68   0x68"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB448\fP 行定义\&.
.SS "#define DINC69   0x69"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB449\fP 行定义\&.
.SS "#define DINC6A   0x6a"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB450\fP 行定义\&.
.SS "#define DINC6B   0x6b"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB451\fP 行定义\&.
.SS "#define DINC70   0x70"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB452\fP 行定义\&.
.SS "#define DINC71   0x71"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB453\fP 行定义\&.
.SS "#define DINC72   0x72"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB454\fP 行定义\&.
.SS "#define DINC73   0x73"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB455\fP 行定义\&.
.SS "#define DINC78   0x78"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB456\fP 行定义\&.
.SS "#define DINC79   0x79"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB457\fP 行定义\&.
.SS "#define DINC7A   0x7a"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB458\fP 行定义\&.
.SS "#define DINC7B   0x7b"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB459\fP 行定义\&.
.SS "#define DIND40   0x40"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB461\fP 行定义\&.
.SS "#define KEY_CFG_1   (\fBKEY_CFG_3\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB57\fP 行定义\&.
.SS "#define KEY_CFG_12   (\fBKEY_FCFG_LSB4\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB46\fP 行定义\&.
.SS "#define KEY_CFG_14   (\fBKEY_CFG_12\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB47\fP 行定义\&.
.SS "#define KEY_CFG_15   (\fBKEY_CFG_14\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB48\fP 行定义\&.
.SS "#define KEY_CFG_16   (\fBKEY_CFG_15\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB49\fP 行定义\&.
.SS "#define KEY_CFG_18   (\fBKEY_CFG_16\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB50\fP 行定义\&.
.SS "#define KEY_CFG_2   (\fBKEY_CFG_5\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB55\fP 行定义\&.
.SS "#define KEY_CFG_20   (\fBKEY_CFG_21\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB14\fP 行定义\&.
.SS "#define KEY_CFG_21   (\fBKEY_CFG_27\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB13\fP 行定义\&.
.SS "#define KEY_CFG_23   (\fBKEY_FCFG_ACCEL_INIT\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB32\fP 行定义\&.
.SS "#define KEY_CFG_24   (\fBKEY_CFG_25\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB10\fP 行定义\&.
.SS "#define KEY_CFG_25   (0)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB9\fP 行定义\&.
.SS "#define KEY_CFG_26   (\fBKEY_CFG_24\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB11\fP 行定义\&.
.SS "#define KEY_CFG_27   (\fBKEY_CFG_26\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB12\fP 行定义\&.
.SS "#define KEY_CFG_3   (\fBKEY_CFG_2\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB56\fP 行定义\&.
.SS "#define KEY_CFG_3B   (\fBKEY_CFG_3D\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB37\fP 行定义\&.
.SS "#define KEY_CFG_3C   (\fBKEY_CFG_3B\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB38\fP 行定义\&.
.SS "#define KEY_CFG_3D   (\fBKEY_FCFG_2\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB36\fP 行定义\&.
.SS "#define KEY_CFG_4   (\fBKEY_CFG_7\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB53\fP 行定义\&.
.SS "#define KEY_CFG_5   (\fBKEY_CFG_4\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB54\fP 行定义\&.
.SS "#define KEY_CFG_6   (\fBKEY_CFG_18\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB51\fP 行定义\&.
.SS "#define KEY_CFG_7   (\fBKEY_CFG_6\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB52\fP 行定义\&.
.SS "#define KEY_CFG_8   (\fBKEY_CFG_EXTERNAL\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB59\fP 行定义\&.
.SS "#define KEY_CFG_9   (\fBKEY_CFG_8\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB60\fP 行定义\&.
.SS "#define KEY_CFG_ACCEL_FILTER   (\fBKEY_CFG_LP_QUAT\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB73\fP 行定义\&.
.SS "#define KEY_CFG_ANDROID_ORIENT_INT   (\fBKEY_END_COMPARE_Y_X_TMP2\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB200\fP 行定义\&.
.SS "#define KEY_CFG_AUTH   (\fBKEY_CFG_DR_INT\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB26\fP 行定义\&.
.SS "#define KEY_CFG_DR_INT   (\fBKEY_CFG_TAP_JERK\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB25\fP 行定义\&.
.SS "#define KEY_CFG_EXTERNAL   (\fBKEY_CFG_1\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB58\fP 行定义\&.
.SS "#define KEY_CFG_FIFO_ON_EVENT   (\fBKEY_CFG_TAP_CLEAR_STICKY\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB29\fP 行定义\&.
.SS "#define KEY_CFG_FLICK_IN   (\fBKEY_FLICK_LOWER\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB136\fP 行定义\&.
.SS "#define KEY_CFG_GYRO_SOURCE   (\fBKEY_CFG_ORIENT_1\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB64\fP 行定义\&.
.SS "#define KEY_CFG_LP_QUAT   (\fBKEY_FCFG_MAG_MOV\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB70\fP 行定义\&.
.SS "#define KEY_CFG_MOTION_BIAS   (\fBKEY_CFG_ACCEL_FILTER\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB74\fP 行定义\&.
.SS "#define KEY_CFG_ORIENT_1   (\fBKEY_CFG_ORIENT_2\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB63\fP 行定义\&.
.SS "#define KEY_CFG_ORIENT_2   (\fBKEY_CFG_ORIENT_3\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB62\fP 行定义\&.
.SS "#define KEY_CFG_ORIENT_3   (\fBKEY_CFG_9\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB61\fP 行定义\&.
.SS "#define KEY_CFG_ORIENT_IRQ_1   (\fBKEY_CFG_GYRO_SOURCE\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB65\fP 行定义\&.
.SS "#define KEY_CFG_ORIENT_IRQ_2   (\fBKEY_CFG_ORIENT_IRQ_1\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB66\fP 行定义\&.
.SS "#define KEY_CFG_ORIENT_IRQ_3   (\fBKEY_CFG_ORIENT_IRQ_2\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB67\fP 行定义\&.
.SS "#define KEY_CFG_TAP0   (\fBKEY_CFG_TAP7\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB19\fP 行定义\&.
.SS "#define KEY_CFG_TAP1   (\fBKEY_CFG_TAP0\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB20\fP 行定义\&.
.SS "#define KEY_CFG_TAP2   (\fBKEY_CFG_TAP1\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB21\fP 行定义\&.
.SS "#define KEY_CFG_TAP3   (\fBKEY_CFG_TAP2\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB22\fP 行定义\&.
.SS "#define KEY_CFG_TAP4   (\fBKEY_CFG_20\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB15\fP 行定义\&.
.SS "#define KEY_CFG_TAP5   (\fBKEY_CFG_TAP4\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB16\fP 行定义\&.
.SS "#define KEY_CFG_TAP6   (\fBKEY_CFG_TAP5\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB17\fP 行定义\&.
.SS "#define KEY_CFG_TAP7   (\fBKEY_CFG_TAP6\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB18\fP 行定义\&.
.SS "#define KEY_CFG_TAP_CLEAR_STICKY   (\fBKEY_CFG_TAP_SAVE_ACCB\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB28\fP 行定义\&.
.SS "#define KEY_CFG_TAP_JERK   (\fBKEY_CFG_TAP_QUANTIZE\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB24\fP 行定义\&.
.SS "#define KEY_CFG_TAP_QUANTIZE   (\fBKEY_CFG_TAP3\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB23\fP 行定义\&.
.SS "#define KEY_CFG_TAP_SAVE_ACCB   (\fBKEY_CFG_AUTH\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB27\fP 行定义\&.
.SS "#define KEY_CGNOTICE_INTR   (\fBKEY_FLICK_UPPER\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB138\fP 行定义\&.
.SS "#define KEY_CPASS_BIAS_X   (\fBKEY_D_CS_TQ3\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB169\fP 行定义\&.
.SS "#define KEY_CPASS_BIAS_Y   (\fBKEY_CPASS_BIAS_X\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB170\fP 行定义\&.
.SS "#define KEY_CPASS_BIAS_Z   (\fBKEY_CPASS_BIAS_Y\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB171\fP 行定义\&.
.SS "#define KEY_CPASS_MTX_00   (\fBKEY_CPASS_BIAS_Z\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB172\fP 行定义\&.
.SS "#define KEY_CPASS_MTX_01   (\fBKEY_CPASS_MTX_00\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB173\fP 行定义\&.
.SS "#define KEY_CPASS_MTX_02   (\fBKEY_CPASS_MTX_01\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB174\fP 行定义\&.
.SS "#define KEY_CPASS_MTX_10   (\fBKEY_CPASS_MTX_02\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB175\fP 行定义\&.
.SS "#define KEY_CPASS_MTX_11   (\fBKEY_CPASS_MTX_10\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB176\fP 行定义\&.
.SS "#define KEY_CPASS_MTX_12   (\fBKEY_CPASS_MTX_11\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB177\fP 行定义\&.
.SS "#define KEY_CPASS_MTX_20   (\fBKEY_CPASS_MTX_12\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB178\fP 行定义\&.
.SS "#define KEY_CPASS_MTX_21   (\fBKEY_CPASS_MTX_20\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB179\fP 行定义\&.
.SS "#define KEY_CPASS_MTX_22   (\fBKEY_CPASS_MTX_21\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB180\fP 行定义\&.
.SS "#define KEY_D_0_104   (\fBKEY_D_0_96\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB82\fP 行定义\&.
.SS "#define KEY_D_0_108   (\fBKEY_D_0_104\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB83\fP 行定义\&.
.SS "#define KEY_D_0_163   (\fBKEY_D_0_108\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB84\fP 行定义\&.
.SS "#define KEY_D_0_188   (\fBKEY_D_0_163\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB85\fP 行定义\&.
.SS "#define KEY_D_0_192   (\fBKEY_D_0_188\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB86\fP 行定义\&.
.SS "#define KEY_D_0_22   (\fBKEY_TEMPLABEL\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB77\fP 行定义\&.
.SS "#define KEY_D_0_224   (\fBKEY_D_0_192\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB87\fP 行定义\&.
.SS "#define KEY_D_0_228   (\fBKEY_D_0_224\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB88\fP 行定义\&.
.SS "#define KEY_D_0_232   (\fBKEY_D_0_228\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB89\fP 行定义\&.
.SS "#define KEY_D_0_236   (\fBKEY_D_0_232\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB90\fP 行定义\&.
.SS "#define KEY_D_0_24   (\fBKEY_D_0_22\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB78\fP 行定义\&.
.SS "#define KEY_D_0_36   (\fBKEY_D_0_24\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB79\fP 行定义\&.
.SS "#define KEY_D_0_52   (\fBKEY_D_0_36\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB80\fP 行定义\&.
.SS "#define KEY_D_0_96   (\fBKEY_D_0_52\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB81\fP 行定义\&.
.SS "#define KEY_D_1_10   (\fBKEY_D_1_8\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB96\fP 行定义\&.
.SS "#define KEY_D_1_100   (\fBKEY_D_1_98\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB110\fP 行定义\&.
.SS "#define KEY_D_1_106   (\fBKEY_D_1_100\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB111\fP 行定义\&.
.SS "#define KEY_D_1_108   (\fBKEY_D_1_106\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB112\fP 行定义\&.
.SS "#define KEY_D_1_112   (\fBKEY_D_1_108\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB113\fP 行定义\&.
.SS "#define KEY_D_1_128   (\fBKEY_D_1_112\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB114\fP 行定义\&.
.SS "#define KEY_D_1_152   (\fBKEY_D_1_128\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB115\fP 行定义\&.
.SS "#define KEY_D_1_160   (\fBKEY_D_1_152\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB116\fP 行定义\&.
.SS "#define KEY_D_1_168   (\fBKEY_D_1_160\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB117\fP 行定义\&.
.SS "#define KEY_D_1_175   (\fBKEY_D_1_168\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB118\fP 行定义\&.
.SS "#define KEY_D_1_176   (\fBKEY_D_1_175\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB119\fP 行定义\&.
.SS "#define KEY_D_1_178   (\fBKEY_D_1_176\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB120\fP 行定义\&.
.SS "#define KEY_D_1_179   (\fBKEY_D_1_178\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB121\fP 行定义\&.
.SS "#define KEY_D_1_2   (\fBKEY_DMP_PREVPTAT\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB93\fP 行定义\&.
.SS "#define KEY_D_1_218   (\fBKEY_D_1_179\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB122\fP 行定义\&.
.SS "#define KEY_D_1_232   (\fBKEY_D_1_218\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB123\fP 行定义\&.
.SS "#define KEY_D_1_236   (\fBKEY_D_1_232\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB124\fP 行定义\&.
.SS "#define KEY_D_1_24   (\fBKEY_D_1_10\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB97\fP 行定义\&.
.SS "#define KEY_D_1_240   (\fBKEY_D_1_236\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB125\fP 行定义\&.
.SS "#define KEY_D_1_244   (\fBKEY_D_1_240\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB126\fP 行定义\&.
.SS "#define KEY_D_1_250   (\fBKEY_D_1_244\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB127\fP 行定义\&.
.SS "#define KEY_D_1_252   (\fBKEY_D_1_250\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB128\fP 行定义\&.
.SS "#define KEY_D_1_28   (\fBKEY_D_1_24\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB98\fP 行定义\&.
.SS "#define KEY_D_1_36   (\fBKEY_D_1_28\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB99\fP 行定义\&.
.SS "#define KEY_D_1_4   (\fBKEY_D_1_2\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB94\fP 行定义\&.
.SS "#define KEY_D_1_40   (\fBKEY_D_1_36\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB100\fP 行定义\&.
.SS "#define KEY_D_1_44   (\fBKEY_D_1_40\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB101\fP 行定义\&.
.SS "#define KEY_D_1_72   (\fBKEY_D_1_44\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB102\fP 行定义\&.
.SS "#define KEY_D_1_74   (\fBKEY_D_1_72\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB103\fP 行定义\&.
.SS "#define KEY_D_1_79   (\fBKEY_D_1_74\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB104\fP 行定义\&.
.SS "#define KEY_D_1_8   (\fBKEY_D_1_4\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB95\fP 行定义\&.
.SS "#define KEY_D_1_88   (\fBKEY_D_1_79\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB105\fP 行定义\&.
.SS "#define KEY_D_1_90   (\fBKEY_D_1_88\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB106\fP 行定义\&.
.SS "#define KEY_D_1_92   (\fBKEY_D_1_90\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB107\fP 行定义\&.
.SS "#define KEY_D_1_96   (\fBKEY_D_1_92\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB108\fP 行定义\&.
.SS "#define KEY_D_1_98   (\fBKEY_D_1_96\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB109\fP 行定义\&.
.SS "#define KEY_D_2_108   (\fBKEY_D_2_96\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB131\fP 行定义\&.
.SS "#define KEY_D_2_12   (\fBKEY_D_1_252\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB129\fP 行定义\&.
.SS "#define KEY_D_2_208   (\fBKEY_D_2_108\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB132\fP 行定义\&.
.SS "#define KEY_D_2_224   (\fBKEY_CGNOTICE_INTR\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB139\fP 行定义\&.
.SS "#define KEY_D_2_244   (\fBKEY_D_2_224\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB140\fP 行定义\&.
.SS "#define KEY_D_2_248   (\fBKEY_D_2_244\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB141\fP 行定义\&.
.SS "#define KEY_D_2_252   (\fBKEY_D_2_248\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB142\fP 行定义\&.
.SS "#define KEY_D_2_96   (\fBKEY_D_2_12\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB130\fP 行定义\&.
.SS "#define KEY_D_ACC_BIAS_X   (\fBKEY_D_GYRO_BIAS_Z\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB147\fP 行定义\&.
.SS "#define KEY_D_ACC_BIAS_Y   (\fBKEY_D_ACC_BIAS_X\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB148\fP 行定义\&.
.SS "#define KEY_D_ACC_BIAS_Z   (\fBKEY_D_ACC_BIAS_Y\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB149\fP 行定义\&.
.SS "#define KEY_D_ACCEL_ENABLE   (\fBKEY_D_GYRO_ENABLE\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB151\fP 行定义\&.
.SS "#define KEY_D_ACSX   (\fBKEY_D_ACT0\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB192\fP 行定义\&.
.SS "#define KEY_D_ACSY   (\fBKEY_D_ACSX\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB193\fP 行定义\&.
.SS "#define KEY_D_ACSZ   (\fBKEY_D_ACSY\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB194\fP 行定义\&.
.SS "#define KEY_D_ACT0   (\fBKEY_DMP_ORIENT\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB191\fP 行定义\&.
.SS "#define KEY_D_AUTH_A   (\fBKEY_D_AUTH_IN\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB214\fP 行定义\&.
.SS "#define KEY_D_AUTH_B   (\fBKEY_D_AUTH_A\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB215\fP 行定义\&.
.SS "#define KEY_D_AUTH_IN   (\fBKEY_D_AUTH_OUT\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB213\fP 行定义\&.
.SS "#define KEY_D_AUTH_OUT   (\fBKEY_X_GRT_Y_TMP2\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB212\fP 行定义\&.
.SS "#define KEY_D_CR_TIME_A   (\fBKEY_D_CR_TIME_G\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB155\fP 行定义\&.
.SS "#define KEY_D_CR_TIME_G   (\fBKEY_D_OUTPUT_ENABLE\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB154\fP 行定义\&.
.SS "#define KEY_D_CR_TIME_Q   (\fBKEY_D_CR_TIME_A\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB156\fP 行定义\&.
.SS "#define KEY_D_CS_TAX   (\fBKEY_D_CR_TIME_Q\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB157\fP 行定义\&.
.SS "#define KEY_D_CS_TAY   (\fBKEY_D_CS_TAX\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB158\fP 行定义\&.
.SS "#define KEY_D_CS_TAZ   (\fBKEY_D_CS_TAY\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB159\fP 行定义\&.
.SS "#define KEY_D_CS_TGX   (\fBKEY_D_CS_TAZ\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB160\fP 行定义\&.
.SS "#define KEY_D_CS_TGY   (\fBKEY_D_CS_TGX\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB161\fP 行定义\&.
.SS "#define KEY_D_CS_TGZ   (\fBKEY_D_CS_TGY\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB162\fP 行定义\&.
.SS "#define KEY_D_CS_TQ0   (\fBKEY_D_CS_TGZ\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB163\fP 行定义\&.
.SS "#define KEY_D_CS_TQ1   (\fBKEY_D_CS_TQ0\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB164\fP 行定义\&.
.SS "#define KEY_D_CS_TQ2   (\fBKEY_D_CS_TQ1\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB165\fP 行定义\&.
.SS "#define KEY_D_CS_TQ3   (\fBKEY_D_CS_TQ2\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB166\fP 行定义\&.
.SS "#define KEY_D_GYRO_BIAS_X   (\fBKEY_D_2_252\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB144\fP 行定义\&.
.SS "#define KEY_D_GYRO_BIAS_Y   (\fBKEY_D_GYRO_BIAS_X\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB145\fP 行定义\&.
.SS "#define KEY_D_GYRO_BIAS_Z   (\fBKEY_D_GYRO_BIAS_Y\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB146\fP 行定义\&.
.SS "#define KEY_D_GYRO_ENABLE   (\fBKEY_D_ACC_BIAS_Z\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB150\fP 行定义\&.
.SS "#define KEY_D_HOST_NO_MOT   (\fBKEY_D_PEDSTD_DECI\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB239\fP 行定义\&.
.SS "#define KEY_D_OUTPUT_ENABLE   (\fBKEY_D_QUAT_ENABLE\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB153\fP 行定义\&.
.SS "#define KEY_D_PEDSTD_BP_A1   (\fBKEY_D_PEDSTD_BP_A2\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB224\fP 行定义\&.
.SS "#define KEY_D_PEDSTD_BP_A2   (\fBKEY_D_PEDSTD_BP_A3\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB223\fP 行定义\&.
.SS "#define KEY_D_PEDSTD_BP_A3   (\fBKEY_D_PEDSTD_BP_A4\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB222\fP 行定义\&.
.SS "#define KEY_D_PEDSTD_BP_A4   (\fBKEY_D_PEDSTD_HP_B\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB221\fP 行定义\&.
.SS "#define KEY_D_PEDSTD_BP_B   (\fBKEY_D_AUTH_B\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB218\fP 行定义\&.
.SS "#define KEY_D_PEDSTD_CLIP   (\fBKEY_D_PEDSTD_INT_THRSH\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB226\fP 行定义\&.
.SS "#define KEY_D_PEDSTD_DECI   (\fBKEY_D_PEDSTD_WALKTIME\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB236\fP 行定义\&.
.SS "#define KEY_D_PEDSTD_HP_A   (\fBKEY_D_PEDSTD_BP_B\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB219\fP 行定义\&.
.SS "#define KEY_D_PEDSTD_HP_B   (\fBKEY_D_PEDSTD_HP_A\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB220\fP 行定义\&.
.SS "#define KEY_D_PEDSTD_INT_THRSH   (\fBKEY_D_PEDSTD_BP_A1\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB225\fP 行定义\&.
.SS "#define KEY_D_PEDSTD_PEAK   (\fBKEY_D_PEDSTD_TIMH\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB232\fP 行定义\&.
.SS "#define KEY_D_PEDSTD_PEAKTHRSH   (\fBKEY_D_PEDSTD_SB_TIME\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB229\fP 行定义\&.
.SS "#define KEY_D_PEDSTD_SB   (\fBKEY_D_PEDSTD_CLIP\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB227\fP 行定义\&.
.SS "#define KEY_D_PEDSTD_SB_TIME   (\fBKEY_D_PEDSTD_SB\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB228\fP 行定义\&.
.SS "#define KEY_D_PEDSTD_STEPCTR   (\fBKEY_D_PEDSTD_TIMECTR\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB234\fP 行定义\&.
.SS "#define KEY_D_PEDSTD_TIMECTR   (\fBKEY_D_PEDSTD_PEAK\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB233\fP 行定义\&.
.SS "#define KEY_D_PEDSTD_TIMH   (\fBKEY_D_PEDSTD_TIML\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB231\fP 行定义\&.
.SS "#define KEY_D_PEDSTD_TIML   (\fBKEY_D_PEDSTD_PEAKTHRSH\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB230\fP 行定义\&.
.SS "#define KEY_D_PEDSTD_WALKTIME   (\fBKEY_D_PEDSTD_STEPCTR\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB235\fP 行定义\&.
.SS "#define KEY_D_QUAT_ENABLE   (\fBKEY_D_ACCEL_ENABLE\fP +1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB152\fP 行定义\&.
.SS "#define KEY_DMP_A_INV_XH   (\fBKEY_DMP_AINV_SH\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB254\fP 行定义\&.
.SS "#define KEY_DMP_AINV_PH   (\fBKEY_DMP_A_INV_XH\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB255\fP 行定义\&.
.SS "#define KEY_DMP_AINV_SH   (\fBKEY_DMP_INTX_SH\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB253\fP 行定义\&.
.SS "#define KEY_DMP_CTHX_H   (\fBKEY_DMP_AINV_PH\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB256\fP 行定义\&.
.SS "#define KEY_DMP_CTHY_H   (\fBKEY_DMP_CTHX_H\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB257\fP 行定义\&.
.SS "#define KEY_DMP_CTHZ_H   (\fBKEY_DMP_CTHY_H\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB258\fP 行定义\&.
.SS "#define KEY_DMP_CTSQ_XH   (\fBKEY_DMP_NCTHZ_H\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB262\fP 行定义\&.
.SS "#define KEY_DMP_CTSQ_YH   (\fBKEY_DMP_CTSQ_XH\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB263\fP 行定义\&.
.SS "#define KEY_DMP_CTSQ_ZH   (\fBKEY_DMP_CTSQ_YH\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB264\fP 行定义\&.
.SS "#define KEY_DMP_FOOTER   (\fBKEY_P_EIS_FIFO_READY\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB249\fP 行定义\&.
.SS "#define KEY_DMP_INTX_H   (\fBKEY_DMP_CTSQ_ZH\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB265\fP 行定义\&.
.SS "#define KEY_DMP_INTX_HC   (\fBKEY_DMP_FOOTER\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB250\fP 行定义\&.
.SS "#define KEY_DMP_INTX_PH   (\fBKEY_DMP_INTX_HC\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB251\fP 行定义\&.
.SS "#define KEY_DMP_INTX_SH   (\fBKEY_DMP_INTX_PH\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB252\fP 行定义\&.
.SS "#define KEY_DMP_INTY_H   (\fBKEY_DMP_INTX_H\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB266\fP 行定义\&.
.SS "#define KEY_DMP_INTZ_H   (\fBKEY_DMP_INTY_H\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB267\fP 行定义\&.
.SS "#define KEY_DMP_NCTHX_H   (\fBKEY_DMP_CTHZ_H\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB259\fP 行定义\&.
.SS "#define KEY_DMP_NCTHY_H   (\fBKEY_DMP_NCTHX_H\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB260\fP 行定义\&.
.SS "#define KEY_DMP_NCTHZ_H   (\fBKEY_DMP_NCTHY_H\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB261\fP 行定义\&.
.SS "#define KEY_DMP_ORIENT   (\fBKEY_DMP_SH_TH_Z\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB190\fP 行定义\&.
.SS "#define KEY_DMP_PREVPTAT   (\fBKEY_D_0_236\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB92\fP 行定义\&.
.SS "#define KEY_DMP_SH_TH_X   (\fBKEY_DMP_SH_TH_Y\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB188\fP 行定义\&.
.SS "#define KEY_DMP_SH_TH_Y   (\fBKEY_DMP_TAP_THR_Z\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB187\fP 行定义\&.
.SS "#define KEY_DMP_SH_TH_Z   (\fBKEY_DMP_SH_TH_X\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB189\fP 行定义\&.
.SS "#define KEY_DMP_TAP_THR_X   (\fBKEY_DMP_TAPW_MIN\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB184\fP 行定义\&.
.SS "#define KEY_DMP_TAP_THR_Y   (\fBKEY_DMP_TAP_THR_X\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB185\fP 行定义\&.
.SS "#define KEY_DMP_TAP_THR_Z   (\fBKEY_DMP_TAP_THR_Y\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB186\fP 行定义\&.
.SS "#define KEY_DMP_TAPW_MIN   (\fBKEY_CPASS_MTX_22\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB183\fP 行定义\&.
.SS "#define KEY_END_COMPARE_Y_X   (\fBKEY_END_ORIENT_1\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB204\fP 行定义\&.
.SS "#define KEY_END_COMPARE_Y_X_TMP   (\fBKEY_NO_ORIENT_INTERRUPT\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB202\fP 行定义\&.
.SS "#define KEY_END_COMPARE_Y_X_TMP2   (\fBKEY_SKIP_END_COMPARE\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB199\fP 行定义\&.
.SS "#define KEY_END_COMPARE_Y_X_TMP3   (\fBKEY_NOT_TIME_MINUS_1\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB208\fP 行定义\&.
.SS "#define KEY_END_ORIENT   (\fBKEY_END_COMPARE_Y_X\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB205\fP 行定义\&.
.SS "#define KEY_END_ORIENT_1   (\fBKEY_END_COMPARE_Y_X_TMP\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB203\fP 行定义\&.
.SS "#define KEY_FCFG_1   (\fBKEY_CFG_23\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB33\fP 行定义\&.
.SS "#define KEY_FCFG_2   (\fBKEY_FCFG_3\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB35\fP 行定义\&.
.SS "#define KEY_FCFG_3   (\fBKEY_FCFG_1\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB34\fP 行定义\&.
.SS "#define KEY_FCFG_4   (\fBKEY_FCFG_5\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB40\fP 行定义\&.
.SS "#define KEY_FCFG_5   (\fBKEY_CFG_3C\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB39\fP 行定义\&.
.SS "#define KEY_FCFG_6   (\fBKEY_FCFG_AZ\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB44\fP 行定义\&.
.SS "#define KEY_FCFG_7   (\fBKEY_FCFG_4\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB41\fP 行定义\&.
.SS "#define KEY_FCFG_ACCEL_INIT   (\fBKEY_FCFG_ACCEL_INPUT\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB31\fP 行定义\&.
.SS "#define KEY_FCFG_ACCEL_INPUT   (\fBKEY_CFG_FIFO_ON_EVENT\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB30\fP 行定义\&.
.SS "#define KEY_FCFG_AZ   (\fBKEY_FCFG_FSCALE\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB43\fP 行定义\&.
.SS "#define KEY_FCFG_FSCALE   (\fBKEY_FCFG_7\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB42\fP 行定义\&.
.SS "#define KEY_FCFG_LSB4   (\fBKEY_FCFG_6\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB45\fP 行定义\&.
.SS "#define KEY_FCFG_MAG_MOV   (\fBKEY_FCFG_MAG_VAL\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB69\fP 行定义\&.
.SS "#define KEY_FCFG_MAG_VAL   (\fBKEY_CFG_ORIENT_IRQ_3\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB68\fP 行定义\&.
.SS "#define KEY_FLICK_COUNTER   (\fBKEY_FLICK_MSG\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB134\fP 行定义\&.
.SS "#define KEY_FLICK_LOWER   (\fBKEY_FLICK_COUNTER\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB135\fP 行定义\&.
.SS "#define KEY_FLICK_MSG   (\fBKEY_D_2_208\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB133\fP 行定义\&.
.SS "#define KEY_FLICK_UPPER   (\fBKEY_CFG_FLICK_IN\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB137\fP 行定义\&.
.SS "#define KEY_NO_ORIENT_INTERRUPT   (\fBKEY_CFG_ANDROID_ORIENT_INT\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB201\fP 行定义\&.
.SS "#define KEY_NOT_TIME_MINUS_1   (\fBKEY_X_GRT_Y\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB207\fP 行定义\&.
.SS "#define KEY_P_EIS_DATA_RATE   (\fBKEY_P_EIS_FIFO_YSHIFT\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB244\fP 行定义\&.
.SS "#define KEY_P_EIS_FIFO_FOOTER   (\fBKEY_D_HOST_NO_MOT\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB242\fP 行定义\&.
.SS "#define KEY_P_EIS_FIFO_READY   (\fBKEY_P_EIS_FIFO_ZSHIFT\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB248\fP 行定义\&.
.SS "#define KEY_P_EIS_FIFO_SYNC   (\fBKEY_P_EIS_FIFO_XSHIFT\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB246\fP 行定义\&.
.SS "#define KEY_P_EIS_FIFO_XSHIFT   (\fBKEY_P_EIS_DATA_RATE\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB245\fP 行定义\&.
.SS "#define KEY_P_EIS_FIFO_YSHIFT   (\fBKEY_P_EIS_FIFO_FOOTER\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB243\fP 行定义\&.
.SS "#define KEY_P_EIS_FIFO_ZSHIFT   (\fBKEY_P_EIS_FIFO_SYNC\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB247\fP 行定义\&.
.SS "#define KEY_SKIP_END_COMPARE   (\fBKEY_SKIP_X_GRT_Y_TMP\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB198\fP 行定义\&.
.SS "#define KEY_SKIP_X_GRT_Y_TMP   (\fBKEY_X_GRT_Y_TMP\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB197\fP 行定义\&.
.SS "#define KEY_STREAM_P_ACCEL_X   (\fBKEY_STREAM_P_ACCEL_Y\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB281\fP 行定义\&.
.SS "#define KEY_STREAM_P_ACCEL_Y   (\fBKEY_STREAM_P_AUX_Z\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB280\fP 行定义\&.
.SS "#define KEY_STREAM_P_ACCEL_Z   (\fBKEY_STREAM_P_FOOTER\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB283\fP 行定义\&.
.SS "#define KEY_STREAM_P_AUX_X   (\fBKEY_STREAM_P_AUX_Y\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB278\fP 行定义\&.
.SS "#define KEY_STREAM_P_AUX_Y   (\fBKEY_STREAM_P_TEMP\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB277\fP 行定义\&.
.SS "#define KEY_STREAM_P_AUX_Z   (\fBKEY_STREAM_P_AUX_X\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB279\fP 行定义\&.
.SS "#define KEY_STREAM_P_FOOTER   (\fBKEY_STREAM_P_ACCEL_X\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB282\fP 行定义\&.
.SS "#define KEY_STREAM_P_GYRO_X   (\fBKEY_STREAM_P_GYRO_Y\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB275\fP 行定义\&.
.SS "#define KEY_STREAM_P_GYRO_Y   (\fBKEY_STREAM_P_GYRO_Z\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB274\fP 行定义\&.
.SS "#define KEY_STREAM_P_GYRO_Z   (\fBKEY_DMP_INTZ_H\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB273\fP 行定义\&.
.SS "#define KEY_STREAM_P_TEMP   (\fBKEY_STREAM_P_GYRO_X\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB276\fP 行定义\&.
.SS "#define KEY_TEMPLABEL   (\fBKEY_CFG_MOTION_BIAS\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB75\fP 行定义\&.
.SS "#define KEY_X_GRT_Y   (\fBKEY_END_ORIENT\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB206\fP 行定义\&.
.SS "#define KEY_X_GRT_Y_TMP   (\fBKEY_D_ACSZ\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB196\fP 行定义\&.
.SS "#define KEY_X_GRT_Y_TMP2   (\fBKEY_END_COMPARE_Y_X_TMP3\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB209\fP 行定义\&.
.SS "#define NUM_KEYS   (\fBKEY_STREAM_P_ACCEL_Z\fP + 1)"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB285\fP 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 Bscpp 的 源代码自动生成\&.
