.TH "D:/gitt/MicrochipFor32/bsp_MPU6050/dmpmap.h" 3 "2022年 十一月 22日 星期二" "Version 1.0.0" "Bscpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/MicrochipFor32/bsp_MPU6050/dmpmap.h
.SH SYNOPSIS
.br
.PP
.SS "宏定义"

.in +1c
.ti -1c
.RI "#define \fBDMP_PTAT\fP   0"
.br
.ti -1c
.RI "#define \fBDMP_XGYR\fP   2"
.br
.ti -1c
.RI "#define \fBDMP_YGYR\fP   4"
.br
.ti -1c
.RI "#define \fBDMP_ZGYR\fP   6"
.br
.ti -1c
.RI "#define \fBDMP_XACC\fP   8"
.br
.ti -1c
.RI "#define \fBDMP_YACC\fP   10"
.br
.ti -1c
.RI "#define \fBDMP_ZACC\fP   12"
.br
.ti -1c
.RI "#define \fBDMP_ADC1\fP   14"
.br
.ti -1c
.RI "#define \fBDMP_ADC2\fP   16"
.br
.ti -1c
.RI "#define \fBDMP_ADC3\fP   18"
.br
.ti -1c
.RI "#define \fBDMP_BIASUNC\fP   20"
.br
.ti -1c
.RI "#define \fBDMP_FIFORT\fP   22"
.br
.ti -1c
.RI "#define \fBDMP_INVGSFH\fP   24"
.br
.ti -1c
.RI "#define \fBDMP_INVGSFL\fP   26"
.br
.ti -1c
.RI "#define \fBDMP_1H\fP   28"
.br
.ti -1c
.RI "#define \fBDMP_1L\fP   30"
.br
.ti -1c
.RI "#define \fBDMP_BLPFSTCH\fP   32"
.br
.ti -1c
.RI "#define \fBDMP_BLPFSTCL\fP   34"
.br
.ti -1c
.RI "#define \fBDMP_BLPFSXH\fP   36"
.br
.ti -1c
.RI "#define \fBDMP_BLPFSXL\fP   38"
.br
.ti -1c
.RI "#define \fBDMP_BLPFSYH\fP   40"
.br
.ti -1c
.RI "#define \fBDMP_BLPFSYL\fP   42"
.br
.ti -1c
.RI "#define \fBDMP_BLPFSZH\fP   44"
.br
.ti -1c
.RI "#define \fBDMP_BLPFSZL\fP   46"
.br
.ti -1c
.RI "#define \fBDMP_BLPFMTC\fP   48"
.br
.ti -1c
.RI "#define \fBDMP_SMC\fP   50"
.br
.ti -1c
.RI "#define \fBDMP_BLPFMXH\fP   52"
.br
.ti -1c
.RI "#define \fBDMP_BLPFMXL\fP   54"
.br
.ti -1c
.RI "#define \fBDMP_BLPFMYH\fP   56"
.br
.ti -1c
.RI "#define \fBDMP_BLPFMYL\fP   58"
.br
.ti -1c
.RI "#define \fBDMP_BLPFMZH\fP   60"
.br
.ti -1c
.RI "#define \fBDMP_BLPFMZL\fP   62"
.br
.ti -1c
.RI "#define \fBDMP_BLPFC\fP   64"
.br
.ti -1c
.RI "#define \fBDMP_SMCTH\fP   66"
.br
.ti -1c
.RI "#define \fBDMP_0H2\fP   68"
.br
.ti -1c
.RI "#define \fBDMP_0L2\fP   70"
.br
.ti -1c
.RI "#define \fBDMP_BERR2H\fP   72"
.br
.ti -1c
.RI "#define \fBDMP_BERR2L\fP   74"
.br
.ti -1c
.RI "#define \fBDMP_BERR2NH\fP   76"
.br
.ti -1c
.RI "#define \fBDMP_SMCINC\fP   78"
.br
.ti -1c
.RI "#define \fBDMP_ANGVBXH\fP   80"
.br
.ti -1c
.RI "#define \fBDMP_ANGVBXL\fP   82"
.br
.ti -1c
.RI "#define \fBDMP_ANGVBYH\fP   84"
.br
.ti -1c
.RI "#define \fBDMP_ANGVBYL\fP   86"
.br
.ti -1c
.RI "#define \fBDMP_ANGVBZH\fP   88"
.br
.ti -1c
.RI "#define \fBDMP_ANGVBZL\fP   90"
.br
.ti -1c
.RI "#define \fBDMP_BERR1H\fP   92"
.br
.ti -1c
.RI "#define \fBDMP_BERR1L\fP   94"
.br
.ti -1c
.RI "#define \fBDMP_ATCH\fP   96"
.br
.ti -1c
.RI "#define \fBDMP_BIASUNCSF\fP   98"
.br
.ti -1c
.RI "#define \fBDMP_ACT2H\fP   100"
.br
.ti -1c
.RI "#define \fBDMP_ACT2L\fP   102"
.br
.ti -1c
.RI "#define \fBDMP_GSFH\fP   104"
.br
.ti -1c
.RI "#define \fBDMP_GSFL\fP   106"
.br
.ti -1c
.RI "#define \fBDMP_GH\fP   108"
.br
.ti -1c
.RI "#define \fBDMP_GL\fP   110"
.br
.ti -1c
.RI "#define \fBDMP_0_5H\fP   112"
.br
.ti -1c
.RI "#define \fBDMP_0_5L\fP   114"
.br
.ti -1c
.RI "#define \fBDMP_0_0H\fP   116"
.br
.ti -1c
.RI "#define \fBDMP_0_0L\fP   118"
.br
.ti -1c
.RI "#define \fBDMP_1_0H\fP   120"
.br
.ti -1c
.RI "#define \fBDMP_1_0L\fP   122"
.br
.ti -1c
.RI "#define \fBDMP_1_5H\fP   124"
.br
.ti -1c
.RI "#define \fBDMP_1_5L\fP   126"
.br
.ti -1c
.RI "#define \fBDMP_TMP1AH\fP   128"
.br
.ti -1c
.RI "#define \fBDMP_TMP1AL\fP   130"
.br
.ti -1c
.RI "#define \fBDMP_TMP2AH\fP   132"
.br
.ti -1c
.RI "#define \fBDMP_TMP2AL\fP   134"
.br
.ti -1c
.RI "#define \fBDMP_TMP3AH\fP   136"
.br
.ti -1c
.RI "#define \fBDMP_TMP3AL\fP   138"
.br
.ti -1c
.RI "#define \fBDMP_TMP4AH\fP   140"
.br
.ti -1c
.RI "#define \fBDMP_TMP4AL\fP   142"
.br
.ti -1c
.RI "#define \fBDMP_XACCW\fP   144"
.br
.ti -1c
.RI "#define \fBDMP_TMP5\fP   146"
.br
.ti -1c
.RI "#define \fBDMP_XACCB\fP   148"
.br
.ti -1c
.RI "#define \fBDMP_TMP8\fP   150"
.br
.ti -1c
.RI "#define \fBDMP_YACCB\fP   152"
.br
.ti -1c
.RI "#define \fBDMP_TMP9\fP   154"
.br
.ti -1c
.RI "#define \fBDMP_ZACCB\fP   156"
.br
.ti -1c
.RI "#define \fBDMP_TMP10\fP   158"
.br
.ti -1c
.RI "#define \fBDMP_DZH\fP   160"
.br
.ti -1c
.RI "#define \fBDMP_DZL\fP   162"
.br
.ti -1c
.RI "#define \fBDMP_XGCH\fP   164"
.br
.ti -1c
.RI "#define \fBDMP_XGCL\fP   166"
.br
.ti -1c
.RI "#define \fBDMP_YGCH\fP   168"
.br
.ti -1c
.RI "#define \fBDMP_YGCL\fP   170"
.br
.ti -1c
.RI "#define \fBDMP_ZGCH\fP   172"
.br
.ti -1c
.RI "#define \fBDMP_ZGCL\fP   174"
.br
.ti -1c
.RI "#define \fBDMP_YACCW\fP   176"
.br
.ti -1c
.RI "#define \fBDMP_TMP7\fP   178"
.br
.ti -1c
.RI "#define \fBDMP_AFB1H\fP   180"
.br
.ti -1c
.RI "#define \fBDMP_AFB1L\fP   182"
.br
.ti -1c
.RI "#define \fBDMP_AFB2H\fP   184"
.br
.ti -1c
.RI "#define \fBDMP_AFB2L\fP   186"
.br
.ti -1c
.RI "#define \fBDMP_MAGFBH\fP   188"
.br
.ti -1c
.RI "#define \fBDMP_MAGFBL\fP   190"
.br
.ti -1c
.RI "#define \fBDMP_QT1H\fP   192"
.br
.ti -1c
.RI "#define \fBDMP_QT1L\fP   194"
.br
.ti -1c
.RI "#define \fBDMP_QT2H\fP   196"
.br
.ti -1c
.RI "#define \fBDMP_QT2L\fP   198"
.br
.ti -1c
.RI "#define \fBDMP_QT3H\fP   200"
.br
.ti -1c
.RI "#define \fBDMP_QT3L\fP   202"
.br
.ti -1c
.RI "#define \fBDMP_QT4H\fP   204"
.br
.ti -1c
.RI "#define \fBDMP_QT4L\fP   206"
.br
.ti -1c
.RI "#define \fBDMP_CTRL1H\fP   208"
.br
.ti -1c
.RI "#define \fBDMP_CTRL1L\fP   210"
.br
.ti -1c
.RI "#define \fBDMP_CTRL2H\fP   212"
.br
.ti -1c
.RI "#define \fBDMP_CTRL2L\fP   214"
.br
.ti -1c
.RI "#define \fBDMP_CTRL3H\fP   216"
.br
.ti -1c
.RI "#define \fBDMP_CTRL3L\fP   218"
.br
.ti -1c
.RI "#define \fBDMP_CTRL4H\fP   220"
.br
.ti -1c
.RI "#define \fBDMP_CTRL4L\fP   222"
.br
.ti -1c
.RI "#define \fBDMP_CTRLS1\fP   224"
.br
.ti -1c
.RI "#define \fBDMP_CTRLSF1\fP   226"
.br
.ti -1c
.RI "#define \fBDMP_CTRLS2\fP   228"
.br
.ti -1c
.RI "#define \fBDMP_CTRLSF2\fP   230"
.br
.ti -1c
.RI "#define \fBDMP_CTRLS3\fP   232"
.br
.ti -1c
.RI "#define \fBDMP_CTRLSFNLL\fP   234"
.br
.ti -1c
.RI "#define \fBDMP_CTRLS4\fP   236"
.br
.ti -1c
.RI "#define \fBDMP_CTRLSFNL2\fP   238"
.br
.ti -1c
.RI "#define \fBDMP_CTRLSFNL\fP   240"
.br
.ti -1c
.RI "#define \fBDMP_TMP30\fP   242"
.br
.ti -1c
.RI "#define \fBDMP_CTRLSFJT\fP   244"
.br
.ti -1c
.RI "#define \fBDMP_TMP31\fP   246"
.br
.ti -1c
.RI "#define \fBDMP_TMP11\fP   248"
.br
.ti -1c
.RI "#define \fBDMP_CTRLSF2_2\fP   250"
.br
.ti -1c
.RI "#define \fBDMP_TMP12\fP   252"
.br
.ti -1c
.RI "#define \fBDMP_CTRLSF1_2\fP   254"
.br
.ti -1c
.RI "#define \fBDMP_PREVPTAT\fP   256"
.br
.ti -1c
.RI "#define \fBDMP_ACCZB\fP   258"
.br
.ti -1c
.RI "#define \fBDMP_ACCXB\fP   264"
.br
.ti -1c
.RI "#define \fBDMP_ACCYB\fP   266"
.br
.ti -1c
.RI "#define \fBDMP_1HB\fP   272"
.br
.ti -1c
.RI "#define \fBDMP_1LB\fP   274"
.br
.ti -1c
.RI "#define \fBDMP_0H\fP   276"
.br
.ti -1c
.RI "#define \fBDMP_0L\fP   278"
.br
.ti -1c
.RI "#define \fBDMP_ASR22H\fP   280"
.br
.ti -1c
.RI "#define \fBDMP_ASR22L\fP   282"
.br
.ti -1c
.RI "#define \fBDMP_ASR6H\fP   284"
.br
.ti -1c
.RI "#define \fBDMP_ASR6L\fP   286"
.br
.ti -1c
.RI "#define \fBDMP_TMP13\fP   288"
.br
.ti -1c
.RI "#define \fBDMP_TMP14\fP   290"
.br
.ti -1c
.RI "#define \fBDMP_FINTXH\fP   292"
.br
.ti -1c
.RI "#define \fBDMP_FINTXL\fP   294"
.br
.ti -1c
.RI "#define \fBDMP_FINTYH\fP   296"
.br
.ti -1c
.RI "#define \fBDMP_FINTYL\fP   298"
.br
.ti -1c
.RI "#define \fBDMP_FINTZH\fP   300"
.br
.ti -1c
.RI "#define \fBDMP_FINTZL\fP   302"
.br
.ti -1c
.RI "#define \fBDMP_TMP1BH\fP   304"
.br
.ti -1c
.RI "#define \fBDMP_TMP1BL\fP   306"
.br
.ti -1c
.RI "#define \fBDMP_TMP2BH\fP   308"
.br
.ti -1c
.RI "#define \fBDMP_TMP2BL\fP   310"
.br
.ti -1c
.RI "#define \fBDMP_TMP3BH\fP   312"
.br
.ti -1c
.RI "#define \fBDMP_TMP3BL\fP   314"
.br
.ti -1c
.RI "#define \fBDMP_TMP4BH\fP   316"
.br
.ti -1c
.RI "#define \fBDMP_TMP4BL\fP   318"
.br
.ti -1c
.RI "#define \fBDMP_STXG\fP   320"
.br
.ti -1c
.RI "#define \fBDMP_ZCTXG\fP   322"
.br
.ti -1c
.RI "#define \fBDMP_STYG\fP   324"
.br
.ti -1c
.RI "#define \fBDMP_ZCTYG\fP   326"
.br
.ti -1c
.RI "#define \fBDMP_STZG\fP   328"
.br
.ti -1c
.RI "#define \fBDMP_ZCTZG\fP   330"
.br
.ti -1c
.RI "#define \fBDMP_CTRLSFJT2\fP   332"
.br
.ti -1c
.RI "#define \fBDMP_CTRLSFJTCNT\fP   334"
.br
.ti -1c
.RI "#define \fBDMP_PVXG\fP   336"
.br
.ti -1c
.RI "#define \fBDMP_TMP15\fP   338"
.br
.ti -1c
.RI "#define \fBDMP_PVYG\fP   340"
.br
.ti -1c
.RI "#define \fBDMP_TMP16\fP   342"
.br
.ti -1c
.RI "#define \fBDMP_PVZG\fP   344"
.br
.ti -1c
.RI "#define \fBDMP_TMP17\fP   346"
.br
.ti -1c
.RI "#define \fBDMP_MNMFLAGH\fP   352"
.br
.ti -1c
.RI "#define \fBDMP_MNMFLAGL\fP   354"
.br
.ti -1c
.RI "#define \fBDMP_MNMTMH\fP   356"
.br
.ti -1c
.RI "#define \fBDMP_MNMTML\fP   358"
.br
.ti -1c
.RI "#define \fBDMP_MNMTMTHRH\fP   360"
.br
.ti -1c
.RI "#define \fBDMP_MNMTMTHRL\fP   362"
.br
.ti -1c
.RI "#define \fBDMP_MNMTHRH\fP   364"
.br
.ti -1c
.RI "#define \fBDMP_MNMTHRL\fP   366"
.br
.ti -1c
.RI "#define \fBDMP_ACCQD4H\fP   368"
.br
.ti -1c
.RI "#define \fBDMP_ACCQD4L\fP   370"
.br
.ti -1c
.RI "#define \fBDMP_ACCQD5H\fP   372"
.br
.ti -1c
.RI "#define \fBDMP_ACCQD5L\fP   374"
.br
.ti -1c
.RI "#define \fBDMP_ACCQD6H\fP   376"
.br
.ti -1c
.RI "#define \fBDMP_ACCQD6L\fP   378"
.br
.ti -1c
.RI "#define \fBDMP_ACCQD7H\fP   380"
.br
.ti -1c
.RI "#define \fBDMP_ACCQD7L\fP   382"
.br
.ti -1c
.RI "#define \fBDMP_ACCQD0H\fP   384"
.br
.ti -1c
.RI "#define \fBDMP_ACCQD0L\fP   386"
.br
.ti -1c
.RI "#define \fBDMP_ACCQD1H\fP   388"
.br
.ti -1c
.RI "#define \fBDMP_ACCQD1L\fP   390"
.br
.ti -1c
.RI "#define \fBDMP_ACCQD2H\fP   392"
.br
.ti -1c
.RI "#define \fBDMP_ACCQD2L\fP   394"
.br
.ti -1c
.RI "#define \fBDMP_ACCQD3H\fP   396"
.br
.ti -1c
.RI "#define \fBDMP_ACCQD3L\fP   398"
.br
.ti -1c
.RI "#define \fBDMP_XN2H\fP   400"
.br
.ti -1c
.RI "#define \fBDMP_XN2L\fP   402"
.br
.ti -1c
.RI "#define \fBDMP_XN1H\fP   404"
.br
.ti -1c
.RI "#define \fBDMP_XN1L\fP   406"
.br
.ti -1c
.RI "#define \fBDMP_YN2H\fP   408"
.br
.ti -1c
.RI "#define \fBDMP_YN2L\fP   410"
.br
.ti -1c
.RI "#define \fBDMP_YN1H\fP   412"
.br
.ti -1c
.RI "#define \fBDMP_YN1L\fP   414"
.br
.ti -1c
.RI "#define \fBDMP_YH\fP   416"
.br
.ti -1c
.RI "#define \fBDMP_YL\fP   418"
.br
.ti -1c
.RI "#define \fBDMP_B0H\fP   420"
.br
.ti -1c
.RI "#define \fBDMP_B0L\fP   422"
.br
.ti -1c
.RI "#define \fBDMP_A1H\fP   424"
.br
.ti -1c
.RI "#define \fBDMP_A1L\fP   426"
.br
.ti -1c
.RI "#define \fBDMP_A2H\fP   428"
.br
.ti -1c
.RI "#define \fBDMP_A2L\fP   430"
.br
.ti -1c
.RI "#define \fBDMP_SEM1\fP   432"
.br
.ti -1c
.RI "#define \fBDMP_FIFOCNT\fP   434"
.br
.ti -1c
.RI "#define \fBDMP_SH_TH_X\fP   436"
.br
.ti -1c
.RI "#define \fBDMP_PACKET\fP   438"
.br
.ti -1c
.RI "#define \fBDMP_SH_TH_Y\fP   440"
.br
.ti -1c
.RI "#define \fBDMP_FOOTER\fP   442"
.br
.ti -1c
.RI "#define \fBDMP_SH_TH_Z\fP   444"
.br
.ti -1c
.RI "#define \fBDMP_TEMP29\fP   448"
.br
.ti -1c
.RI "#define \fBDMP_TEMP30\fP   450"
.br
.ti -1c
.RI "#define \fBDMP_XACCB_PRE\fP   452"
.br
.ti -1c
.RI "#define \fBDMP_XACCB_PREL\fP   454"
.br
.ti -1c
.RI "#define \fBDMP_YACCB_PRE\fP   456"
.br
.ti -1c
.RI "#define \fBDMP_YACCB_PREL\fP   458"
.br
.ti -1c
.RI "#define \fBDMP_ZACCB_PRE\fP   460"
.br
.ti -1c
.RI "#define \fBDMP_ZACCB_PREL\fP   462"
.br
.ti -1c
.RI "#define \fBDMP_TMP22\fP   464"
.br
.ti -1c
.RI "#define \fBDMP_TAP_TIMER\fP   466"
.br
.ti -1c
.RI "#define \fBDMP_TAP_THX\fP   468"
.br
.ti -1c
.RI "#define \fBDMP_TAP_THY\fP   472"
.br
.ti -1c
.RI "#define \fBDMP_TAP_THZ\fP   476"
.br
.ti -1c
.RI "#define \fBDMP_TAPW_MIN\fP   478"
.br
.ti -1c
.RI "#define \fBDMP_TMP25\fP   480"
.br
.ti -1c
.RI "#define \fBDMP_TMP26\fP   482"
.br
.ti -1c
.RI "#define \fBDMP_TMP27\fP   484"
.br
.ti -1c
.RI "#define \fBDMP_TMP28\fP   486"
.br
.ti -1c
.RI "#define \fBDMP_ORIENT\fP   488"
.br
.ti -1c
.RI "#define \fBDMP_THRSH\fP   490"
.br
.ti -1c
.RI "#define \fBDMP_ENDIANH\fP   492"
.br
.ti -1c
.RI "#define \fBDMP_ENDIANL\fP   494"
.br
.ti -1c
.RI "#define \fBDMP_BLPFNMTCH\fP   496"
.br
.ti -1c
.RI "#define \fBDMP_BLPFNMTCL\fP   498"
.br
.ti -1c
.RI "#define \fBDMP_BLPFNMXH\fP   500"
.br
.ti -1c
.RI "#define \fBDMP_BLPFNMXL\fP   502"
.br
.ti -1c
.RI "#define \fBDMP_BLPFNMYH\fP   504"
.br
.ti -1c
.RI "#define \fBDMP_BLPFNMYL\fP   506"
.br
.ti -1c
.RI "#define \fBDMP_BLPFNMZH\fP   508"
.br
.ti -1c
.RI "#define \fBDMP_BLPFNMZL\fP   510"
.br
.in -1c
.SH "宏定义说明"
.PP 
.SS "#define DMP_0_0H   116"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB72\fP 行定义\&.
.SS "#define DMP_0_0L   118"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB73\fP 行定义\&.
.SS "#define DMP_0_5H   112"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB70\fP 行定义\&.
.SS "#define DMP_0_5L   114"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB71\fP 行定义\&.
.SS "#define DMP_0H   276"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB148\fP 行定义\&.
.SS "#define DMP_0H2   68"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB48\fP 行定义\&.
.SS "#define DMP_0L   278"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB149\fP 行定义\&.
.SS "#define DMP_0L2   70"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB49\fP 行定义\&.
.SS "#define DMP_1_0H   120"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB74\fP 行定义\&.
.SS "#define DMP_1_0L   122"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB75\fP 行定义\&.
.SS "#define DMP_1_5H   124"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB76\fP 行定义\&.
.SS "#define DMP_1_5L   126"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB77\fP 行定义\&.
.SS "#define DMP_1H   28"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB28\fP 行定义\&.
.SS "#define DMP_1HB   272"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB146\fP 行定义\&.
.SS "#define DMP_1L   30"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB29\fP 行定义\&.
.SS "#define DMP_1LB   274"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB147\fP 行定义\&.
.SS "#define DMP_A1H   424"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB220\fP 行定义\&.
.SS "#define DMP_A1L   426"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB221\fP 行定义\&.
.SS "#define DMP_A2H   428"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB222\fP 行定义\&.
.SS "#define DMP_A2L   430"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB223\fP 行定义\&.
.SS "#define DMP_ACCQD0H   384"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB200\fP 行定义\&.
.SS "#define DMP_ACCQD0L   386"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB201\fP 行定义\&.
.SS "#define DMP_ACCQD1H   388"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB202\fP 行定义\&.
.SS "#define DMP_ACCQD1L   390"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB203\fP 行定义\&.
.SS "#define DMP_ACCQD2H   392"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB204\fP 行定义\&.
.SS "#define DMP_ACCQD2L   394"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB205\fP 行定义\&.
.SS "#define DMP_ACCQD3H   396"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB206\fP 行定义\&.
.SS "#define DMP_ACCQD3L   398"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB207\fP 行定义\&.
.SS "#define DMP_ACCQD4H   368"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB192\fP 行定义\&.
.SS "#define DMP_ACCQD4L   370"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB193\fP 行定义\&.
.SS "#define DMP_ACCQD5H   372"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB194\fP 行定义\&.
.SS "#define DMP_ACCQD5L   374"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB195\fP 行定义\&.
.SS "#define DMP_ACCQD6H   376"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB196\fP 行定义\&.
.SS "#define DMP_ACCQD6L   378"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB197\fP 行定义\&.
.SS "#define DMP_ACCQD7H   380"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB198\fP 行定义\&.
.SS "#define DMP_ACCQD7L   382"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB199\fP 行定义\&.
.SS "#define DMP_ACCXB   264"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB144\fP 行定义\&.
.SS "#define DMP_ACCYB   266"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB145\fP 行定义\&.
.SS "#define DMP_ACCZB   258"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB143\fP 行定义\&.
.SS "#define DMP_ACT2H   100"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB64\fP 行定义\&.
.SS "#define DMP_ACT2L   102"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB65\fP 行定义\&.
.SS "#define DMP_ADC1   14"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB21\fP 行定义\&.
.SS "#define DMP_ADC2   16"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB22\fP 行定义\&.
.SS "#define DMP_ADC3   18"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB23\fP 行定义\&.
.SS "#define DMP_AFB1H   180"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB104\fP 行定义\&.
.SS "#define DMP_AFB1L   182"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB105\fP 行定义\&.
.SS "#define DMP_AFB2H   184"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB106\fP 行定义\&.
.SS "#define DMP_AFB2L   186"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB107\fP 行定义\&.
.SS "#define DMP_ANGVBXH   80"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB54\fP 行定义\&.
.SS "#define DMP_ANGVBXL   82"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB55\fP 行定义\&.
.SS "#define DMP_ANGVBYH   84"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB56\fP 行定义\&.
.SS "#define DMP_ANGVBYL   86"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB57\fP 行定义\&.
.SS "#define DMP_ANGVBZH   88"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB58\fP 行定义\&.
.SS "#define DMP_ANGVBZL   90"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB59\fP 行定义\&.
.SS "#define DMP_ASR22H   280"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB150\fP 行定义\&.
.SS "#define DMP_ASR22L   282"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB151\fP 行定义\&.
.SS "#define DMP_ASR6H   284"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB152\fP 行定义\&.
.SS "#define DMP_ASR6L   286"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB153\fP 行定义\&.
.SS "#define DMP_ATCH   96"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB62\fP 行定义\&.
.SS "#define DMP_B0H   420"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB218\fP 行定义\&.
.SS "#define DMP_B0L   422"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB219\fP 行定义\&.
.SS "#define DMP_BERR1H   92"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB60\fP 行定义\&.
.SS "#define DMP_BERR1L   94"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB61\fP 行定义\&.
.SS "#define DMP_BERR2H   72"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB50\fP 行定义\&.
.SS "#define DMP_BERR2L   74"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB51\fP 行定义\&.
.SS "#define DMP_BERR2NH   76"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB52\fP 行定义\&.
.SS "#define DMP_BIASUNC   20"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB24\fP 行定义\&.
.SS "#define DMP_BIASUNCSF   98"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB63\fP 行定义\&.
.SS "#define DMP_BLPFC   64"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB46\fP 行定义\&.
.SS "#define DMP_BLPFMTC   48"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB38\fP 行定义\&.
.SS "#define DMP_BLPFMXH   52"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB40\fP 行定义\&.
.SS "#define DMP_BLPFMXL   54"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB41\fP 行定义\&.
.SS "#define DMP_BLPFMYH   56"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB42\fP 行定义\&.
.SS "#define DMP_BLPFMYL   58"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB43\fP 行定义\&.
.SS "#define DMP_BLPFMZH   60"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB44\fP 行定义\&.
.SS "#define DMP_BLPFMZL   62"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB45\fP 行定义\&.
.SS "#define DMP_BLPFNMTCH   496"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB253\fP 行定义\&.
.SS "#define DMP_BLPFNMTCL   498"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB254\fP 行定义\&.
.SS "#define DMP_BLPFNMXH   500"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB255\fP 行定义\&.
.SS "#define DMP_BLPFNMXL   502"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB256\fP 行定义\&.
.SS "#define DMP_BLPFNMYH   504"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB257\fP 行定义\&.
.SS "#define DMP_BLPFNMYL   506"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB258\fP 行定义\&.
.SS "#define DMP_BLPFNMZH   508"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB259\fP 行定义\&.
.SS "#define DMP_BLPFNMZL   510"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB260\fP 行定义\&.
.SS "#define DMP_BLPFSTCH   32"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB30\fP 行定义\&.
.SS "#define DMP_BLPFSTCL   34"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB31\fP 行定义\&.
.SS "#define DMP_BLPFSXH   36"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB32\fP 行定义\&.
.SS "#define DMP_BLPFSXL   38"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB33\fP 行定义\&.
.SS "#define DMP_BLPFSYH   40"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB34\fP 行定义\&.
.SS "#define DMP_BLPFSYL   42"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB35\fP 行定义\&.
.SS "#define DMP_BLPFSZH   44"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB36\fP 行定义\&.
.SS "#define DMP_BLPFSZL   46"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB37\fP 行定义\&.
.SS "#define DMP_CTRL1H   208"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB118\fP 行定义\&.
.SS "#define DMP_CTRL1L   210"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB119\fP 行定义\&.
.SS "#define DMP_CTRL2H   212"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB120\fP 行定义\&.
.SS "#define DMP_CTRL2L   214"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB121\fP 行定义\&.
.SS "#define DMP_CTRL3H   216"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB122\fP 行定义\&.
.SS "#define DMP_CTRL3L   218"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB123\fP 行定义\&.
.SS "#define DMP_CTRL4H   220"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB124\fP 行定义\&.
.SS "#define DMP_CTRL4L   222"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB125\fP 行定义\&.
.SS "#define DMP_CTRLS1   224"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB126\fP 行定义\&.
.SS "#define DMP_CTRLS2   228"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB128\fP 行定义\&.
.SS "#define DMP_CTRLS3   232"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB130\fP 行定义\&.
.SS "#define DMP_CTRLS4   236"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB132\fP 行定义\&.
.SS "#define DMP_CTRLSF1   226"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB127\fP 行定义\&.
.SS "#define DMP_CTRLSF1_2   254"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB141\fP 行定义\&.
.SS "#define DMP_CTRLSF2   230"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB129\fP 行定义\&.
.SS "#define DMP_CTRLSF2_2   250"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB139\fP 行定义\&.
.SS "#define DMP_CTRLSFJT   244"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB136\fP 行定义\&.
.SS "#define DMP_CTRLSFJT2   332"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB176\fP 行定义\&.
.SS "#define DMP_CTRLSFJTCNT   334"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB177\fP 行定义\&.
.SS "#define DMP_CTRLSFNL   240"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB134\fP 行定义\&.
.SS "#define DMP_CTRLSFNL2   238"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB133\fP 行定义\&.
.SS "#define DMP_CTRLSFNLL   234"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB131\fP 行定义\&.
.SS "#define DMP_DZH   160"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB94\fP 行定义\&.
.SS "#define DMP_DZL   162"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB95\fP 行定义\&.
.SS "#define DMP_ENDIANH   492"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB251\fP 行定义\&.
.SS "#define DMP_ENDIANL   494"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB252\fP 行定义\&.
.SS "#define DMP_FIFOCNT   434"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB225\fP 行定义\&.
.SS "#define DMP_FIFORT   22"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB25\fP 行定义\&.
.SS "#define DMP_FINTXH   292"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB156\fP 行定义\&.
.SS "#define DMP_FINTXL   294"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB157\fP 行定义\&.
.SS "#define DMP_FINTYH   296"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB158\fP 行定义\&.
.SS "#define DMP_FINTYL   298"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB159\fP 行定义\&.
.SS "#define DMP_FINTZH   300"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB160\fP 行定义\&.
.SS "#define DMP_FINTZL   302"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB161\fP 行定义\&.
.SS "#define DMP_FOOTER   442"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB229\fP 行定义\&.
.SS "#define DMP_GH   108"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB68\fP 行定义\&.
.SS "#define DMP_GL   110"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB69\fP 行定义\&.
.SS "#define DMP_GSFH   104"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB66\fP 行定义\&.
.SS "#define DMP_GSFL   106"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB67\fP 行定义\&.
.SS "#define DMP_INVGSFH   24"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB26\fP 行定义\&.
.SS "#define DMP_INVGSFL   26"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB27\fP 行定义\&.
.SS "#define DMP_MAGFBH   188"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB108\fP 行定义\&.
.SS "#define DMP_MAGFBL   190"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB109\fP 行定义\&.
.SS "#define DMP_MNMFLAGH   352"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB184\fP 行定义\&.
.SS "#define DMP_MNMFLAGL   354"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB185\fP 行定义\&.
.SS "#define DMP_MNMTHRH   364"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB190\fP 行定义\&.
.SS "#define DMP_MNMTHRL   366"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB191\fP 行定义\&.
.SS "#define DMP_MNMTMH   356"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB186\fP 行定义\&.
.SS "#define DMP_MNMTML   358"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB187\fP 行定义\&.
.SS "#define DMP_MNMTMTHRH   360"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB188\fP 行定义\&.
.SS "#define DMP_MNMTMTHRL   362"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB189\fP 行定义\&.
.SS "#define DMP_ORIENT   488"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB249\fP 行定义\&.
.SS "#define DMP_PACKET   438"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB227\fP 行定义\&.
.SS "#define DMP_PREVPTAT   256"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB142\fP 行定义\&.
.SS "#define DMP_PTAT   0"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB14\fP 行定义\&.
.SS "#define DMP_PVXG   336"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB178\fP 行定义\&.
.SS "#define DMP_PVYG   340"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB180\fP 行定义\&.
.SS "#define DMP_PVZG   344"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB182\fP 行定义\&.
.SS "#define DMP_QT1H   192"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB110\fP 行定义\&.
.SS "#define DMP_QT1L   194"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB111\fP 行定义\&.
.SS "#define DMP_QT2H   196"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB112\fP 行定义\&.
.SS "#define DMP_QT2L   198"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB113\fP 行定义\&.
.SS "#define DMP_QT3H   200"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB114\fP 行定义\&.
.SS "#define DMP_QT3L   202"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB115\fP 行定义\&.
.SS "#define DMP_QT4H   204"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB116\fP 行定义\&.
.SS "#define DMP_QT4L   206"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB117\fP 行定义\&.
.SS "#define DMP_SEM1   432"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB224\fP 行定义\&.
.SS "#define DMP_SH_TH_X   436"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB226\fP 行定义\&.
.SS "#define DMP_SH_TH_Y   440"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB228\fP 行定义\&.
.SS "#define DMP_SH_TH_Z   444"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB230\fP 行定义\&.
.SS "#define DMP_SMC   50"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB39\fP 行定义\&.
.SS "#define DMP_SMCINC   78"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB53\fP 行定义\&.
.SS "#define DMP_SMCTH   66"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB47\fP 行定义\&.
.SS "#define DMP_STXG   320"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB170\fP 行定义\&.
.SS "#define DMP_STYG   324"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB172\fP 行定义\&.
.SS "#define DMP_STZG   328"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB174\fP 行定义\&.
.SS "#define DMP_TAP_THX   468"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB241\fP 行定义\&.
.SS "#define DMP_TAP_THY   472"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB242\fP 行定义\&.
.SS "#define DMP_TAP_THZ   476"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB243\fP 行定义\&.
.SS "#define DMP_TAP_TIMER   466"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB240\fP 行定义\&.
.SS "#define DMP_TAPW_MIN   478"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB244\fP 行定义\&.
.SS "#define DMP_TEMP29   448"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB231\fP 行定义\&.
.SS "#define DMP_TEMP30   450"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB232\fP 行定义\&.
.SS "#define DMP_THRSH   490"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB250\fP 行定义\&.
.SS "#define DMP_TMP10   158"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB93\fP 行定义\&.
.SS "#define DMP_TMP11   248"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB138\fP 行定义\&.
.SS "#define DMP_TMP12   252"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB140\fP 行定义\&.
.SS "#define DMP_TMP13   288"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB154\fP 行定义\&.
.SS "#define DMP_TMP14   290"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB155\fP 行定义\&.
.SS "#define DMP_TMP15   338"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB179\fP 行定义\&.
.SS "#define DMP_TMP16   342"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB181\fP 行定义\&.
.SS "#define DMP_TMP17   346"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB183\fP 行定义\&.
.SS "#define DMP_TMP1AH   128"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB78\fP 行定义\&.
.SS "#define DMP_TMP1AL   130"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB79\fP 行定义\&.
.SS "#define DMP_TMP1BH   304"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB162\fP 行定义\&.
.SS "#define DMP_TMP1BL   306"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB163\fP 行定义\&.
.SS "#define DMP_TMP22   464"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB239\fP 行定义\&.
.SS "#define DMP_TMP25   480"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB245\fP 行定义\&.
.SS "#define DMP_TMP26   482"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB246\fP 行定义\&.
.SS "#define DMP_TMP27   484"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB247\fP 行定义\&.
.SS "#define DMP_TMP28   486"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB248\fP 行定义\&.
.SS "#define DMP_TMP2AH   132"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB80\fP 行定义\&.
.SS "#define DMP_TMP2AL   134"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB81\fP 行定义\&.
.SS "#define DMP_TMP2BH   308"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB164\fP 行定义\&.
.SS "#define DMP_TMP2BL   310"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB165\fP 行定义\&.
.SS "#define DMP_TMP30   242"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB135\fP 行定义\&.
.SS "#define DMP_TMP31   246"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB137\fP 行定义\&.
.SS "#define DMP_TMP3AH   136"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB82\fP 行定义\&.
.SS "#define DMP_TMP3AL   138"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB83\fP 行定义\&.
.SS "#define DMP_TMP3BH   312"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB166\fP 行定义\&.
.SS "#define DMP_TMP3BL   314"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB167\fP 行定义\&.
.SS "#define DMP_TMP4AH   140"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB84\fP 行定义\&.
.SS "#define DMP_TMP4AL   142"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB85\fP 行定义\&.
.SS "#define DMP_TMP4BH   316"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB168\fP 行定义\&.
.SS "#define DMP_TMP4BL   318"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB169\fP 行定义\&.
.SS "#define DMP_TMP5   146"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB87\fP 行定义\&.
.SS "#define DMP_TMP7   178"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB103\fP 行定义\&.
.SS "#define DMP_TMP8   150"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB89\fP 行定义\&.
.SS "#define DMP_TMP9   154"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB91\fP 行定义\&.
.SS "#define DMP_XACC   8"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB18\fP 行定义\&.
.SS "#define DMP_XACCB   148"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB88\fP 行定义\&.
.SS "#define DMP_XACCB_PRE   452"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB233\fP 行定义\&.
.SS "#define DMP_XACCB_PREL   454"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB234\fP 行定义\&.
.SS "#define DMP_XACCW   144"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB86\fP 行定义\&.
.SS "#define DMP_XGCH   164"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB96\fP 行定义\&.
.SS "#define DMP_XGCL   166"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB97\fP 行定义\&.
.SS "#define DMP_XGYR   2"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB15\fP 行定义\&.
.SS "#define DMP_XN1H   404"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB210\fP 行定义\&.
.SS "#define DMP_XN1L   406"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB211\fP 行定义\&.
.SS "#define DMP_XN2H   400"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB208\fP 行定义\&.
.SS "#define DMP_XN2L   402"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB209\fP 行定义\&.
.SS "#define DMP_YACC   10"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB19\fP 行定义\&.
.SS "#define DMP_YACCB   152"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB90\fP 行定义\&.
.SS "#define DMP_YACCB_PRE   456"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB235\fP 行定义\&.
.SS "#define DMP_YACCB_PREL   458"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB236\fP 行定义\&.
.SS "#define DMP_YACCW   176"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB102\fP 行定义\&.
.SS "#define DMP_YGCH   168"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB98\fP 行定义\&.
.SS "#define DMP_YGCL   170"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB99\fP 行定义\&.
.SS "#define DMP_YGYR   4"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB16\fP 行定义\&.
.SS "#define DMP_YH   416"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB216\fP 行定义\&.
.SS "#define DMP_YL   418"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB217\fP 行定义\&.
.SS "#define DMP_YN1H   412"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB214\fP 行定义\&.
.SS "#define DMP_YN1L   414"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB215\fP 行定义\&.
.SS "#define DMP_YN2H   408"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB212\fP 行定义\&.
.SS "#define DMP_YN2L   410"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB213\fP 行定义\&.
.SS "#define DMP_ZACC   12"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB20\fP 行定义\&.
.SS "#define DMP_ZACCB   156"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB92\fP 行定义\&.
.SS "#define DMP_ZACCB_PRE   460"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB237\fP 行定义\&.
.SS "#define DMP_ZACCB_PREL   462"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB238\fP 行定义\&.
.SS "#define DMP_ZCTXG   322"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB171\fP 行定义\&.
.SS "#define DMP_ZCTYG   326"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB173\fP 行定义\&.
.SS "#define DMP_ZCTZG   330"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB175\fP 行定义\&.
.SS "#define DMP_ZGCH   172"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB100\fP 行定义\&.
.SS "#define DMP_ZGCL   174"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB101\fP 行定义\&.
.SS "#define DMP_ZGYR   6"

.PP
在文件 \fBdmpmap\&.h\fP 第 \fB17\fP 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 Bscpp 的 源代码自动生成\&.
