.TH "int_param_s" 3 "2022年 十一月 22日 星期二" "Version 1.0.0" "Bscpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
int_param_s
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <inv_mpu\&.h>\fP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "void(* \fBcb\fP )(void)"
.br
.ti -1c
.RI "unsigned short \fBpin\fP"
.br
.ti -1c
.RI "unsigned char \fBlp_exit\fP"
.br
.ti -1c
.RI "unsigned char \fBactive_low\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 \fBinv_mpu\&.h\fP 第 \fB37\fP 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Bscpp 的 源代码自动生成\&.
