.TH "motion_int_cache_s" 3 "2022年 十一月 22日 星期二" "Version 1.0.0" "Bscpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
motion_int_cache_s
.SH SYNOPSIS
.br
.PP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "unsigned short \fBgyro_fsr\fP"
.br
.ti -1c
.RI "unsigned char \fBaccel_fsr\fP"
.br
.ti -1c
.RI "unsigned short \fBlpf\fP"
.br
.ti -1c
.RI "unsigned short \fBsample_rate\fP"
.br
.ti -1c
.RI "unsigned char \fBsensors_on\fP"
.br
.ti -1c
.RI "unsigned char \fBfifo_sensors\fP"
.br
.ti -1c
.RI "unsigned char \fBdmp_on\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 \fBinv_mpu\&.c\fP 第 \fB221\fP 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Bscpp 的 源代码自动生成\&.
