.TH "MSD_CID" 3 "2022年 十一月 22日 星期二" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSD_CID
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bsp_SD\&.h>\fP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "\fBu8\fP \fBManufacturerID\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBOEM_AppliID\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBProdName1\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBProdName2\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBProdRev\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBProdSN\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBReserved1\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBManufactDate\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBCID_CRC\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBReserved2\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 \fBbsp_SD\&.h\fP 第 \fB136\fP 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "\fBu8\fP MSD_CID::CID_CRC"

.PP
在文件 \fBbsp_SD\&.h\fP 第 \fB145\fP 行定义\&.
.SS "\fBu16\fP MSD_CID::ManufactDate"

.PP
在文件 \fBbsp_SD\&.h\fP 第 \fB144\fP 行定义\&.
.SS "\fBu8\fP MSD_CID::ManufacturerID"

.PP
在文件 \fBbsp_SD\&.h\fP 第 \fB137\fP 行定义\&.
.SS "\fBu16\fP MSD_CID::OEM_AppliID"

.PP
在文件 \fBbsp_SD\&.h\fP 第 \fB138\fP 行定义\&.
.SS "\fBu32\fP MSD_CID::ProdName1"

.PP
在文件 \fBbsp_SD\&.h\fP 第 \fB139\fP 行定义\&.
.SS "\fBu8\fP MSD_CID::ProdName2"

.PP
在文件 \fBbsp_SD\&.h\fP 第 \fB140\fP 行定义\&.
.SS "\fBu8\fP MSD_CID::ProdRev"

.PP
在文件 \fBbsp_SD\&.h\fP 第 \fB141\fP 行定义\&.
.SS "\fBu32\fP MSD_CID::ProdSN"

.PP
在文件 \fBbsp_SD\&.h\fP 第 \fB142\fP 行定义\&.
.SS "\fBu8\fP MSD_CID::Reserved1"

.PP
在文件 \fBbsp_SD\&.h\fP 第 \fB143\fP 行定义\&.
.SS "\fBu8\fP MSD_CID::Reserved2"

.PP
在文件 \fBbsp_SD\&.h\fP 第 \fB146\fP 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
