.TH "MSD_CARDINFO" 3 "2022年 十一月 27日 星期日" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MSD_CARDINFO
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bsp_SD\&.h>\fP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "\fBMSD_CSD\fP \fBCSD\fP"
.br
.ti -1c
.RI "\fBMSD_CID\fP \fBCID\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBCapacity\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBBlockSize\fP"
.br
.ti -1c
.RI "\fBu16\fP \fBRCA\fP"
.br
.ti -1c
.RI "\fBu8\fP \fBCardType\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBSpaceTotal\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBSpaceFree\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 \fBbsp_SD\&.h\fP 第 \fB149\fP 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "\fBu32\fP MSD_CARDINFO::BlockSize"

.PP
在文件 \fBbsp_SD\&.h\fP 第 \fB153\fP 行定义\&.
.SS "\fBu32\fP MSD_CARDINFO::Capacity"

.PP
在文件 \fBbsp_SD\&.h\fP 第 \fB152\fP 行定义\&.
.SS "\fBu8\fP MSD_CARDINFO::CardType"

.PP
在文件 \fBbsp_SD\&.h\fP 第 \fB155\fP 行定义\&.
.SS "\fBMSD_CID\fP MSD_CARDINFO::CID"

.PP
在文件 \fBbsp_SD\&.h\fP 第 \fB151\fP 行定义\&.
.SS "\fBMSD_CSD\fP MSD_CARDINFO::CSD"

.PP
在文件 \fBbsp_SD\&.h\fP 第 \fB150\fP 行定义\&.
.SS "\fBu16\fP MSD_CARDINFO::RCA"

.PP
在文件 \fBbsp_SD\&.h\fP 第 \fB154\fP 行定义\&.
.SS "\fBu32\fP MSD_CARDINFO::SpaceFree"

.PP
在文件 \fBbsp_SD\&.h\fP 第 \fB157\fP 行定义\&.
.SS "\fBu32\fP MSD_CARDINFO::SpaceTotal"

.PP
在文件 \fBbsp_SD\&.h\fP 第 \fB156\fP 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
