.TH "struct_bsp_Flash_Pack" 3 "2022年 十一月 24日 星期四" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
struct_bsp_Flash_Pack \- 一包数据的内容  

.SH SYNOPSIS
.br
.PP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "char \fBVar0\fP"
.br
.ti -1c
.RI "short \fBVar1\fP"
.br
.ti -1c
.RI "int \fBVar2\fP"
.br
.in -1c
.SH "详细描述"
.PP 
一包数据的内容 


.PP
\fB待办事项\fP
.RS 4
随意更改内部内容方便读取 
.RE
.PP

.PP
在文件 \fBbsp_flash\&.c\fP 第 \fB43\fP 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "char struct_bsp_Flash_Pack::Var0"

.PP
在文件 \fBbsp_flash\&.c\fP 第 \fB44\fP 行定义\&.
.SS "short struct_bsp_Flash_Pack::Var1"

.PP
在文件 \fBbsp_flash\&.c\fP 第 \fB45\fP 行定义\&.
.SS "int struct_bsp_Flash_Pack::Var2"

.PP
在文件 \fBbsp_flash\&.c\fP 第 \fB46\fP 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
