.TH "tKeyLabel" 3 "2022年 十一月 22日 星期二" "Version 1.0.0" "Bscpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tKeyLabel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dmpKey\&.h>\fP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "unsigned short \fBkey\fP"
.br
.ti -1c
.RI "unsigned short \fBaddr\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 \fBdmpKey\&.h\fP 第 \fB287\fP 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "unsigned short tKeyLabel::addr"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB289\fP 行定义\&.
.SS "unsigned short tKeyLabel::key"

.PP
在文件 \fBdmpKey\&.h\fP 第 \fB288\fP 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Bscpp 的 源代码自动生成\&.
