.TH "todo" 3 "2022年 十一月 22日 星期二" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- 待办事项列表 
.PP

.IP "\fB成员 \fBbsp_IIC::IIC_Delay\fP (void)=0\fP" 1c
需要为其实现才可使用软件IIC  
.IP "\fB成员 \fBbsp_IIC::IIC_SCK\fP (u8 var)=0\fP" 1c
需要为其实现才可使用软件IIC  
.IP "\fB成员 \fBbsp_IIC::IIC_SDA\fP (u8 var)=0\fP" 1c
需要为其实现才可使用软件IIC  
.IP "\fB成员 \fBMainInit\fP (void)\fP" 1c
在此处填写初始化程序  
.IP "\fB成员 \fBMainSystem\fP (void)\fP" 1c
在此处填写主进程程序 
.PP

