.TH "D:/gitt/MicrochipFor32/bsp_System/vartable.h" 3 "2022年 十一月 25日 星期五" "Version 2.0.0" "MF32BSP_XerolySkinner" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/gitt/MicrochipFor32/bsp_System/vartable.h \- 全局向量在此生成  

.SH SYNOPSIS
.br
.PP
\fC#include 'User\&.h'\fP
.br
\fC#include 'varint\&.h'\fP
.br
\fC#include 'stdio\&.h'\fP
.br
\fC#include 'CallBack\&.h'\fP
.br
\fC#include 'main\&.h'\fP
.br
\fC#include 'gpio\&.h'\fP
.br

.SS "函数"

.in +1c
.ti -1c
.RI "void \fBMainInit\fP (void)"
.br
.RI "初始化步骤的首部 "
.ti -1c
.RI "void \fBMainSystem\fP (void)"
.br
.RI "循环主程序函数 "
.in -1c
.SH "详细描述"
.PP 
全局向量在此生成 


.PP
在文件 \fBvartable\&.h\fP 中定义\&.
.SH "函数说明"
.PP 
.SS "void MainInit (void)"

.PP
初始化步骤的首部 
.PP
\fB注解\fP
.RS 4
在MX生成的main中,进入循环前放置本函数 
.RE
.PP

.PP
\fB待办事项\fP
.RS 4
在此处填写初始化程序 
.RE
.PP

.PP
在文件 \fBMainSystem\&.cpp\fP 第 \fB47\fP 行定义\&.
.SS "void MainSystem (void)"

.PP
循环主程序函数 
.PP
\fB注解\fP
.RS 4
在MX生成的main中,进入循环后放置本函数 
.RE
.PP

.PP
\fB待办事项\fP
.RS 4
在此处填写主进程程序 
.RE
.PP

.PP
在文件 \fBMainSystem\&.cpp\fP 第 \fB56\fP 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 MF32BSP_XerolySkinner 的 源代码自动生成\&.
