bsp_CRC.cpp
const u8 aucCRCHi[][]
CRC-16-MODBUS-查表法-高字节数据表
Referenced by CRC16_MODBUS.
const u8 aucCRCLo[][]
CRC-16-MODBUS-查表法-低字节数据表
Referenced by CRC16_MODBUS.
u16 CRC16_MODBUS(u8 *pucFrame, u16 usLen)
References aucCRCHi, aucCRCLo.
Referenced by bsp_ModBus_Rx::analysis, bsp_ModBus_Tx::ReadInCoil, bsp_ModBus_Tx::ReadInReg, bsp_ModBus_Tx::ReadKeepReg, bsp_ModBus_Tx::ReadOutCoil, bsp_ModBus_Tx::WriteCoils, bsp_ModBus_Tx::WriteCoilsVar, bsp_ModBus_Tx::WriteOneCoil, bsp_ModBus_Tx::WriteOneReg, bsp_ModBus_Tx::WriteRegs, bsp_ModBus_Tx::WriteRegsVar.