bsp_ModBus_Tx
u8 bsp_ModBus_Tx::ID
器件ID
Referenced by bsp_ModBus_Tx, ReadInCoil, ReadInReg, ReadKeepReg, ReadOutCoil, WriteCoils, WriteCoilsVar, WriteOneCoil, WriteOneReg, WriteRegs, WriteRegsVar.
bsp_ModBus_Tx::bsp_ModBus_Tx(u8 ID)
References ID.
void bsp_ModBus_Tx::ReadKeepReg(u16 address, u16 mem)
发送读取保存寄存器的指令
address 读取的地址 mem 读取的个数 无返回值
References CRC16_MODBUS, Fun_R_KeepReg, ID, Transmit.
void bsp_ModBus_Tx::ReadInReg(u16 address, u16 mem)
发送读取输入寄存器的指令
address 读取的地址 mem 读取的个数 无返回值
References CRC16_MODBUS, Fun_R_InReg, ID, Transmit.
void bsp_ModBus_Tx::WriteOneReg(u16 address, u16 var)
发送写一个寄存器的指令
address 写入的地址 var 写入的值 无返回值
References CRC16_MODBUS, Fun_W_OneReg, ID, Transmit.
void bsp_ModBus_Tx::WriteRegs(u16 address, u16 mem, u16 *var)
发送写多个寄存器的指令
address 写入的地址 mem 写入的个数 *var 待写入数据的缓冲区 无返回值 简单通信建议使用WriteRegsVar
References CRC16_MODBUS, Fun_W_Regs, ID, Transmit.
void bsp_ModBus_Tx::WriteRegsVar(u16 address, u16 mem,...)
发送写多个寄存器的指令
address 写入的地址 mem 写入的个数 var 写入的数据 根据mem的数量决定此处数量 无返回值
References CRC16_MODBUS, Fun_W_Regs, ID, Transmit.
void bsp_ModBus_Tx::ReadOutCoil(u16 address, u16 mem)
发送读输出线圈的指令
address 读取的地址 mem 读取的个数 无返回值
References CRC16_MODBUS, Fun_R_OutCoil, ID, Transmit.
void bsp_ModBus_Tx::ReadInCoil(u16 address, u16 mem)
发送读输入线圈的指令
address 读取的地址 mem 读取的个数 无返回值
References CRC16_MODBUS, Fun_R_InCoil, ID, Transmit.
void bsp_ModBus_Tx::WriteOneCoil(u16 address, u16 state)
发送写入一个线圈的指令
address 写入的地址 state 写入的状态 0:复位 其他:置位 无返回值
References CRC16_MODBUS, Fun_W_OneCoil, ID, Transmit.
void bsp_ModBus_Tx::WriteCoils(u16 address, u16 mem, u8 *var)
发送写多个线圈的指令
address 写入的地址 mem 写入的个数 *var 待写入数据的缓冲区 无返回值 简单通信建议使用WriteCoilsVar
References CRC16_MODBUS, Fun_W_Coils, ID, Transmit.
void bsp_ModBus_Tx::WriteCoilsVar(u16 address, u16 mem,...)
发送写多个线圈的指令
address 写入的地址 mem 写入的个数 var 写入的数据 根据mem的数量决定此处数量 无返回值
References CRC16_MODBUS, Fun_W_Coils, ID, Transmit.
virtual void bsp_ModBus_Tx::Transmit(u8 *dat, u16 len)=0
Referenced by ReadInCoil, ReadInReg, ReadKeepReg, ReadOutCoil, WriteCoils, WriteCoilsVar, WriteOneCoil, WriteOneReg, WriteRegs, WriteRegsVar.