STL_rQueue
void(*)(void) STL_rQueue::poptopfun(void)(void)
u32 STL_rQueue::room
Referenced by clean, push, STL_rQueue, The_room.
u32 STL_rQueue::size
Referenced by clean, pop, push, STL_rQueue, The_size, top.
u8* STL_rQueue::dat
Referenced by clean, pop, poptop32, push, STL_rQueue, top, ~STL_rQueue.
STL_rQueue::STL_rQueue(void)
References dat, room, size.
STL_rQueue::~STL_rQueue(void)
References dat.
u8 STL_rQueue::push(u8 var)
压入一个成员
var 需要压入的数值 错误号
References dat, QUEUES_OK, QUEUES_REAL_ERROR, room, size.
Referenced by push32.
u8 STL_rQueue::pop(void)
弹出一个成员
错误号
References dat, QUEUES_EMPTY, QUEUES_OK, size.
Referenced by poptop, poptop32.
u8 STL_rQueue::top(u8 &var)
显示最后压入的数值
&var 最后压入数值的储存变量 错误号
References dat, QUEUES_EMPTY, QUEUES_OK, size.
Referenced by poptop, poptop32.
u32 STL_rQueue::The_size(void)
返回成员数量
成员数量,为u8类型,如u32将占4个元素
References size.
u32 STL_rQueue::The_room(void)
返回占用的内存数
内存数,u8类型
References room.
u8 STL_rQueue::clean(void)
将申请的空间比对所需空间,腾出冗余空间
错误号
References dat, QUEUES_OK, QUEUES_REAL_ERROR, room, size.
u8 STL_rQueue::poptop(void)
弹出并且返回一个成员
弹出的成员值 该函数不会检查成功与否
References pop, top.
u8 STL_rQueue::push32(u32 var)
压入一个32位成员
var 需要压入的数值 错误号
References push, QUEUES_OK.
Referenced by pushfun.
u32 STL_rQueue::poptop32(void)
弹出并且返回一个32位成员
弹出的成员值 该函数不会检查成功与否
References dat, pop, top.
void STL_rQueue::pushfun(void(*fun)(void))
压入一个void(*)void函数
该函数不会检查成功与否
References push32.