STL_lQueue
void(*)(void) STL_lQueue::poptopfun(void)(void)
u32 STL_lQueue::mem
Referenced by pop, push, STL_lQueue, top, ~STL_lQueue.
_lQueue* STL_lQueue::Hdat
Referenced by pop, push, STL_lQueue.
_lQueue* STL_lQueue::Tdat
Referenced by pop, push, STL_lQueue, top.
STL_lQueue::STL_lQueue(void)
References Hdat, mem, Tdat.
STL_lQueue::~STL_lQueue(void)
References mem, pop.
u8 STL_lQueue::push(void *&var, u32 size)
压入一个成员
*&var 需要压入的数值的地址 size 需要压入的数值的长度 错误号
References _lQueue::back, _lQueue::dat, Hdat, mem, QUEUES_MALL_ERROR, QUEUES_OK, _lQueue::size, Tdat.
Referenced by push32, push8.
u8 STL_lQueue::pop(void)
弹出一个成员
错误号 无论push进去的是32位还是8位数,都用这个弹出
References _lQueue::back, _lQueue::dat, Hdat, mem, QUEUES_EMPTY, QUEUES_OK, Tdat.
Referenced by poptop32, poptop8, ~STL_lQueue.
u8 STL_lQueue::top(void *&var, u32 &size)
显示队列顶部成员
*&var 需要赋予的数值的地址 &size 需要赋予的数值的长度 错误号
References _lQueue::dat, mem, QUEUES_EMPTY, QUEUES_OK, _lQueue::size, Tdat.
Referenced by top32, top8.
u8 STL_lQueue::push8(u8 var)
压入一个8位成员
var 需要压入的8位数据 错误号
References push, QUEUES_MALL_ERROR, QUEUES_OK.
u8 STL_lQueue::top8(u8 &var)
显示队列顶成员
&var 结果赋予给该变量 错误号
References QUEUES_EMPTY, QUEUES_OK, top.
Referenced by poptop8.
u8 STL_lQueue::poptop8(void)
显示并且弹出一个队列顶成员
返回弹出的数值
References pop, top8.
u8 STL_lQueue::push32(u32 var)
压入一个32位成员
var 需要压入的32位数据 错误号
References push, QUEUES_MALL_ERROR, QUEUES_OK.
Referenced by pushfun.
u8 STL_lQueue::top32(u32 &var)
显示队列顶成员
&var 结果赋予给该变量 错误号
References QUEUES_EMPTY, QUEUES_OK, top.
Referenced by poptop32.
u32 STL_lQueue::poptop32(void)
显示并且弹出一个队列顶成员
返回弹出的数值
References pop, top32.
u8 STL_lQueue::pushfun(void(*fun)(void))
压入一个void(*)(void)函数指针
*fun 需要压入的函数 错误号 如果有个函数是 void fun(void); 可以通过pushfun(fun);将其压入
References push32.