STL_rStack
void(*)(void) STL_rStack::poptopfun(void)(void)
u32 STL_rStack::room
Referenced by clean, push, STL_rStack, The_room.
u32 STL_rStack::size
Referenced by clean, pop, push, STL_rStack, The_size, top.
u8* STL_rStack::dat
Referenced by clean, poptop32, push, STL_rStack, top, ~STL_rStack.
STL_rStack::STL_rStack(void)
References dat, room, size.
STL_rStack::~STL_rStack(void)
References dat.
u8 STL_rStack::push(u8 var)
压入一个成员
var 需要压入的数值 错误号
References dat, room, size, STACKS_OK, STACKS_REAL_ERROR.
Referenced by push32.
u8 STL_rStack::pop(void)
弹出一个成员
错误号
References size, STACKS_EMPTY, STACKS_OK.
Referenced by poptop, poptop32.
u8 STL_rStack::top(u8 &var)
显示最后压入的数值
&var 最后压入数值的储存变量 错误号
References dat, size, STACKS_EMPTY, STACKS_OK.
Referenced by poptop, poptop32.
u32 STL_rStack::The_size(void)
返回成员数量
成员数量,为u8类型,如u32将占4个元素
References size.
u32 STL_rStack::The_room(void)
返回占用的内存数
内存数,u8类型
References room.
u8 STL_rStack::clean(void)
将申请的空间比对所需空间,腾出冗余空间
错误号
References dat, room, size, STACKS_OK, STACKS_REAL_ERROR.
u8 STL_rStack::poptop(void)
弹出并且返回一个成员
弹出的成员值 该函数不会检查成功与否
References pop, top.
u8 STL_rStack::push32(u32 var)
压入一个32位成员
var 需要压入的数值 错误号
References push, STACKS_OK.
Referenced by pushfun.
u32 STL_rStack::poptop32(void)
弹出并且返回一个32位成员
弹出的成员值 该函数不会检查成功与否
References dat, pop, top.
void STL_rStack::pushfun(void(*fun)(void))
压入一个void(*)void函数
该函数不会检查成功与否
References push32.