STL_lStack
void(*)(void) STL_lStack::poptopfun(void)(void)
u32 STL_lStack::mem
Referenced by pop, push, STL_lStack, top, ~STL_lStack.
_lStack* STL_lStack::dat
Referenced by pop, push, STL_lStack, top.
STL_lStack::STL_lStack(void)
References dat, mem.
STL_lStack::~STL_lStack(void)
References mem, pop.
u8 STL_lStack::push(void *&var, u32 size)
压入一个成员
*&var 需要压入的数值的地址 size 需要压入的数值的长度 错误号
References _lStack::dat, dat, _lStack::front, mem, _lStack::size, STACKS_MALL_ERROR, STACKS_OK.
Referenced by push32, push8.
u8 STL_lStack::pop(void)
弹出一个成员
错误号 无论push进去的是32位还是8位数,都用这个弹出
References _lStack::dat, dat, _lStack::front, mem, STACKS_EMPTY, STACKS_OK.
Referenced by poptop32, poptop8, ~STL_lStack.
u8 STL_lStack::top(void *&var, u32 &size)
显示栈顶部成员
*&var 需要赋予的数值的地址 &size 需要赋予的数值的长度 错误号
References _lStack::dat, dat, mem, _lStack::size, STACKS_EMPTY, STACKS_OK.
Referenced by top32, top8.
u8 STL_lStack::push8(u8 var)
压入一个8位成员
var 需要压入的8位数据 错误号
References push, STACKS_MALL_ERROR, STACKS_OK.
u8 STL_lStack::top8(u8 &var)
显示栈顶成员
&var 结果赋予给该变量 错误号
References STACKS_EMPTY, STACKS_OK, top.
Referenced by poptop8.
u8 STL_lStack::poptop8(void)
显示并且弹出一个栈顶成员
返回弹出的数值
References pop, top8.
u8 STL_lStack::push32(u32 var)
压入一个32位成员
var 需要压入的32位数据 错误号
References push, STACKS_MALL_ERROR, STACKS_OK.
Referenced by pushfun.
u8 STL_lStack::top32(u32 &var)
显示栈顶成员
&var 结果赋予给该变量 错误号
References STACKS_EMPTY, STACKS_OK, top.
Referenced by poptop32.
u32 STL_lStack::poptop32(void)
显示并且弹出一个栈顶成员
返回弹出的数值
References pop, top32.
u8 STL_lStack::pushfun(void(*fun)(void))
压入一个void(*)(void)函数指针
*fun 需要压入的函数 错误号 如果有个函数是 void fun(void); 可以通过pushfun(fun);将其压入
References push32.