bsp_STM32_OLED
bsp_STM32_OLED::bsp_STM32_OLED(bsp_IIC_STM32 &IICS)
bsp_STM32_OLED::bsp_STM32_OLED(GPIO_TypeDef *GPIOx_SCK, uint16_t GPIO_Pin_SCK, GPIO_TypeDef *GPIOx_SDA, uint16_t GPIO_Pin_SDA)
void bsp_STM32_OLED::Init(void)
OLED初始化 初始化显示屏的设置
References OLED_init_cmd, Send_cmd.
void bsp_STM32_OLED::Column_set(u8 column)
光标定位行中的位置
column 设定的该行位置
References Send_cmd.
Referenced by Clear, Draw_ASCII, Picture_display, Picture_ReverseDisplay.
void bsp_STM32_OLED::Page_set(u8 page)
光标定位于一页
page 设定所处的页位置
References Send_cmd.
Referenced by Clear, Draw_ASCII, Picture_display, Picture_ReverseDisplay.
void bsp_STM32_OLED::Clear(u8 dat)
全页绘制
dat 全页绘制的数据,0x00为清空,0xFF为全涂
References Column_set, bsp_IIC::IIC_SendByte, bsp_IIC::IIC_Start, bsp_IIC::IIC_Stop, bsp_IIC::IIC_WaitAck, Page_set.
void bsp_STM32_OLED::Picture_display(const u8 *ptr_pic)
OLED绘图
*ptr_pic 图片数据的头
References Column_set, bsp_IIC::IIC_SendByte, bsp_IIC::IIC_Start, bsp_IIC::IIC_Stop, bsp_IIC::IIC_WaitAck, Page_set.
void bsp_STM32_OLED::Picture_ReverseDisplay(const u8 *ptr_pic)
OLED反向绘图
*ptr_pic 图片数据的头
References Column_set, bsp_IIC::IIC_SendByte, bsp_IIC::IIC_Start, bsp_IIC::IIC_Stop, bsp_IIC::IIC_WaitAck, Page_set.
void bsp_STM32_OLED::Draw_ASCII(u32 H, u32 V, u8 word)
OLED绘制ASCII字符
H 行数 V 列数 word 所要显示的字符
References Column_set, OLED_WORD_ASCII, Page_set, Send_len_dat.
void bsp_STM32_OLED::Send_dat(u8 dat)
发送一条数据给OLED
dat 要发送的数据
References bsp_IIC::IIC_WriteOneByte.
void bsp_STM32_OLED::Send_cmd(u8 cmd)
发送一条指令给OLED
cmd 要发送的指令
References bsp_IIC::IIC_WriteOneByte.
Referenced by Column_set, Init, Page_set.
void bsp_STM32_OLED::Send_len_dat(u8 *dat, u32 len)
发送一串定长指令给OLED
*dat 要发送的指令头 len 指令长度
References bsp_IIC::IIC_Write.
Referenced by Draw_ASCII.