bsp_Digit
u16 bsp_Digit::division
分频系数,越大越慢
Referenced by bsp_Digit, DatCom, dop.
bool bsp_Digit::Polarity
共阴或共阳
Referenced by bsp_Digit, DatCom, dop.
GPIO_TypeDef* bsp_Digit::GPIOx_MOSIO
Referenced by bsp_Digit, dat.
uint16_t bsp_Digit::GPIO_Pin_MOSIO
Referenced by bsp_Digit, dat.
GPIO_TypeDef* bsp_Digit::GPIOx_S_CLK
Referenced by bsp_Digit, dat.
uint16_t bsp_Digit::GPIO_Pin_S_CLK
Referenced by bsp_Digit, dat.
GPIO_TypeDef* bsp_Digit::GPIOx_R_CLK
Referenced by bsp_Digit, com.
uint16_t bsp_Digit::GPIO_Pin_R_CLK
Referenced by bsp_Digit, com.
bsp_Digit::bsp_Digit(GPIO_TypeDef *GPIOx_MOSIO, uint16_t GPIO_Pin_MOSIO, GPIO_TypeDef *GPIOx_S_CLK, uint16_t GPIO_Pin_S_CLK, GPIO_TypeDef *GPIOx_R_CLK, uint16_t GPIO_Pin_R_CLK, bool Polarity)
References division, GPIO_Pin_MOSIO, GPIO_Pin_R_CLK, GPIO_Pin_S_CLK, GPIOx_MOSIO, GPIOx_R_CLK, GPIOx_S_CLK, Polarity.
void bsp_Digit::DatCom(u8 SendVal, u8 cha)
在某位显示一个数字
References com, dat, digit_ca, division, Polarity.
Referenced by num.
void bsp_Digit::num(u16 num)
显示一个四位数据
References DatCom, num.
Referenced by num, numdop.
void bsp_Digit::dop(u8 cha)
显示一个小数点
References com, dat, division, Polarity.
Referenced by numdop.
void bsp_Digit::numdop(u16 num, u8 cha)
显示数据与一个像素点
References dop, num.
void bsp_Digit::dat(u8 SendVal)
References GPIO_Pin_MOSIO, GPIO_Pin_S_CLK, GPIOx_MOSIO, GPIOx_S_CLK.
Referenced by DatCom, dop.
void bsp_Digit::com(void)
References GPIO_Pin_R_CLK, GPIOx_R_CLK.
Referenced by DatCom, dop.