bsp_AT
void bsp_AT::com(const char *dat)
发送一条AT指令,已加AT+与\r 尾
dat 带发射数据
References Transmit.
Referenced by bsp_ATKESP8266::AP_TCP_Client, bsp_ATKESP8266::AP_TCP_Service, bsp_ATKESP8266::AP_UDP, bsp_ATKESP8266::APSTA_TCP_Client, bsp_ATKESP8266::APSTA_TCP_Service, bsp_ATKESP8266::APSTA_UDP, bsp_ATKESP8266::STA_TCP_Client, bsp_ATKESP8266::STA_TCP_Service, bsp_ATKESP8266::STA_UDP, bsp_ATKESP8266::TCP_Client_T, bsp_ATKESP8266::TCP_Service_T, bsp_ATKESP8266::UDP_Service_T.
virtual void bsp_AT::Transmit(u8 *dat, u16 len)=0
发送数据到端口
dat 数据头 len 数据长度
Referenced by com.