bsp_SD
SPI_HandleTypeDef* bsp_SD::hspi
Referenced by bsp_SD, spi_readwrite, SPI_setspeed.
GPIO_TypeDef* bsp_SD::GPIOx_CS
Referenced by bsp_SD, SD_CS.
uint16_t bsp_SD::GPIO_Pin_CS
Referenced by bsp_SD, SD_CS.
u8 bsp_SD::DFF
Referenced by bsp_SD, SD_init, SD_sendcmd.
u8 bsp_SD::SD_TYPE
Referenced by bsp_SD, SD_init, SD_ReadDisk, SD_WriteDisk.
MSD_CARDINFO bsp_SD::SD0_CardInfo
Referenced by MSD0_GetCardInfo.
bsp_SD::bsp_SD(SPI_HandleTypeDef *hspi, GPIO_TypeDef *GPIOx_CS, uint16_t GPIO_Pin_CS)
References DFF, GPIO_Pin_CS, GPIOx_CS, hspi, SD_TYPE.
u8 bsp_SD::SD_init(void)
初始化SD卡
返回值:0,ok;其他,失败.
References CMD0, CMD1, CMD16, CMD41, CMD55, CMD58, CMD8, DFF, ERR, MMC, SD_CS, SD_sendcmd, SD_TYPE, spi_readwrite, SPI_setspeed, V1, V2, V2HC.
u8 bsp_SD::SD_ReadDisk(u8 *buf, u32 sector, u8 cnt)
读SD卡
*buf 数据缓存区 sector 起始扇区 cnt 扇区数 返回值:0,ok;其他,失败.
References CMD12, CMD17, CMD18, SD_CS, SD_ReceiveData, SD_sendcmd, SD_TYPE, V2HC.
Referenced by offsetRead, offsetWrite.
u8 bsp_SD::SD_WriteDisk(u8 *buf, u32 sector, u8 cnt)
写SD卡
*buf 数据缓存区 sector 起始扇区 cnt 扇区数 返回值:0,ok;其他,失败.
References CMD23, CMD24, CMD25, CMD55, MMC, SD_CS, SD_SendBlock, SD_sendcmd, SD_TYPE, V2HC.
Referenced by offsetWrite.
u32 bsp_SD::SD_GetSectorCount(void)
获取SD卡的总扇区数
总扇区数
References SD_GETCSD.
u8 bsp_SD::offsetWrite(u64 offset, u8 *dat, u64 datlen)
写入连贯的数据
offset 写入位置 *dat 数据缓冲区 datlen 写入长度 返回值:0,ok;其他,失败.
References SD_ReadDisk, SD_WriteDisk.
u8 bsp_SD::offsetRead(u64 offset, u8 *dat, u64 datlen)
读取连贯的数据
offset 读取位置 *dat 数据缓冲区 datlen 读取长度 返回值:0,ok;其他,失败.
References SD_ReadDisk.
void bsp_SD::SD_CS(u8 p)
片选信号
无
References GPIO_Pin_CS, GPIOx_CS.
Referenced by SD_GETCID, SD_GETCSD, SD_init, SD_ReadDisk, SD_ReceiveData, SD_sendcmd, SD_WriteDisk.
u8 bsp_SD::SD_GETCID(u8 *cid_data)
获取CID信息
CID信息
References CMD10, SD_CS, SD_ReceiveData, SD_sendcmd.
u8 bsp_SD::SD_GETCSD(u8 *csd_data)
获取CSD信息
CSD信息
References CMD9, SD_CS, SD_ReceiveData, SD_sendcmd.
Referenced by SD_GetSectorCount.
int bsp_SD::MSD0_GetCardInfo(PMSD_CARDINFO SD0_CardInfo)
References MSD_CARDINFO::BlockSize, MSD_CARDINFO::Capacity, MSD_CSD::CardComdClasses, MSD_CARDINFO::CardType, MSD_CARDINFO::CID, MSD_CID::CID_CRC, CMD10, CMD9, MSD_CSD::ContentProtectAppli, MSD_CSD::CopyFlag, MSD_CARDINFO::CSD, MSD_CSD::CSD_CRC, MSD_CSD::CSDStruct, MSD_CSD::DeviceSize, MSD_CSD::DeviceSizeMul, MSD_CSD::DSRImpl, MSD_CSD::ECC, MSD_CSD::EraseGrMul, MSD_CSD::EraseGrSize, MSD_CSD::FileFormat, MSD_CSD::FileFormatGrouop, MSD_CSD::ManDeflECC, MSD_CID::ManufactDate, MSD_CID::ManufacturerID, MSD_CSD::MaxBusClkFrec, MSD_CSD::MaxRdCurrentVDDMax, MSD_CSD::MaxRdCurrentVDDMin, MSD_CSD::MaxWrBlockLen, MSD_CSD::MaxWrCurrentVDDMax, MSD_CSD::MaxWrCurrentVDDMin, MSD_BLOCKSIZE, MSD_CSD::NSAC, MSD_CID::OEM_AppliID, MSD_CSD::PartBlockRead, MSD_CSD::PermWrProtect, MSD_CID::ProdName1, MSD_CID::ProdName2, MSD_CID::ProdRev, MSD_CID::ProdSN, MSD_CSD::RdBlockLen, MSD_CSD::RdBlockMisalign, MSD_CSD::Reserved1, MSD_CID::Reserved1, MSD_CSD::Reserved2, MSD_CID::Reserved2, MSD_CSD::Reserved3, MSD_CSD::Reserved4, SD0_CardInfo, SD_ReceiveData, SD_sendcmd, MSD_CSD::SysSpecVersion, MSD_CSD::TAAC, MSD_CSD::TempWrProtect, V2HC, MSD_CSD::WrBlockMisalign, MSD_CSD::WriteBlockPaPartial, MSD_CSD::WrProtectGrEnable, MSD_CSD::WrProtectGrSize, MSD_CSD::WrSpeedFact.
u8 bsp_SD::SD_ReceiveData(u8 *data, u16 len)
读取SD卡指定长度信息
*data 数据缓存区 len 长度 返回值:0,ok;其他,失败.
References SD_CS, spi_readwrite.
Referenced by MSD0_GetCardInfo, SD_GETCID, SD_GETCSD, SD_ReadDisk.
u8 bsp_SD::SD_SendBlock(u8 *buf, u8 cmd)
向SD卡写入一个扇区
*buf 数据缓存区 cmd 操作指令 返回值:0,ok;其他,失败.
References spi_readwrite.
Referenced by SD_WriteDisk.
u32 bsp_SD::SD_sendcmd(u8 cmd, u32 arg, u8 crc)
写SD卡
cmd 命令 arg crc 校验码
References CMD12, DFF, SD_CS, spi_readwrite.
Referenced by MSD0_GetCardInfo, SD_GETCID, SD_GETCSD, SD_init, SD_ReadDisk, SD_WriteDisk.
void bsp_SD::SPI_setspeed(u8 speed)
设置SPI的速率
speed 速率 无
References hspi.
Referenced by SD_init.
u8 bsp_SD::spi_readwrite(u8 Txdata)
References hspi.
Referenced by SD_init, SD_ReceiveData, SD_SendBlock, SD_sendcmd.