DRIVERS
lpf_e
gyro_fsr_e
accel_fsr_e
clock_sel_e
lp_accel_rate_e
unsigned char gyro_reg_s::who_am_i
unsigned char gyro_reg_s::rate_div
Referenced by get_st_biases, mpu_set_sample_rate.
unsigned char gyro_reg_s::lpf
Referenced by get_st_biases, mpu_lp_motion_interrupt, mpu_set_lpf.
unsigned char gyro_reg_s::prod_id
Referenced by mpu_init.
unsigned char gyro_reg_s::user_ctrl
Referenced by get_st_biases, mpu_lp_motion_interrupt, mpu_reset_fifo, mpu_set_bypass, mpu_set_sensors.
unsigned char gyro_reg_s::fifo_en
Referenced by get_st_biases, mpu_reset_fifo.
unsigned char gyro_reg_s::gyro_cfg
Referenced by get_st_biases, mpu_set_gyro_fsr.
unsigned char gyro_reg_s::accel_cfg
Referenced by get_st_biases, mpu_lp_motion_interrupt, mpu_set_accel_fsr.
unsigned char gyro_reg_s::motion_thr
Referenced by mpu_lp_motion_interrupt.
unsigned char gyro_reg_s::motion_dur
unsigned char gyro_reg_s::fifo_count_h
Referenced by get_st_biases, mpu_read_fifo, mpu_read_fifo_stream.
unsigned char gyro_reg_s::fifo_r_w
Referenced by get_st_biases, mpu_read_fifo, mpu_read_fifo_stream, mpu_read_reg, mpu_reg_dump.
unsigned char gyro_reg_s::raw_gyro
Referenced by mpu_get_gyro_reg.
unsigned char gyro_reg_s::raw_accel
Referenced by mpu_get_accel_reg.
unsigned char gyro_reg_s::temp
Referenced by mpu_get_temperature.
unsigned char gyro_reg_s::int_enable
Referenced by get_st_biases, mpu_lp_motion_interrupt, mpu_reset_fifo, set_int_enable.
unsigned char gyro_reg_s::dmp_int_status
Referenced by mpu_get_int_status.
unsigned char gyro_reg_s::int_status
Referenced by mpu_read_fifo, mpu_read_fifo_stream.
unsigned char gyro_reg_s::pwr_mgmt_1
Referenced by get_st_biases, mpu_init, mpu_lp_accel_mode, mpu_lp_motion_interrupt, mpu_set_sensors.
unsigned char gyro_reg_s::pwr_mgmt_2
Referenced by mpu_set_sensors.
unsigned char gyro_reg_s::int_pin_cfg
Referenced by mpu_set_bypass, mpu_set_int_latched.
unsigned char gyro_reg_s::mem_r_w
Referenced by mpu_read_mem, mpu_read_reg, mpu_reg_dump, mpu_write_mem.
unsigned char gyro_reg_s::accel_offs
Referenced by mpu_init.
unsigned char gyro_reg_s::i2c_mst
Referenced by get_st_biases, setup_compass.
unsigned char gyro_reg_s::bank_sel
Referenced by mpu_read_mem, mpu_write_mem.
unsigned char gyro_reg_s::mem_start_addr
unsigned char gyro_reg_s::prgm_start_h
Referenced by mpu_load_firmware.
unsigned char hw_s::addr
Referenced by get_accel_prod_shift, get_st_biases, gyro_self_test, mpu_get_accel_reg, mpu_get_compass_reg, mpu_get_gyro_reg, mpu_get_int_status, mpu_get_temperature, mpu_init, mpu_load_firmware, mpu_lp_accel_mode, mpu_lp_motion_interrupt, mpu_read_fifo, mpu_read_fifo_stream, mpu_read_mem, mpu_read_reg, mpu_reg_dump, mpu_reset_fifo, mpu_set_accel_bias, mpu_set_accel_fsr, mpu_set_bypass, mpu_set_compass_sample_rate, mpu_set_dmp_state, mpu_set_gyro_fsr, mpu_set_int_latched, mpu_set_lpf, mpu_set_sample_rate, mpu_set_sensors, mpu_write_mem, set_int_enable, setup_compass.
unsigned short hw_s::max_fifo
Referenced by mpu_read_fifo, mpu_read_fifo_stream.
unsigned char hw_s::num_reg
Referenced by mpu_read_reg, mpu_reg_dump.
unsigned short hw_s::temp_sens
Referenced by mpu_get_temperature.
short hw_s::temp_offset
Referenced by mpu_get_temperature.
unsigned short hw_s::bank_size
Referenced by mpu_read_mem, mpu_write_mem.
unsigned short motion_int_cache_s::gyro_fsr
Referenced by mpu_lp_motion_interrupt.
unsigned char motion_int_cache_s::accel_fsr
Referenced by mpu_lp_motion_interrupt.
unsigned short motion_int_cache_s::lpf
Referenced by mpu_lp_motion_interrupt.
unsigned short motion_int_cache_s::sample_rate
Referenced by mpu_lp_motion_interrupt.
unsigned char motion_int_cache_s::sensors_on
Referenced by mpu_lp_motion_interrupt.
unsigned char motion_int_cache_s::fifo_sensors
Referenced by mpu_lp_motion_interrupt.
unsigned char motion_int_cache_s::dmp_on
Referenced by mpu_lp_motion_interrupt.
unsigned char chip_cfg_s::gyro_fsr
Referenced by mpu_get_gyro_fsr, mpu_get_gyro_sens, mpu_init, mpu_lp_motion_interrupt, mpu_run_self_test, mpu_set_gyro_fsr.
unsigned char chip_cfg_s::accel_fsr
Referenced by mpu_get_accel_fsr, mpu_get_accel_sens, mpu_init, mpu_lp_motion_interrupt, mpu_run_self_test, mpu_set_accel_fsr.
unsigned char chip_cfg_s::sensors
Referenced by mpu_configure_fifo, mpu_get_accel_reg, mpu_get_compass_reg, mpu_get_gyro_reg, mpu_get_int_status, mpu_get_power_state, mpu_get_temperature, mpu_init, mpu_lp_accel_mode, mpu_lp_motion_interrupt, mpu_read_fifo, mpu_read_fifo_stream, mpu_read_mem, mpu_reset_fifo, mpu_run_self_test, mpu_set_accel_fsr, mpu_set_bypass, mpu_set_gyro_fsr, mpu_set_lpf, mpu_set_sample_rate, mpu_set_sensors, mpu_write_mem, set_int_enable.
unsigned char chip_cfg_s::lpf
Referenced by mpu_get_lpf, mpu_init, mpu_lp_motion_interrupt, mpu_run_self_test, mpu_set_lpf.
unsigned char chip_cfg_s::clk_src
Referenced by mpu_init, mpu_lp_accel_mode, mpu_lp_motion_interrupt, mpu_run_self_test, mpu_set_sensors.
unsigned short chip_cfg_s::sample_rate
Referenced by mpu_get_sample_rate, mpu_init, mpu_lp_motion_interrupt, mpu_run_self_test, mpu_set_compass_sample_rate, mpu_set_sample_rate.
unsigned char chip_cfg_s::fifo_enable
Referenced by mpu_configure_fifo, mpu_get_fifo_config, mpu_init, mpu_lp_motion_interrupt, mpu_read_fifo, mpu_reset_fifo, mpu_run_self_test, mpu_set_dmp_state.
unsigned char chip_cfg_s::int_enable
Referenced by mpu_reset_fifo, set_int_enable.
unsigned char chip_cfg_s::bypass_mode
Referenced by mpu_init, mpu_reset_fifo, mpu_set_bypass, mpu_set_int_latched.
unsigned char chip_cfg_s::accel_half
Referenced by mpu_get_accel_fsr, mpu_get_accel_sens, mpu_init.
unsigned char chip_cfg_s::lp_accel_mode
Referenced by mpu_configure_fifo, mpu_init, mpu_lp_accel_mode, mpu_set_sample_rate, mpu_set_sensors.
unsigned char chip_cfg_s::int_motion_only
Referenced by mpu_init, mpu_lp_motion_interrupt.
struct motion_int_cache_s chip_cfg_s::cache
Referenced by mpu_init, mpu_lp_motion_interrupt.
unsigned char chip_cfg_s::active_low_int
Referenced by mpu_init, mpu_set_bypass, mpu_set_int_latched, mpu_set_int_level.
unsigned char chip_cfg_s::latched_int
Referenced by mpu_init, mpu_set_bypass, mpu_set_int_latched.
unsigned char chip_cfg_s::dmp_on
Referenced by mpu_configure_fifo, mpu_get_dmp_state, mpu_get_sample_rate, mpu_init, mpu_lp_motion_interrupt, mpu_read_fifo, mpu_read_fifo_stream, mpu_reset_fifo, mpu_run_self_test, mpu_set_dmp_state, mpu_set_sample_rate, mpu_set_sensors, set_int_enable.
unsigned char chip_cfg_s::dmp_loaded
Referenced by mpu_init, mpu_load_firmware, mpu_set_dmp_state.
unsigned short chip_cfg_s::dmp_sample_rate
Referenced by mpu_init, mpu_load_firmware, mpu_set_dmp_state.
unsigned long test_s::gyro_sens
Referenced by get_st_biases, gyro_self_test.
unsigned long test_s::accel_sens
Referenced by get_st_biases.
unsigned char test_s::reg_rate_div
Referenced by get_st_biases.
unsigned char test_s::reg_lpf
Referenced by get_st_biases.
unsigned char test_s::reg_gyro_fsr
Referenced by get_st_biases.
unsigned char test_s::reg_accel_fsr
Referenced by get_st_biases.
unsigned short test_s::wait_ms
Referenced by get_st_biases.
unsigned char test_s::packet_thresh
float test_s::min_dps
Referenced by gyro_self_test.
float test_s::max_dps
Referenced by gyro_self_test.
float test_s::max_gyro_var
Referenced by gyro_self_test.
float test_s::min_g
Referenced by accel_self_test.
float test_s::max_g
Referenced by accel_self_test.
float test_s::max_accel_var
Referenced by accel_self_test.
const struct gyro_reg_s* gyro_state_s::reg
Referenced by get_st_biases, mpu_get_accel_reg, mpu_get_compass_reg, mpu_get_gyro_reg, mpu_get_int_status, mpu_get_temperature, mpu_init, mpu_load_firmware, mpu_lp_accel_mode, mpu_lp_motion_interrupt, mpu_read_fifo, mpu_read_fifo_stream, mpu_read_mem, mpu_read_reg, mpu_reg_dump, mpu_reset_fifo, mpu_set_accel_fsr, mpu_set_bypass, mpu_set_compass_sample_rate, mpu_set_gyro_fsr, mpu_set_int_latched, mpu_set_lpf, mpu_set_sample_rate, mpu_set_sensors, mpu_write_mem, set_int_enable, setup_compass.
const struct hw_s* gyro_state_s::hw
Referenced by get_accel_prod_shift, get_st_biases, gyro_self_test, mpu_get_accel_reg, mpu_get_compass_fsr, mpu_get_compass_reg, mpu_get_gyro_reg, mpu_get_int_status, mpu_get_temperature, mpu_init, mpu_load_firmware, mpu_lp_accel_mode, mpu_lp_motion_interrupt, mpu_read_fifo, mpu_read_fifo_stream, mpu_read_mem, mpu_read_reg, mpu_reg_dump, mpu_reset_fifo, mpu_set_accel_bias, mpu_set_accel_fsr, mpu_set_bypass, mpu_set_compass_sample_rate, mpu_set_dmp_state, mpu_set_gyro_fsr, mpu_set_int_latched, mpu_set_lpf, mpu_set_sample_rate, mpu_set_sensors, mpu_write_mem, set_int_enable, setup_compass.
struct chip_cfg_s gyro_state_s::chip_cfg
Referenced by mpu_configure_fifo, mpu_get_accel_fsr, mpu_get_accel_reg, mpu_get_accel_sens, mpu_get_compass_reg, mpu_get_compass_sample_rate, mpu_get_dmp_state, mpu_get_fifo_config, mpu_get_gyro_fsr, mpu_get_gyro_reg, mpu_get_gyro_sens, mpu_get_int_status, mpu_get_lpf, mpu_get_power_state, mpu_get_sample_rate, mpu_get_temperature, mpu_init, mpu_load_firmware, mpu_lp_accel_mode, mpu_lp_motion_interrupt, mpu_read_fifo, mpu_read_fifo_stream, mpu_read_mem, mpu_reset_fifo, mpu_run_self_test, mpu_set_accel_fsr, mpu_set_bypass, mpu_set_compass_sample_rate, mpu_set_dmp_state, mpu_set_gyro_fsr, mpu_set_int_latched, mpu_set_int_level, mpu_set_lpf, mpu_set_sample_rate, mpu_set_sensors, mpu_write_mem, set_int_enable, setup_compass.
const struct test_s* gyro_state_s::test
Referenced by get_st_biases.
const struct gyro_reg_s reg
Referenced by MPU_Read_Byte, MPU_Read_Len, mpu_read_reg, MPU_Write_Byte, MPU_Write_Len.
const struct hw_s hw
const struct test_s test
Referenced by accel_self_test, get_st_biases, gyro_self_test.
struct gyro_state_s st
Referenced by get_accel_prod_shift, get_st_biases, gyro_self_test, mpu_configure_fifo, mpu_get_accel_fsr, mpu_get_accel_reg, mpu_get_accel_sens, mpu_get_compass_fsr, mpu_get_compass_reg, mpu_get_compass_sample_rate, mpu_get_dmp_state, mpu_get_fifo_config, mpu_get_gyro_fsr, mpu_get_gyro_reg, mpu_get_gyro_sens, mpu_get_int_status, mpu_get_lpf, mpu_get_power_state, mpu_get_sample_rate, mpu_get_temperature, mpu_init, mpu_load_firmware, mpu_lp_accel_mode, mpu_lp_motion_interrupt, mpu_read_fifo, mpu_read_fifo_stream, mpu_read_mem, mpu_read_reg, mpu_reg_dump, mpu_reset_fifo, mpu_run_self_test, mpu_set_accel_bias, mpu_set_accel_fsr, mpu_set_bypass, mpu_set_compass_sample_rate, mpu_set_dmp_state, mpu_set_gyro_fsr, mpu_set_int_latched, mpu_set_int_level, mpu_set_lpf, mpu_set_sample_rate, mpu_set_sensors, mpu_write_mem, set_int_enable, setup_compass.
signed char gyro_orientation[9][9]
Referenced by mpu_dmp_init.
void(* int_param_s::cb) (void))(void)
unsigned short int_param_s::pin
unsigned char int_param_s::lp_exit
unsigned char int_param_s::active_low
const unsigned char dmp_memory[DMP_CODE_SIZE][DMP_CODE_SIZE]
Referenced by dmp_load_motion_driver_firmware.
const unsigned short sStartAddress
Referenced by dmp_load_motion_driver_firmware.
struct dmp_s dmp
Referenced by decode_gesture, dmp_enable_feature, dmp_get_enabled_features, dmp_get_fifo_rate, dmp_read_fifo, dmp_register_android_orient_cb, dmp_register_tap_cb, dmp_set_accel_bias, dmp_set_fifo_rate, dmp_set_gyro_bias, dmp_set_orientation.
void log_none(char *fmt,...)
static int set_int_enable(unsigned char enable)
Enable/disable data ready interrupt. If the DMP is on, the DMP interrupt is enabled. Otherwise, the data ready interrupt is used.
enable 1 to enable interrupt. 0 if successful.
References hw_s::addr, BIT_DATA_RDY_EN, BIT_DMP_INT_EN, gyro_state_s::chip_cfg, chip_cfg_s::dmp_on, gyro_state_s::hw, i2c_write, gyro_reg_s::int_enable, chip_cfg_s::int_enable, gyro_state_s::reg, chip_cfg_s::sensors, st.
Referenced by mpu_configure_fifo, mpu_lp_motion_interrupt, mpu_set_dmp_state.
int mpu_reg_dump(void)
Register dump for testing.
0 if successful.
References hw_s::addr, gyro_reg_s::fifo_r_w, gyro_state_s::hw, i2c_read, log_i, gyro_reg_s::mem_r_w, hw_s::num_reg, gyro_state_s::reg, st.
int mpu_read_reg(unsigned char reg, unsigned char *data)
Read from a single register. NOTE: The memory and FIFO read/write registers cannot be accessed.
reg Register address. data Register data. 0 if successful.
References hw_s::addr, gyro_reg_s::fifo_r_w, gyro_state_s::hw, i2c_read, gyro_reg_s::mem_r_w, hw_s::num_reg, gyro_state_s::reg, reg, st.
int mpu_init(void)
Initialize hardware. Initial configuration: Gyro FSR: +/- 2000DPS Accel FSR +/- 2G DLPF: 42Hz FIFO rate: 50Hz Clock source: Gyro PLL FIFO: Disabled. Data ready interrupt: Disabled, active low, unlatched.
int_param Platform-specific parameters to interrupt API. 0 if successful.
References chip_cfg_s::accel_fsr, chip_cfg_s::accel_half, gyro_reg_s::accel_offs, chip_cfg_s::active_low_int, hw_s::addr, BIT_FIFO_SIZE_1024, BIT_RESET, chip_cfg_s::bypass_mode, chip_cfg_s::cache, gyro_state_s::chip_cfg, chip_cfg_s::clk_src, delay_ms, chip_cfg_s::dmp_loaded, chip_cfg_s::dmp_on, chip_cfg_s::dmp_sample_rate, chip_cfg_s::fifo_enable, chip_cfg_s::gyro_fsr, gyro_state_s::hw, i2c_read, i2c_write, chip_cfg_s::int_motion_only, INV_CLK_PLL, chip_cfg_s::latched_int, log_e, log_i, chip_cfg_s::lp_accel_mode, chip_cfg_s::lpf, mpu_configure_fifo, mpu_read_mem, mpu_set_accel_fsr, mpu_set_bypass, mpu_set_compass_sample_rate, mpu_set_gyro_fsr, mpu_set_lpf, mpu_set_sample_rate, mpu_set_sensors, gyro_reg_s::prod_id, gyro_reg_s::pwr_mgmt_1, gyro_state_s::reg, chip_cfg_s::sample_rate, chip_cfg_s::sensors, setup_compass, st.
Referenced by mpu_dmp_init.
int mpu_lp_accel_mode(unsigned char rate)
Enter low-power accel-only mode. In low-power accel mode, the chip goes to sleep and only wakes up to sample the accelerometer at one of the following frequencies: MPU6050: 1.25Hz, 5Hz, 20Hz, 40Hz MPU6500: 1.25Hz, 2.5Hz, 5Hz, 10Hz, 20Hz, 40Hz, 80Hz, 160Hz, 320Hz, 640Hz If the requested rate is not one listed above, the device will be set to the next highest rate. Requesting a rate above the maximum supported frequency will result in an error. To select a fractional wake-up frequency, round down the value passed to rate.
rate Minimum sampling rate, or zero to disable LP accel mode. 0 if successful.
References hw_s::addr, BIT_LPA_CYCLE, BIT_STBY_XYZG, gyro_state_s::chip_cfg, chip_cfg_s::clk_src, gyro_state_s::hw, i2c_write, INV_LPA_1_25HZ, INV_LPA_20HZ, INV_LPA_40HZ, INV_LPA_5HZ, INV_XYZ_ACCEL, chip_cfg_s::lp_accel_mode, mpu_configure_fifo, mpu_set_int_latched, mpu_set_lpf, gyro_reg_s::pwr_mgmt_1, gyro_state_s::reg, chip_cfg_s::sensors, st.
Referenced by mpu_lp_motion_interrupt, mpu_set_sample_rate.
int mpu_get_gyro_reg(short *data, unsigned long *timestamp)
Read raw gyro data directly from the registers.
data Raw data in hardware units. timestamp Timestamp in milliseconds. Null if not needed. 0 if successful.
References hw_s::addr, gyro_state_s::chip_cfg, get_ms, gyro_state_s::hw, i2c_read, INV_XYZ_GYRO, gyro_reg_s::raw_gyro, gyro_state_s::reg, chip_cfg_s::sensors, st.
int mpu_get_accel_reg(short *data, unsigned long *timestamp)
Read raw accel data directly from the registers.
data Raw data in hardware units. timestamp Timestamp in milliseconds. Null if not needed. 0 if successful.
References hw_s::addr, gyro_state_s::chip_cfg, get_ms, gyro_state_s::hw, i2c_read, INV_XYZ_ACCEL, gyro_reg_s::raw_accel, gyro_state_s::reg, chip_cfg_s::sensors, st.
int mpu_get_temperature(long *data, unsigned long *timestamp)
Read temperature data directly from the registers.
data Data in q16 format. timestamp Timestamp in milliseconds. Null if not needed. 0 if successful.
References hw_s::addr, gyro_state_s::chip_cfg, get_ms, gyro_state_s::hw, i2c_read, gyro_state_s::reg, chip_cfg_s::sensors, st, gyro_reg_s::temp, hw_s::temp_offset, hw_s::temp_sens.
int mpu_set_accel_bias(const long *accel_bias)
Push biases to the accel bias registers. This function expects biases relative to the current sensor output, and these biases will be added to the factory-supplied values.
accel_bias New biases. 0 if successful.
References hw_s::addr, gyro_state_s::hw, i2c_read, i2c_write, st.
int mpu_reset_fifo(void)
Reset FIFO read/write pointers.
0 if successful.
References hw_s::addr, BIT_AUX_IF_EN, BIT_DATA_RDY_EN, BIT_DMP_EN, BIT_DMP_INT_EN, BIT_DMP_RST, BIT_FIFO_EN, BIT_FIFO_RST, chip_cfg_s::bypass_mode, gyro_state_s::chip_cfg, delay_ms, chip_cfg_s::dmp_on, gyro_reg_s::fifo_en, chip_cfg_s::fifo_enable, gyro_state_s::hw, i2c_write, gyro_reg_s::int_enable, chip_cfg_s::int_enable, INV_XYZ_COMPASS, gyro_state_s::reg, chip_cfg_s::sensors, st, gyro_reg_s::user_ctrl.
Referenced by dmp_enable_6x_lp_quat, dmp_enable_feature, dmp_enable_lp_quat, dmp_read_fifo, mpu_configure_fifo, mpu_read_fifo, mpu_read_fifo_stream, mpu_set_dmp_state.
int mpu_get_gyro_fsr(unsigned short *fsr)
Get the gyro full-scale range.
fsr Current full-scale range. 0 if successful.
References gyro_state_s::chip_cfg, chip_cfg_s::gyro_fsr, INV_FSR_1000DPS, INV_FSR_2000DPS, INV_FSR_250DPS, INV_FSR_500DPS, st.
Referenced by mpu_lp_motion_interrupt, mpu_run_self_test.
int mpu_set_gyro_fsr(unsigned short fsr)
Set the gyro full-scale range.
fsr Desired full-scale range. 0 if successful.
References hw_s::addr, gyro_state_s::chip_cfg, gyro_reg_s::gyro_cfg, chip_cfg_s::gyro_fsr, gyro_state_s::hw, i2c_write, INV_FSR_1000DPS, INV_FSR_2000DPS, INV_FSR_250DPS, INV_FSR_500DPS, gyro_state_s::reg, chip_cfg_s::sensors, st.
Referenced by mpu_init, mpu_lp_motion_interrupt, mpu_run_self_test.
int mpu_get_accel_fsr(unsigned char *fsr)
Get the accel full-scale range.
fsr Current full-scale range. 0 if successful.
References chip_cfg_s::accel_fsr, chip_cfg_s::accel_half, gyro_state_s::chip_cfg, INV_FSR_16G, INV_FSR_2G, INV_FSR_4G, INV_FSR_8G, st.
Referenced by dmp_set_tap_thresh, mpu_lp_motion_interrupt, mpu_run_self_test.
int mpu_set_accel_fsr(unsigned char fsr)
Set the accel full-scale range.
fsr Desired full-scale range. 0 if successful.
References gyro_reg_s::accel_cfg, chip_cfg_s::accel_fsr, hw_s::addr, gyro_state_s::chip_cfg, gyro_state_s::hw, i2c_write, INV_FSR_16G, INV_FSR_2G, INV_FSR_4G, INV_FSR_8G, gyro_state_s::reg, chip_cfg_s::sensors, st.
Referenced by mpu_init, mpu_lp_motion_interrupt, mpu_run_self_test.
int mpu_get_lpf(unsigned short *lpf)
Get the current DLPF setting.
lpf Current LPF setting. 0 if successful.
References gyro_state_s::chip_cfg, INV_FILTER_10HZ, INV_FILTER_188HZ, INV_FILTER_20HZ, INV_FILTER_2100HZ_NOLPF, INV_FILTER_256HZ_NOLPF2, INV_FILTER_42HZ, INV_FILTER_5HZ, INV_FILTER_98HZ, chip_cfg_s::lpf, st.
Referenced by mpu_lp_motion_interrupt, mpu_run_self_test.
int mpu_set_lpf(unsigned short lpf)
Set digital low pass filter. The following LPF settings are supported: 188, 98, 42, 20, 10, 5.
lpf Desired LPF setting. 0 if successful.
References hw_s::addr, gyro_state_s::chip_cfg, gyro_state_s::hw, i2c_write, INV_FILTER_10HZ, INV_FILTER_188HZ, INV_FILTER_20HZ, INV_FILTER_42HZ, INV_FILTER_5HZ, INV_FILTER_98HZ, gyro_reg_s::lpf, chip_cfg_s::lpf, gyro_state_s::reg, chip_cfg_s::sensors, st.
Referenced by mpu_init, mpu_lp_accel_mode, mpu_lp_motion_interrupt, mpu_run_self_test, mpu_set_sample_rate.
int mpu_get_sample_rate(unsigned short *rate)
Get sampling rate.
rate Current sampling rate (Hz). 0 if successful.
References gyro_state_s::chip_cfg, chip_cfg_s::dmp_on, chip_cfg_s::sample_rate, st.
Referenced by mpu_lp_motion_interrupt, mpu_run_self_test.
int mpu_set_sample_rate(unsigned short rate)
Set sampling rate. Sampling rate must be between 4Hz and 1kHz.
rate Desired sampling rate (Hz). 0 if successful.
References hw_s::addr, gyro_state_s::chip_cfg, chip_cfg_s::dmp_on, gyro_state_s::hw, i2c_write, chip_cfg_s::lp_accel_mode, min, mpu_lp_accel_mode, mpu_set_compass_sample_rate, mpu_set_lpf, gyro_reg_s::rate_div, gyro_state_s::reg, chip_cfg_s::sample_rate, chip_cfg_s::sensors, st.
Referenced by mpu_dmp_init, mpu_init, mpu_lp_motion_interrupt, mpu_run_self_test, mpu_set_dmp_state.
int mpu_get_compass_sample_rate(unsigned short *rate)
Get compass sampling rate.
rate Current compass sampling rate (Hz). 0 if successful.
References gyro_state_s::chip_cfg, st.
int mpu_set_compass_sample_rate(unsigned short rate)
Set compass sampling rate. The compass on the auxiliary I2C bus is read by the MPU hardware at a maximum of 100Hz. The actual rate can be set to a fraction of the gyro sampling rate.
WARNING: The new rate may be different than what was requested. Call mpu_get_compass_sample_rate to check the actual setting. rate Desired compass sampling rate (Hz). 0 if successful.
References hw_s::addr, gyro_state_s::chip_cfg, gyro_state_s::hw, i2c_write, gyro_state_s::reg, chip_cfg_s::sample_rate, st.
Referenced by mpu_init, mpu_set_sample_rate.
int mpu_get_gyro_sens(float *sens)
Get gyro sensitivity scale factor.
sens Conversion from hardware units to dps. 0 if successful.
References gyro_state_s::chip_cfg, chip_cfg_s::gyro_fsr, INV_FSR_1000DPS, INV_FSR_2000DPS, INV_FSR_250DPS, INV_FSR_500DPS, st.
Referenced by run_self_test.
int mpu_get_accel_sens(unsigned short *sens)
Get accel sensitivity scale factor.
sens Conversion from hardware units to g's. 0 if successful.
References chip_cfg_s::accel_fsr, chip_cfg_s::accel_half, gyro_state_s::chip_cfg, INV_FSR_16G, INV_FSR_2G, INV_FSR_4G, INV_FSR_8G, st.
Referenced by dmp_set_accel_bias, run_self_test.
int mpu_get_fifo_config(unsigned char *sensors)
Get current FIFO configuration. sensors can contain a combination of the following flags: INV_X_GYRO, INV_Y_GYRO, INV_Z_GYRO INV_XYZ_GYRO INV_XYZ_ACCEL
sensors Mask of sensors in FIFO. 0 if successful.
References gyro_state_s::chip_cfg, chip_cfg_s::fifo_enable, st.
Referenced by mpu_lp_motion_interrupt, mpu_run_self_test.
int mpu_configure_fifo(unsigned char sensors)
Select which sensors are pushed to FIFO. sensors can contain a combination of the following flags: INV_X_GYRO, INV_Y_GYRO, INV_Z_GYRO INV_XYZ_GYRO INV_XYZ_ACCEL
sensors Mask of sensors to push to FIFO. 0 if successful.
References gyro_state_s::chip_cfg, chip_cfg_s::dmp_on, chip_cfg_s::fifo_enable, chip_cfg_s::lp_accel_mode, mpu_reset_fifo, chip_cfg_s::sensors, set_int_enable, st.
Referenced by mpu_dmp_init, mpu_init, mpu_lp_accel_mode, mpu_lp_motion_interrupt, mpu_run_self_test.
int mpu_get_power_state(unsigned char *power_on)
Get current power state.
power_on 1 if turned on, 0 if suspended. 0 if successful.
References gyro_state_s::chip_cfg, chip_cfg_s::sensors, st.
int mpu_set_sensors(unsigned char sensors)
Turn specific sensors on/off. sensors can contain a combination of the following flags: INV_X_GYRO, INV_Y_GYRO, INV_Z_GYRO INV_XYZ_GYRO INV_XYZ_ACCEL INV_XYZ_COMPASS
sensors Mask of sensors to wake. 0 if successful.
References hw_s::addr, BIT_AUX_IF_EN, BIT_DMP_EN, BIT_SLEEP, BIT_STBY_XG, BIT_STBY_XYZA, BIT_STBY_YG, BIT_STBY_ZG, gyro_state_s::chip_cfg, chip_cfg_s::clk_src, delay_ms, chip_cfg_s::dmp_on, gyro_state_s::hw, i2c_read, i2c_write, INV_CLK_PLL, INV_X_GYRO, INV_XYZ_ACCEL, INV_XYZ_COMPASS, INV_XYZ_GYRO, INV_Y_GYRO, INV_Z_GYRO, chip_cfg_s::lp_accel_mode, mpu_set_bypass, mpu_set_int_latched, gyro_reg_s::pwr_mgmt_1, gyro_reg_s::pwr_mgmt_2, gyro_state_s::reg, chip_cfg_s::sensors, st, gyro_reg_s::user_ctrl.
Referenced by mpu_dmp_init, mpu_init, mpu_lp_motion_interrupt, mpu_run_self_test.
int mpu_get_int_status(short *status)
Read the MPU interrupt status registers.
status Mask of interrupt bits. 0 if successful.
References hw_s::addr, gyro_state_s::chip_cfg, gyro_reg_s::dmp_int_status, gyro_state_s::hw, i2c_read, gyro_state_s::reg, chip_cfg_s::sensors, st.
int mpu_read_fifo(short *gyro, short *accel, unsigned long *timestamp, unsigned char *sensors, unsigned char *more)
Get one packet from the FIFO. If sensors does not contain a particular sensor, disregard the data returned to that pointer. sensors can contain a combination of the following flags: INV_X_GYRO, INV_Y_GYRO, INV_Z_GYRO INV_XYZ_GYRO INV_XYZ_ACCEL If the FIFO has no new data, sensors will be zero. If the FIFO is disabled, sensors will be zero and this function will return a non-zero error code.
gyro Gyro data in hardware units. accel Accel data in hardware units. timestamp Timestamp in milliseconds. sensors Mask of sensors read from FIFO. more Number of remaining packets. 0 if successful.
References hw_s::addr, BIT_FIFO_OVERFLOW, gyro_state_s::chip_cfg, chip_cfg_s::dmp_on, gyro_reg_s::fifo_count_h, chip_cfg_s::fifo_enable, gyro_reg_s::fifo_r_w, get_ms, gyro_state_s::hw, i2c_read, gyro_reg_s::int_status, INV_X_GYRO, INV_XYZ_ACCEL, INV_Y_GYRO, INV_Z_GYRO, hw_s::max_fifo, MAX_PACKET_LENGTH, mpu_reset_fifo, gyro_state_s::reg, chip_cfg_s::sensors, st.
int mpu_read_fifo_stream(unsigned short length, unsigned char *data, unsigned char *more)
Get one unparsed packet from the FIFO. This function should be used if the packet is to be parsed elsewhere.
length Length of one FIFO packet. data FIFO packet. more Number of remaining packets.
References hw_s::addr, BIT_FIFO_OVERFLOW, gyro_state_s::chip_cfg, chip_cfg_s::dmp_on, gyro_reg_s::fifo_count_h, gyro_reg_s::fifo_r_w, gyro_state_s::hw, i2c_read, gyro_reg_s::int_status, hw_s::max_fifo, mpu_reset_fifo, gyro_state_s::reg, chip_cfg_s::sensors, st.
Referenced by dmp_read_fifo.
int mpu_set_bypass(unsigned char bypass_on)
Set device to bypass mode.
bypass_on 1 to enable bypass mode. 0 if successful.
References chip_cfg_s::active_low_int, hw_s::addr, BIT_ACTL, BIT_ANY_RD_CLR, BIT_AUX_IF_EN, BIT_BYPASS_EN, BIT_LATCH_EN, chip_cfg_s::bypass_mode, gyro_state_s::chip_cfg, delay_ms, gyro_state_s::hw, i2c_read, i2c_write, gyro_reg_s::int_pin_cfg, INV_XYZ_COMPASS, chip_cfg_s::latched_int, gyro_state_s::reg, chip_cfg_s::sensors, st, gyro_reg_s::user_ctrl.
Referenced by mpu_init, mpu_set_dmp_state, mpu_set_sensors, setup_compass.
int mpu_set_int_level(unsigned char active_low)
Set interrupt level.
active_low 1 for active low, 0 for active high. 0 if successful.
References chip_cfg_s::active_low_int, gyro_state_s::chip_cfg, st.
int mpu_set_int_latched(unsigned char enable)
Enable latched interrupts. Any MPU register will clear the interrupt.
enable 1 to enable, 0 to disable. 0 if successful.
References chip_cfg_s::active_low_int, hw_s::addr, BIT_ACTL, BIT_ANY_RD_CLR, BIT_BYPASS_EN, BIT_LATCH_EN, chip_cfg_s::bypass_mode, gyro_state_s::chip_cfg, gyro_state_s::hw, i2c_write, gyro_reg_s::int_pin_cfg, chip_cfg_s::latched_int, gyro_state_s::reg, st.
Referenced by mpu_lp_accel_mode, mpu_set_sensors.
static int get_accel_prod_shift(float *st_shift)
References hw_s::addr, gyro_state_s::hw, i2c_read, st.
Referenced by accel_self_test.
static int accel_self_test(long *bias_regular, long *bias_st)
References fabs, get_accel_prod_shift, test_s::max_accel_var, test_s::max_g, test_s::min_g, test.
Referenced by mpu_run_self_test.
static int gyro_self_test(long *bias_regular, long *bias_st)
References hw_s::addr, fabs, test_s::gyro_sens, gyro_state_s::hw, i2c_read, test_s::max_dps, test_s::max_gyro_var, test_s::min_dps, st, test.
Referenced by mpu_run_self_test.
static int get_st_biases(long *gyro, long *accel, unsigned char hw_test)
References gyro_reg_s::accel_cfg, test_s::accel_sens, hw_s::addr, BIT_DMP_RST, BIT_FIFO_EN, BIT_FIFO_RST, delay_ms, gyro_reg_s::fifo_count_h, gyro_reg_s::fifo_en, gyro_reg_s::fifo_r_w, gyro_reg_s::gyro_cfg, test_s::gyro_sens, gyro_state_s::hw, gyro_reg_s::i2c_mst, i2c_read, i2c_write, gyro_reg_s::int_enable, INV_XYZ_ACCEL, INV_XYZ_GYRO, gyro_reg_s::lpf, MAX_PACKET_LENGTH, gyro_reg_s::pwr_mgmt_1, gyro_reg_s::rate_div, gyro_state_s::reg, test_s::reg_accel_fsr, test_s::reg_gyro_fsr, test_s::reg_lpf, test_s::reg_rate_div, st, gyro_state_s::test, test, gyro_reg_s::user_ctrl, test_s::wait_ms.
Referenced by mpu_run_self_test.
int mpu_run_self_test(long *gyro, long *accel)
Trigger gyro/accel/compass self-test. On success/error, the self-test returns a mask representing the sensor(s) that failed. For each bit, a one (1) represents a "pass" case; conversely, a zero (0) indicates a failure.
The mask is defined as follows: Bit 0: Gyro. Bit 1: Accel. Bit 2: Compass. Currently, the hardware self-test is unsupported for MPU6500. However, this function can still be used to obtain the accel and gyro biases. This function must be called with the device either face-up or face-down (z-axis is parallel to gravity). gyro Gyro biases in q16 format. accel Accel biases (if applicable) in q16 format. Result mask (see above).
References chip_cfg_s::accel_fsr, accel_self_test, gyro_state_s::chip_cfg, chip_cfg_s::clk_src, chip_cfg_s::dmp_on, chip_cfg_s::fifo_enable, get_st_biases, chip_cfg_s::gyro_fsr, gyro_self_test, INV_CLK_PLL, chip_cfg_s::lpf, mpu_configure_fifo, mpu_get_accel_fsr, mpu_get_fifo_config, mpu_get_gyro_fsr, mpu_get_lpf, mpu_get_sample_rate, mpu_set_accel_fsr, mpu_set_dmp_state, mpu_set_gyro_fsr, mpu_set_lpf, mpu_set_sample_rate, mpu_set_sensors, chip_cfg_s::sample_rate, chip_cfg_s::sensors, st.
Referenced by run_self_test.
int mpu_write_mem(unsigned short mem_addr, unsigned short length, unsigned char *data)
Write to the DMP memory. This function prevents I2C writes past the bank boundaries. The DMP memory is only accessible when the chip is awake.
mem_addr Memory location (bank << 8 | start address) length Number of bytes to write. data Bytes to write to memory. 0 if successful.
References hw_s::addr, gyro_reg_s::bank_sel, hw_s::bank_size, gyro_state_s::chip_cfg, gyro_state_s::hw, i2c_write, gyro_reg_s::mem_r_w, gyro_state_s::reg, chip_cfg_s::sensors, st.
Referenced by dmp_enable_6x_lp_quat, dmp_enable_feature, dmp_enable_gyro_cal, dmp_enable_lp_quat, dmp_set_accel_bias, dmp_set_fifo_rate, dmp_set_gyro_bias, dmp_set_interrupt_mode, dmp_set_orientation, dmp_set_pedometer_step_count, dmp_set_pedometer_walk_time, dmp_set_shake_reject_thresh, dmp_set_shake_reject_time, dmp_set_shake_reject_timeout, dmp_set_tap_axes, dmp_set_tap_count, dmp_set_tap_thresh, dmp_set_tap_time, dmp_set_tap_time_multi, mpu_load_firmware.
int mpu_read_mem(unsigned short mem_addr, unsigned short length, unsigned char *data)
Read from the DMP memory. This function prevents I2C reads past the bank boundaries. The DMP memory is only accessible when the chip is awake.
mem_addr Memory location (bank << 8 | start address) length Number of bytes to read. data Bytes read from memory. 0 if successful.
References hw_s::addr, gyro_reg_s::bank_sel, hw_s::bank_size, gyro_state_s::chip_cfg, gyro_state_s::hw, i2c_read, i2c_write, gyro_reg_s::mem_r_w, gyro_state_s::reg, chip_cfg_s::sensors, st.
Referenced by dmp_get_pedometer_step_count, dmp_get_pedometer_walk_time, mpu_init, mpu_load_firmware.
int mpu_load_firmware(unsigned short length, const unsigned char *firmware, unsigned short start_addr, unsigned short sample_rate)
Load and verify DMP image.
length Length of DMP image. firmware DMP code. start_addr Starting address of DMP code memory. sample_rate Fixed sampling rate used when DMP is enabled. 0 if successful.
References hw_s::addr, gyro_state_s::chip_cfg, chip_cfg_s::dmp_loaded, chip_cfg_s::dmp_sample_rate, gyro_state_s::hw, i2c_write, LOAD_CHUNK, min, mpu_read_mem, mpu_write_mem, gyro_reg_s::prgm_start_h, gyro_state_s::reg, st.
Referenced by dmp_load_motion_driver_firmware.
int mpu_set_dmp_state(unsigned char enable)
Enable/disable DMP support.
enable 1 to turn on the DMP. 0 if successful.
References hw_s::addr, gyro_state_s::chip_cfg, chip_cfg_s::dmp_loaded, chip_cfg_s::dmp_on, chip_cfg_s::dmp_sample_rate, chip_cfg_s::fifo_enable, gyro_state_s::hw, i2c_write, mpu_reset_fifo, mpu_set_bypass, mpu_set_sample_rate, set_int_enable, st.
Referenced by mpu_dmp_init, mpu_lp_motion_interrupt, mpu_run_self_test.
int mpu_get_dmp_state(unsigned char *enabled)
Get DMP state.
enabled 1 if enabled. 0 if successful.
References gyro_state_s::chip_cfg, chip_cfg_s::dmp_on, st.
int setup_compass(void)
References hw_s::addr, BIT_I2C_MST_VDDIO, BIT_I2C_READ, BIT_SLAVE_EN, gyro_state_s::chip_cfg, delay_ms, gyro_state_s::hw, gyro_reg_s::i2c_mst, i2c_read, i2c_write, log_e, mpu_set_bypass, gyro_state_s::reg, st.
Referenced by mpu_init.
int mpu_get_compass_reg(short *data, unsigned long *timestamp)
Read raw compass data.
data Raw data in hardware units. timestamp Timestamp in milliseconds. Null if not needed. 0 if successful.
References hw_s::addr, gyro_state_s::chip_cfg, get_ms, gyro_state_s::hw, i2c_read, i2c_write, INV_XYZ_COMPASS, gyro_state_s::reg, chip_cfg_s::sensors, st.
int mpu_get_compass_fsr(unsigned short *fsr)
Get the compass full-scale range.
fsr Current full-scale range. 0 if successful.
References gyro_state_s::hw, st.
int mpu_lp_motion_interrupt(unsigned short thresh, unsigned char time, unsigned char lpa_freq)
Enters LP accel motion interrupt mode. The behavior of this feature is very different between the MPU6050 and the MPU6500. Each chip's version of this feature is explained below.
MPU6050: When this mode is first enabled, the hardware captures a single accel sample, and subsequent samples are compared with this one to determine if the device is in motion. Therefore, whenever this "locked" sample needs to be changed, this function must be called again. The hardware motion threshold can be between 32mg and 8160mg in 32mg increments. Low-power accel mode supports the following frequencies: 1.25Hz, 5Hz, 20Hz, 40Hz MPU6500: Unlike the MPU6050 version, the hardware does not "lock in" a reference sample. The hardware monitors the accel data and detects any large change over a short period of time. The hardware motion threshold can be between 4mg and 1020mg in 4mg increments. MPU6500 Low-power accel mode supports the following frequencies: 1.25Hz, 2.5Hz, 5Hz, 10Hz, 20Hz, 40Hz, 80Hz, 160Hz, 320Hz, 640Hz NOTES: The driver will round down thresh to the nearest supported value if an unsupported threshold is selected. To select a fractional wake-up frequency, round down the value passed to lpa_freq. The MPU6500 does not support a delay parameter. If this function is used for the MPU6500, the value passed to time will be ignored. To disable this mode, set lpa_freq to zero. The driver will restore the previous configuration. thresh Motion threshold in mg. time Duration in milliseconds that the accel data must exceed thresh before motion is reported. lpa_freq Minimum sampling rate, or zero to disable. 0 if successful.
References gyro_reg_s::accel_cfg, motion_int_cache_s::accel_fsr, chip_cfg_s::accel_fsr, hw_s::addr, BIT_LPA_CYCLE, BIT_MOT_INT_EN, BIT_STBY_XYZG, BITS_HPF, BITS_WOM_EN, chip_cfg_s::cache, gyro_state_s::chip_cfg, chip_cfg_s::clk_src, delay_ms, motion_int_cache_s::dmp_on, chip_cfg_s::dmp_on, chip_cfg_s::fifo_enable, motion_int_cache_s::fifo_sensors, motion_int_cache_s::gyro_fsr, chip_cfg_s::gyro_fsr, gyro_state_s::hw, i2c_write, gyro_reg_s::int_enable, chip_cfg_s::int_motion_only, INV_CLK_PLL, INV_FILTER_256HZ_NOLPF2, INV_LPA_1_25HZ, INV_LPA_20HZ, INV_LPA_40HZ, INV_LPA_5HZ, gyro_reg_s::lpf, motion_int_cache_s::lpf, chip_cfg_s::lpf, gyro_reg_s::motion_thr, mpu_configure_fifo, mpu_get_accel_fsr, mpu_get_fifo_config, mpu_get_gyro_fsr, mpu_get_lpf, mpu_get_sample_rate, mpu_lp_accel_mode, mpu_set_accel_fsr, mpu_set_dmp_state, mpu_set_gyro_fsr, mpu_set_lpf, mpu_set_sample_rate, mpu_set_sensors, gyro_reg_s::pwr_mgmt_1, gyro_state_s::reg, motion_int_cache_s::sample_rate, chip_cfg_s::sample_rate, chip_cfg_s::sensors, motion_int_cache_s::sensors_on, set_int_enable, st, gyro_reg_s::user_ctrl.
u8 run_self_test(void)
References dmp_set_accel_bias, dmp_set_gyro_bias, mpu_get_accel_sens, mpu_get_gyro_sens, mpu_run_self_test.
Referenced by mpu_dmp_init.
unsigned short inv_orientation_matrix_to_scalar(const signed char *mtx)
References inv_row_2_scale.
Referenced by mpu_dmp_init.
unsigned short inv_row_2_scale(const signed char *row)
Referenced by inv_orientation_matrix_to_scalar.
void mget_ms(unsigned long *time)
u8 mpu_dmp_init(void)
References DEFAULT_MPU_HZ, dmp_enable_feature, DMP_FEATURE_6X_LP_QUAT, DMP_FEATURE_ANDROID_ORIENT, DMP_FEATURE_GYRO_CAL, DMP_FEATURE_SEND_CAL_GYRO, DMP_FEATURE_SEND_RAW_ACCEL, DMP_FEATURE_TAP, dmp_load_motion_driver_firmware, dmp_set_fifo_rate, dmp_set_orientation, gyro_orientation, inv_orientation_matrix_to_scalar, INV_XYZ_ACCEL, INV_XYZ_GYRO, mpu_configure_fifo, mpu_init, mpu_set_dmp_state, mpu_set_sample_rate, mpu_set_sensors, run_self_test.
u8 mpu_dmp_get_data(float *pitch, float *roll, float *yaw)
References dmp_read_fifo, INV_WXYZ_QUAT, q30.
int mpu_init_slave(void)
int mpu_register_tap_cb(void(*func)(unsigned char, unsigned char))
int dmp_load_motion_driver_firmware(void)
Load the DMP with this image.
0 if successful.
References DMP_CODE_SIZE, dmp_memory, DMP_SAMPLE_RATE, mpu_load_firmware, sStartAddress.
Referenced by mpu_dmp_init.
int dmp_set_orientation(unsigned short orient)
Push gyro and accel orientation to the DMP. The orientation is represented here as the output of inv_orientation_matrix_to_scalar.
orient Gyro and accel orientation in body frame. 0 if successful.
References DINA0C, DINA26, DINA2C, DINA36, DINA46, DINA4C, DINA56, DINA66, DINA6C, DINA76, DINAC9, DINACD, dmp, FCFG_1, FCFG_2, FCFG_3, FCFG_7, mpu_write_mem, dmp_s::orient.
Referenced by mpu_dmp_init.
int dmp_set_gyro_bias(long *bias)
Push gyro biases to the DMP. Because the gyro integration is handled in the DMP, any gyro biases calculated by the MPL should be pushed down to DMP memory to remove 3-axis quaternion drift. NOTE: If the DMP-based gyro calibration is enabled, the DMP will overwrite the biases written to this location once a new one is computed.
bias Gyro biases in q16. 0 if successful.
References D_EXT_GYRO_BIAS_X, D_EXT_GYRO_BIAS_Y, D_EXT_GYRO_BIAS_Z, dmp, GYRO_SF, mpu_write_mem, dmp_s::orient.
Referenced by run_self_test.
int dmp_set_accel_bias(long *bias)
Push accel biases to the DMP. These biases will be removed from the DMP 6-axis quaternion.
bias Accel biases in q16. 0 if successful.
References D_ACCEL_BIAS, dmp, mpu_get_accel_sens, mpu_write_mem, dmp_s::orient.
Referenced by run_self_test.
int dmp_set_fifo_rate(unsigned short rate)
Set DMP output rate. Only used when DMP is on.
rate Desired fifo rate (Hz). 0 if successful.
References CFG_6, D_0_22, DINAAA, DINAAB, DINADF, DINAF1, DINAF2, DINAFE, dmp, DMP_SAMPLE_RATE, dmp_s::fifo_rate, mpu_write_mem.
Referenced by mpu_dmp_init.
int dmp_get_fifo_rate(unsigned short *rate)
Get DMP output rate.
rate Current fifo rate (Hz). 0 if successful.
References dmp, dmp_s::fifo_rate.
int dmp_set_tap_thresh(unsigned char axis, unsigned short thresh)
Set tap threshold for a specific axis.
axis 1, 2, and 4 for XYZ accel, respectively. thresh Tap threshold, in mg/ms. 0 if successful.
References D_1_36, D_1_40, D_1_44, DMP_SAMPLE_RATE, DMP_TAP_THX, DMP_TAP_THY, DMP_TAP_THZ, mpu_get_accel_fsr, mpu_write_mem, TAP_X, TAP_XYZ, TAP_Y, TAP_Z.
Referenced by dmp_enable_feature.
int dmp_set_tap_axes(unsigned char axis)
Set which axes will register a tap.
axis 1, 2, and 4 for XYZ, respectively. 0 if successful.
References D_1_72, mpu_write_mem, TAP_X, TAP_Y, TAP_Z.
Referenced by dmp_enable_feature.
int dmp_set_tap_count(unsigned char min_taps)
Set minimum number of taps needed for an interrupt.
min_taps Minimum consecutive taps (1-4). 0 if successful.
References D_1_79, mpu_write_mem.
Referenced by dmp_enable_feature.
int dmp_set_tap_time(unsigned short time)
Set length between valid taps.
time Milliseconds between taps. 0 if successful.
References DMP_SAMPLE_RATE, DMP_TAPW_MIN, mpu_write_mem.
Referenced by dmp_enable_feature.
int dmp_set_tap_time_multi(unsigned short time)
Set max time between taps to register as a multi-tap.
time Max milliseconds between taps. 0 if successful.
References D_1_218, DMP_SAMPLE_RATE, mpu_write_mem.
Referenced by dmp_enable_feature.
int dmp_set_shake_reject_thresh(long sf, unsigned short thresh)
Set shake rejection threshold. If the DMP detects a gyro sample larger than thresh, taps are rejected.
sf Gyro scale factor. thresh Gyro threshold in dps. 0 if successful.
References D_1_92, mpu_write_mem.
Referenced by dmp_enable_feature.
int dmp_set_shake_reject_time(unsigned short time)
Set shake rejection time. Sets the length of time that the gyro must be outside of the threshold set by gyro_set_shake_reject_thresh before taps are rejected. A mandatory 60 ms is added to this parameter.
time Time in milliseconds. 0 if successful.
References D_1_90, DMP_SAMPLE_RATE, mpu_write_mem.
Referenced by dmp_enable_feature.
int dmp_set_shake_reject_timeout(unsigned short time)
Set shake rejection timeout. Sets the length of time after a shake rejection that the gyro must stay inside of the threshold before taps can be detected again. A mandatory 60 ms is added to this parameter.
time Time in milliseconds. 0 if successful.
References D_1_88, DMP_SAMPLE_RATE, mpu_write_mem.
Referenced by dmp_enable_feature.
int dmp_get_pedometer_step_count(unsigned long *count)
Get current step count.
count Number of steps detected. 0 if successful.
References D_PEDSTD_STEPCTR, mpu_read_mem.
int dmp_set_pedometer_step_count(unsigned long count)
Overwrite current step count. WARNING: This function writes to DMP memory and could potentially encounter a race condition if called while the pedometer is enabled.
count New step count. 0 if successful.
References D_PEDSTD_STEPCTR, mpu_write_mem.
int dmp_get_pedometer_walk_time(unsigned long *time)
Get duration of walking time.
time Walk time in milliseconds. 0 if successful.
References D_PEDSTD_TIMECTR, mpu_read_mem.
int dmp_set_pedometer_walk_time(unsigned long time)
Overwrite current walk time. WARNING: This function writes to DMP memory and could potentially encounter a race condition if called while the pedometer is enabled.
time New walk time in milliseconds.
References D_PEDSTD_TIMECTR, mpu_write_mem.
int dmp_enable_feature(unsigned short mask)
Enable DMP features. The following #define's are used in the input mask: DMP_FEATURE_TAP DMP_FEATURE_ANDROID_ORIENT DMP_FEATURE_LP_QUAT DMP_FEATURE_6X_LP_QUAT DMP_FEATURE_GYRO_CAL DMP_FEATURE_SEND_RAW_ACCEL DMP_FEATURE_SEND_RAW_GYRO NOTE: DMP_FEATURE_LP_QUAT and DMP_FEATURE_6X_LP_QUAT are mutually exclusive. NOTE: DMP_FEATURE_SEND_RAW_GYRO and DMP_FEATURE_SEND_CAL_GYRO are also mutually exclusive.
mask Mask of features to enable. 0 if successful.
References CFG_15, CFG_20, CFG_27, CFG_ANDROID_ORIENT_INT, CFG_GYRO_RAW_DATA, D_0_104, DINA20, DINA80, DINA90, DINAC0, DINAC2, dmp, dmp_enable_6x_lp_quat, dmp_enable_gyro_cal, dmp_enable_lp_quat, DMP_FEATURE_6X_LP_QUAT, DMP_FEATURE_ANDROID_ORIENT, DMP_FEATURE_GYRO_CAL, DMP_FEATURE_LP_QUAT, DMP_FEATURE_PEDOMETER, DMP_FEATURE_SEND_ANY_GYRO, DMP_FEATURE_SEND_CAL_GYRO, DMP_FEATURE_SEND_RAW_ACCEL, DMP_FEATURE_TAP, dmp_set_shake_reject_thresh, dmp_set_shake_reject_time, dmp_set_shake_reject_timeout, dmp_set_tap_axes, dmp_set_tap_count, dmp_set_tap_thresh, dmp_set_tap_time, dmp_set_tap_time_multi, dmp_s::feature_mask, GYRO_SF, mpu_reset_fifo, mpu_write_mem, dmp_s::packet_length, TAP_XYZ.
Referenced by mpu_dmp_init.
int dmp_get_enabled_features(unsigned short *mask)
Get list of currently enabled DMP features.
Mask of enabled features. 0 if successful.
References dmp, dmp_s::feature_mask.
int dmp_enable_gyro_cal(unsigned char enable)
Calibrate the gyro data in the DMP. After eight seconds of no motion, the DMP will compute gyro biases and subtract them from the quaternion output. If dmp_enable_feature is called with DMP_FEATURE_SEND_CAL_GYRO, the biases will also be subtracted from the gyro output.
enable 1 to enable gyro calibration. 0 if successful.
References CFG_MOTION_BIAS, mpu_write_mem.
Referenced by dmp_enable_feature.
int dmp_enable_lp_quat(unsigned char enable)
Generate 3-axis quaternions from the DMP. In this driver, the 3-axis and 6-axis DMP quaternion features are mutually exclusive.
enable 1 to enable 3-axis quaternion. 0 if successful.
References CFG_LP_QUAT, DINBC0, DINBC2, DINBC4, DINBC6, mpu_reset_fifo, mpu_write_mem.
Referenced by dmp_enable_feature.
int dmp_enable_6x_lp_quat(unsigned char enable)
Generate 6-axis quaternions from the DMP. In this driver, the 3-axis and 6-axis DMP quaternion features are mutually exclusive.
enable 1 to enable 6-axis quaternion. 0 if successful.
References CFG_8, DINA20, DINA28, DINA30, DINA38, mpu_reset_fifo, mpu_write_mem.
Referenced by dmp_enable_feature.
static int decode_gesture(unsigned char *gesture)
Decode the four-byte gesture data and execute any callbacks.
gesture Gesture data from DMP packet. 0 if successful.
References dmp_s::android_orient_cb, dmp, INT_SRC_ANDROID_ORIENT, INT_SRC_TAP, dmp_s::tap_cb.
Referenced by dmp_read_fifo.
int dmp_set_interrupt_mode(unsigned char mode)
Specify when a DMP interrupt should occur. A DMP interrupt can be configured to trigger on either of the two conditions below: a. One FIFO period has elapsed (set by mpu_set_sample_rate). b. A tap event has been detected.
mode DMP_INT_GESTURE or DMP_INT_CONTINUOUS. 0 if successful.
References CFG_FIFO_ON_EVENT, DMP_INT_CONTINUOUS, DMP_INT_GESTURE, mpu_write_mem.
int dmp_read_fifo(short *gyro, short *accel, long *quat, unsigned long *timestamp, short *sensors, unsigned char *more)
Get one packet from the FIFO. If sensors does not contain a particular sensor, disregard the data returned to that pointer. sensors can contain a combination of the following flags: INV_X_GYRO, INV_Y_GYRO, INV_Z_GYRO INV_XYZ_GYRO INV_XYZ_ACCEL INV_WXYZ_QUAT If the FIFO has no new data, sensors will be zero. If the FIFO is disabled, sensors will be zero and this function will return a non-zero error code.
gyro Gyro data in hardware units. accel Accel data in hardware units. quat 3-axis quaternion data in hardware units. timestamp Timestamp in milliseconds. sensors Mask of sensors read from FIFO. more Number of remaining packets. 0 if successful.
References decode_gesture, dmp, DMP_FEATURE_6X_LP_QUAT, DMP_FEATURE_ANDROID_ORIENT, DMP_FEATURE_LP_QUAT, DMP_FEATURE_SEND_ANY_GYRO, DMP_FEATURE_SEND_RAW_ACCEL, DMP_FEATURE_TAP, dmp_s::feature_mask, get_ms, INV_WXYZ_QUAT, INV_XYZ_ACCEL, INV_XYZ_GYRO, MAX_PACKET_LENGTH, mpu_read_fifo_stream, mpu_reset_fifo, dmp_s::packet_length, QUAT_MAG_SQ_MAX, QUAT_MAG_SQ_MIN.
Referenced by mpu_dmp_get_data.
int dmp_register_tap_cb(void(*func)(unsigned char, unsigned char))
Register a function to be executed on a tap event. The tap direction is represented by one of the following: TAP_X_UP TAP_X_DOWN TAP_Y_UP TAP_Y_DOWN TAP_Z_UP TAP_Z_DOWN
func Callback function. 0 if successful.
References dmp, dmp_s::tap_cb.
int dmp_register_android_orient_cb(void(*func)(unsigned char))
Register a function to be executed on a android orientation event.
func Callback function. 0 if successful.
References dmp_s::android_orient_cb, dmp.
MPU6050
MOTION_DRIVER_TARGET_MSP430
i2c_write
i2c_read
delay_ms
get_ms
log_i
log_e
fabs
min
BIT_I2C_MST_VDDIO
BIT_FIFO_EN
BIT_DMP_EN
BIT_FIFO_RST
BIT_DMP_RST
BIT_FIFO_OVERFLOW
BIT_DATA_RDY_EN
BIT_DMP_INT_EN
BIT_MOT_INT_EN
BITS_FSR
BITS_LPF
BITS_HPF
BITS_CLK
BIT_FIFO_SIZE_1024
BIT_FIFO_SIZE_2048
BIT_FIFO_SIZE_4096
BIT_RESET
BIT_SLEEP
BIT_S0_DELAY_EN
BIT_S2_DELAY_EN
BITS_SLAVE_LENGTH
BIT_SLAVE_BYTE_SW
BIT_SLAVE_GROUP
BIT_SLAVE_EN
BIT_I2C_READ
BITS_I2C_MASTER_DLY
BIT_AUX_IF_EN
BIT_ACTL
BIT_LATCH_EN
BIT_ANY_RD_CLR
BIT_BYPASS_EN
BITS_WOM_EN
BIT_LPA_CYCLE
BIT_STBY_XA
BIT_STBY_YA
BIT_STBY_ZA
BIT_STBY_XG
BIT_STBY_YG
BIT_STBY_ZG
BIT_STBY_XYZA
BIT_STBY_XYZG
MAX_PACKET_LENGTH
q30
DEFAULT_MPU_HZ
INV_X_GYRO
INV_Y_GYRO
INV_Z_GYRO
INV_XYZ_GYRO
INV_XYZ_ACCEL
INV_XYZ_COMPASS
MPU_INT_STATUS_DATA_READY
MPU_INT_STATUS_DMP
MPU_INT_STATUS_PLL_READY
MPU_INT_STATUS_I2C_MST
MPU_INT_STATUS_FIFO_OVERFLOW
MPU_INT_STATUS_ZMOT
MPU_INT_STATUS_MOT
MPU_INT_STATUS_FREE_FALL
MPU_INT_STATUS_DMP_0
MPU_INT_STATUS_DMP_1
MPU_INT_STATUS_DMP_2
MPU_INT_STATUS_DMP_3
MPU_INT_STATUS_DMP_4
MPU_INT_STATUS_DMP_5
MOTION_DRIVER_TARGET_MSP430
delay_ms
get_ms
log_i
log_e
CFG_LP_QUAT
END_ORIENT_TEMP
CFG_27
CFG_20
CFG_23
CFG_FIFO_ON_EVENT
END_PREDICTION_UPDATE
CGNOTICE_INTR
X_GRT_Y_TMP
CFG_DR_INT
CFG_AUTH
UPDATE_PROP_ROT
END_COMPARE_Y_X_TMP2
SKIP_X_GRT_Y_TMP
SKIP_END_COMPARE
FCFG_3
FCFG_2
FCFG_1
END_COMPARE_Y_X_TMP3
FCFG_7
FCFG_6
FLAT_STATE_END
SWING_END_4
SWING_END_2
SWING_END_3
SWING_END_1
CFG_8
CFG_15
CFG_16
CFG_EXT_GYRO_BIAS
END_COMPARE_Y_X_TMP
DO_NOT_UPDATE_PROP_ROT
CFG_7
FLAT_STATE_END_TEMP
END_COMPARE_Y_X
SKIP_SWING_END_1
SKIP_SWING_END_3
SKIP_SWING_END_2
TILTG75_START
CFG_6
TILTL75_END
END_ORIENT
CFG_FLICK_IN
TILTL75_START
CFG_MOTION_BIAS
X_GRT_Y
TEMPLABEL
CFG_ANDROID_ORIENT_INT
CFG_GYRO_RAW_DATA
X_GRT_Y_TMP2
D_0_22
D_0_24
D_0_36
D_0_52
D_0_96
D_0_104
D_0_108
D_0_163
D_0_188
D_0_192
D_0_224
D_0_228
D_0_232
D_0_236
D_1_2
D_1_4
D_1_8
D_1_10
D_1_24
D_1_28
D_1_36
D_1_40
D_1_44
D_1_72
D_1_74
D_1_79
D_1_88
D_1_90
D_1_92
D_1_96
D_1_98
D_1_106
D_1_108
D_1_112
D_1_128
D_1_152
D_1_160
D_1_176
D_1_178
D_1_218
D_1_232
D_1_236
D_1_240
D_1_244
D_1_250
D_1_252
D_2_12
D_2_96
D_2_108
D_2_208
D_2_224
D_2_236
D_2_244
D_2_248
D_2_252
CPASS_BIAS_X
CPASS_BIAS_Y
CPASS_BIAS_Z
CPASS_MTX_00
CPASS_MTX_01
CPASS_MTX_02
CPASS_MTX_10
CPASS_MTX_11
CPASS_MTX_12
CPASS_MTX_20
CPASS_MTX_21
CPASS_MTX_22
D_EXT_GYRO_BIAS_X
D_EXT_GYRO_BIAS_Y
D_EXT_GYRO_BIAS_Z
D_ACT0
D_ACSX
D_ACSY
D_ACSZ
FLICK_MSG
FLICK_COUNTER
FLICK_LOWER
FLICK_UPPER
D_AUTH_OUT
D_AUTH_IN
D_AUTH_A
D_AUTH_B
D_PEDSTD_BP_B
D_PEDSTD_HP_A
D_PEDSTD_HP_B
D_PEDSTD_BP_A4
D_PEDSTD_BP_A3
D_PEDSTD_BP_A2
D_PEDSTD_BP_A1
D_PEDSTD_INT_THRSH
D_PEDSTD_CLIP
D_PEDSTD_SB
D_PEDSTD_SB_TIME
D_PEDSTD_PEAKTHRSH
D_PEDSTD_TIML
D_PEDSTD_TIMH
D_PEDSTD_PEAK
D_PEDSTD_STEPCTR
D_PEDSTD_TIMECTR
D_PEDSTD_DECI
D_HOST_NO_MOT
D_ACCEL_BIAS
D_ORIENT_GAP
D_TILT0_H
D_TILT0_L
D_TILT1_H
D_TILT1_L
D_TILT2_H
D_TILT2_L
D_TILT3_H
D_TILT3_L
DMP_CODE_SIZE
INT_SRC_TAP
INT_SRC_ANDROID_ORIENT
DMP_FEATURE_SEND_ANY_GYRO
MAX_PACKET_LENGTH
DMP_SAMPLE_RATE
GYRO_SF
FIFO_CORRUPTION_CHECK
QUAT_ERROR_THRESH
QUAT_MAG_SQ_NORMALIZED
QUAT_MAG_SQ_MIN
QUAT_MAG_SQ_MAX
TAP_X
TAP_Y
TAP_Z
TAP_XYZ
TAP_X_UP
TAP_X_DOWN
TAP_Y_UP
TAP_Y_DOWN
TAP_Z_UP
TAP_Z_DOWN
ANDROID_ORIENT_PORTRAIT
ANDROID_ORIENT_LANDSCAPE
ANDROID_ORIENT_REVERSE_PORTRAIT
ANDROID_ORIENT_REVERSE_LANDSCAPE
DMP_INT_GESTURE
DMP_INT_CONTINUOUS
DMP_FEATURE_TAP
DMP_FEATURE_ANDROID_ORIENT
DMP_FEATURE_LP_QUAT
DMP_FEATURE_PEDOMETER
DMP_FEATURE_6X_LP_QUAT
DMP_FEATURE_GYRO_CAL
DMP_FEATURE_SEND_RAW_ACCEL
DMP_FEATURE_SEND_RAW_GYRO
DMP_FEATURE_SEND_CAL_GYRO
INV_WXYZ_QUAT