inv_mpu_dmp_motion_driver.c
MOTION_DRIVER_TARGET_MSP430
delay_ms
get_ms
log_i
log_e
CFG_LP_QUAT
END_ORIENT_TEMP
CFG_27
CFG_20
CFG_23
CFG_FIFO_ON_EVENT
END_PREDICTION_UPDATE
CGNOTICE_INTR
X_GRT_Y_TMP
CFG_DR_INT
CFG_AUTH
UPDATE_PROP_ROT
END_COMPARE_Y_X_TMP2
SKIP_X_GRT_Y_TMP
SKIP_END_COMPARE
FCFG_3
FCFG_2
FCFG_1
END_COMPARE_Y_X_TMP3
FCFG_7
FCFG_6
FLAT_STATE_END
SWING_END_4
SWING_END_2
SWING_END_3
SWING_END_1
CFG_8
CFG_15
CFG_16
CFG_EXT_GYRO_BIAS
END_COMPARE_Y_X_TMP
DO_NOT_UPDATE_PROP_ROT
CFG_7
FLAT_STATE_END_TEMP
END_COMPARE_Y_X
SKIP_SWING_END_1
SKIP_SWING_END_3
SKIP_SWING_END_2
TILTG75_START
CFG_6
TILTL75_END
END_ORIENT
CFG_FLICK_IN
TILTL75_START
CFG_MOTION_BIAS
X_GRT_Y
TEMPLABEL
CFG_ANDROID_ORIENT_INT
CFG_GYRO_RAW_DATA
X_GRT_Y_TMP2
D_0_22
D_0_24
D_0_36
D_0_52
D_0_96
D_0_104
D_0_108
D_0_163
D_0_188
D_0_192
D_0_224
D_0_228
D_0_232
D_0_236
D_1_2
D_1_4
D_1_8
D_1_10
D_1_24
D_1_28
D_1_36
D_1_40
D_1_44
D_1_72
D_1_74
D_1_79
D_1_88
D_1_90
D_1_92
D_1_96
D_1_98
D_1_106
D_1_108
D_1_112
D_1_128
D_1_152
D_1_160
D_1_176
D_1_178
D_1_218
D_1_232
D_1_236
D_1_240
D_1_244
D_1_250
D_1_252
D_2_12
D_2_96
D_2_108
D_2_208
D_2_224
D_2_236
D_2_244
D_2_248
D_2_252
CPASS_BIAS_X
CPASS_BIAS_Y
CPASS_BIAS_Z
CPASS_MTX_00
CPASS_MTX_01
CPASS_MTX_02
CPASS_MTX_10
CPASS_MTX_11
CPASS_MTX_12
CPASS_MTX_20
CPASS_MTX_21
CPASS_MTX_22
D_EXT_GYRO_BIAS_X
D_EXT_GYRO_BIAS_Y
D_EXT_GYRO_BIAS_Z
D_ACT0
D_ACSX
D_ACSY
D_ACSZ
FLICK_MSG
FLICK_COUNTER
FLICK_LOWER
FLICK_UPPER
D_AUTH_OUT
D_AUTH_IN
D_AUTH_A
D_AUTH_B
D_PEDSTD_BP_B
D_PEDSTD_HP_A
D_PEDSTD_HP_B
D_PEDSTD_BP_A4
D_PEDSTD_BP_A3
D_PEDSTD_BP_A2
D_PEDSTD_BP_A1
D_PEDSTD_INT_THRSH
D_PEDSTD_CLIP
D_PEDSTD_SB
D_PEDSTD_SB_TIME
D_PEDSTD_PEAKTHRSH
D_PEDSTD_TIML
D_PEDSTD_TIMH
D_PEDSTD_PEAK
D_PEDSTD_STEPCTR
D_PEDSTD_TIMECTR
D_PEDSTD_DECI
D_HOST_NO_MOT
D_ACCEL_BIAS
D_ORIENT_GAP
D_TILT0_H
D_TILT0_L
D_TILT1_H
D_TILT1_L
D_TILT2_H
D_TILT2_L
D_TILT3_H
D_TILT3_L
DMP_CODE_SIZE
INT_SRC_TAP
INT_SRC_ANDROID_ORIENT
DMP_FEATURE_SEND_ANY_GYRO
MAX_PACKET_LENGTH
DMP_SAMPLE_RATE
GYRO_SF
FIFO_CORRUPTION_CHECK
QUAT_ERROR_THRESH
QUAT_MAG_SQ_NORMALIZED
QUAT_MAG_SQ_MIN
QUAT_MAG_SQ_MAX
const unsigned char dmp_memory[DMP_CODE_SIZE][DMP_CODE_SIZE]
Referenced by dmp_load_motion_driver_firmware.
const unsigned short sStartAddress
Referenced by dmp_load_motion_driver_firmware.
struct dmp_s dmp
Referenced by decode_gesture, dmp_enable_feature, dmp_get_enabled_features, dmp_get_fifo_rate, dmp_read_fifo, dmp_register_android_orient_cb, dmp_register_tap_cb, dmp_set_accel_bias, dmp_set_fifo_rate, dmp_set_gyro_bias, dmp_set_orientation.
int dmp_load_motion_driver_firmware(void)
Load the DMP with this image.
0 if successful.
References DMP_CODE_SIZE, dmp_memory, DMP_SAMPLE_RATE, mpu_load_firmware, sStartAddress.
Referenced by mpu_dmp_init.
int dmp_set_orientation(unsigned short orient)
Push gyro and accel orientation to the DMP. The orientation is represented here as the output of inv_orientation_matrix_to_scalar.
orient Gyro and accel orientation in body frame. 0 if successful.
References DINA0C, DINA26, DINA2C, DINA36, DINA46, DINA4C, DINA56, DINA66, DINA6C, DINA76, DINAC9, DINACD, dmp, FCFG_1, FCFG_2, FCFG_3, FCFG_7, mpu_write_mem, dmp_s::orient.
Referenced by mpu_dmp_init.
int dmp_set_gyro_bias(long *bias)
Push gyro biases to the DMP. Because the gyro integration is handled in the DMP, any gyro biases calculated by the MPL should be pushed down to DMP memory to remove 3-axis quaternion drift. NOTE: If the DMP-based gyro calibration is enabled, the DMP will overwrite the biases written to this location once a new one is computed.
bias Gyro biases in q16. 0 if successful.
References D_EXT_GYRO_BIAS_X, D_EXT_GYRO_BIAS_Y, D_EXT_GYRO_BIAS_Z, dmp, GYRO_SF, mpu_write_mem, dmp_s::orient.
Referenced by run_self_test.
int dmp_set_accel_bias(long *bias)
Push accel biases to the DMP. These biases will be removed from the DMP 6-axis quaternion.
bias Accel biases in q16. 0 if successful.
References D_ACCEL_BIAS, dmp, mpu_get_accel_sens, mpu_write_mem, dmp_s::orient.
Referenced by run_self_test.
int dmp_set_fifo_rate(unsigned short rate)
Set DMP output rate. Only used when DMP is on.
rate Desired fifo rate (Hz). 0 if successful.
References CFG_6, D_0_22, DINAAA, DINAAB, DINADF, DINAF1, DINAF2, DINAFE, dmp, DMP_SAMPLE_RATE, dmp_s::fifo_rate, mpu_write_mem.
Referenced by mpu_dmp_init.
int dmp_get_fifo_rate(unsigned short *rate)
Get DMP output rate.
rate Current fifo rate (Hz). 0 if successful.
References dmp, dmp_s::fifo_rate.
int dmp_set_tap_thresh(unsigned char axis, unsigned short thresh)
Set tap threshold for a specific axis.
axis 1, 2, and 4 for XYZ accel, respectively. thresh Tap threshold, in mg/ms. 0 if successful.
References D_1_36, D_1_40, D_1_44, DMP_SAMPLE_RATE, DMP_TAP_THX, DMP_TAP_THY, DMP_TAP_THZ, mpu_get_accel_fsr, mpu_write_mem, TAP_X, TAP_XYZ, TAP_Y, TAP_Z.
Referenced by dmp_enable_feature.
int dmp_set_tap_axes(unsigned char axis)
Set which axes will register a tap.
axis 1, 2, and 4 for XYZ, respectively. 0 if successful.
References D_1_72, mpu_write_mem, TAP_X, TAP_Y, TAP_Z.
Referenced by dmp_enable_feature.
int dmp_set_tap_count(unsigned char min_taps)
Set minimum number of taps needed for an interrupt.
min_taps Minimum consecutive taps (1-4). 0 if successful.
References D_1_79, mpu_write_mem.
Referenced by dmp_enable_feature.
int dmp_set_tap_time(unsigned short time)
Set length between valid taps.
time Milliseconds between taps. 0 if successful.
References DMP_SAMPLE_RATE, DMP_TAPW_MIN, mpu_write_mem.
Referenced by dmp_enable_feature.
int dmp_set_tap_time_multi(unsigned short time)
Set max time between taps to register as a multi-tap.
time Max milliseconds between taps. 0 if successful.
References D_1_218, DMP_SAMPLE_RATE, mpu_write_mem.
Referenced by dmp_enable_feature.
int dmp_set_shake_reject_thresh(long sf, unsigned short thresh)
Set shake rejection threshold. If the DMP detects a gyro sample larger than thresh, taps are rejected.
sf Gyro scale factor. thresh Gyro threshold in dps. 0 if successful.
References D_1_92, mpu_write_mem.
Referenced by dmp_enable_feature.
int dmp_set_shake_reject_time(unsigned short time)
Set shake rejection time. Sets the length of time that the gyro must be outside of the threshold set by gyro_set_shake_reject_thresh before taps are rejected. A mandatory 60 ms is added to this parameter.
time Time in milliseconds. 0 if successful.
References D_1_90, DMP_SAMPLE_RATE, mpu_write_mem.
Referenced by dmp_enable_feature.
int dmp_set_shake_reject_timeout(unsigned short time)
Set shake rejection timeout. Sets the length of time after a shake rejection that the gyro must stay inside of the threshold before taps can be detected again. A mandatory 60 ms is added to this parameter.
time Time in milliseconds. 0 if successful.
References D_1_88, DMP_SAMPLE_RATE, mpu_write_mem.
Referenced by dmp_enable_feature.
int dmp_get_pedometer_step_count(unsigned long *count)
Get current step count.
count Number of steps detected. 0 if successful.
References D_PEDSTD_STEPCTR, mpu_read_mem.
int dmp_set_pedometer_step_count(unsigned long count)
Overwrite current step count. WARNING: This function writes to DMP memory and could potentially encounter a race condition if called while the pedometer is enabled.
count New step count. 0 if successful.
References D_PEDSTD_STEPCTR, mpu_write_mem.
int dmp_get_pedometer_walk_time(unsigned long *time)
Get duration of walking time.
time Walk time in milliseconds. 0 if successful.
References D_PEDSTD_TIMECTR, mpu_read_mem.
int dmp_set_pedometer_walk_time(unsigned long time)
Overwrite current walk time. WARNING: This function writes to DMP memory and could potentially encounter a race condition if called while the pedometer is enabled.
time New walk time in milliseconds.
References D_PEDSTD_TIMECTR, mpu_write_mem.
int dmp_enable_feature(unsigned short mask)
Enable DMP features. The following #define's are used in the input mask: DMP_FEATURE_TAP DMP_FEATURE_ANDROID_ORIENT DMP_FEATURE_LP_QUAT DMP_FEATURE_6X_LP_QUAT DMP_FEATURE_GYRO_CAL DMP_FEATURE_SEND_RAW_ACCEL DMP_FEATURE_SEND_RAW_GYRO NOTE: DMP_FEATURE_LP_QUAT and DMP_FEATURE_6X_LP_QUAT are mutually exclusive. NOTE: DMP_FEATURE_SEND_RAW_GYRO and DMP_FEATURE_SEND_CAL_GYRO are also mutually exclusive.
mask Mask of features to enable. 0 if successful.
References CFG_15, CFG_20, CFG_27, CFG_ANDROID_ORIENT_INT, CFG_GYRO_RAW_DATA, D_0_104, DINA20, DINA80, DINA90, DINAC0, DINAC2, dmp, dmp_enable_6x_lp_quat, dmp_enable_gyro_cal, dmp_enable_lp_quat, DMP_FEATURE_6X_LP_QUAT, DMP_FEATURE_ANDROID_ORIENT, DMP_FEATURE_GYRO_CAL, DMP_FEATURE_LP_QUAT, DMP_FEATURE_PEDOMETER, DMP_FEATURE_SEND_ANY_GYRO, DMP_FEATURE_SEND_CAL_GYRO, DMP_FEATURE_SEND_RAW_ACCEL, DMP_FEATURE_TAP, dmp_set_shake_reject_thresh, dmp_set_shake_reject_time, dmp_set_shake_reject_timeout, dmp_set_tap_axes, dmp_set_tap_count, dmp_set_tap_thresh, dmp_set_tap_time, dmp_set_tap_time_multi, dmp_s::feature_mask, GYRO_SF, mpu_reset_fifo, mpu_write_mem, dmp_s::packet_length, TAP_XYZ.
Referenced by mpu_dmp_init.
int dmp_get_enabled_features(unsigned short *mask)
Get list of currently enabled DMP features.
Mask of enabled features. 0 if successful.
References dmp, dmp_s::feature_mask.
int dmp_enable_gyro_cal(unsigned char enable)
Calibrate the gyro data in the DMP. After eight seconds of no motion, the DMP will compute gyro biases and subtract them from the quaternion output. If dmp_enable_feature is called with DMP_FEATURE_SEND_CAL_GYRO, the biases will also be subtracted from the gyro output.
enable 1 to enable gyro calibration. 0 if successful.
References CFG_MOTION_BIAS, mpu_write_mem.
Referenced by dmp_enable_feature.
int dmp_enable_lp_quat(unsigned char enable)
Generate 3-axis quaternions from the DMP. In this driver, the 3-axis and 6-axis DMP quaternion features are mutually exclusive.
enable 1 to enable 3-axis quaternion. 0 if successful.
References CFG_LP_QUAT, DINBC0, DINBC2, DINBC4, DINBC6, mpu_reset_fifo, mpu_write_mem.
Referenced by dmp_enable_feature.
int dmp_enable_6x_lp_quat(unsigned char enable)
Generate 6-axis quaternions from the DMP. In this driver, the 3-axis and 6-axis DMP quaternion features are mutually exclusive.
enable 1 to enable 6-axis quaternion. 0 if successful.
References CFG_8, DINA20, DINA28, DINA30, DINA38, mpu_reset_fifo, mpu_write_mem.
Referenced by dmp_enable_feature.
static int decode_gesture(unsigned char *gesture)
Decode the four-byte gesture data and execute any callbacks.
gesture Gesture data from DMP packet. 0 if successful.
References dmp_s::android_orient_cb, dmp, INT_SRC_ANDROID_ORIENT, INT_SRC_TAP, dmp_s::tap_cb.
Referenced by dmp_read_fifo.
int dmp_set_interrupt_mode(unsigned char mode)
Specify when a DMP interrupt should occur. A DMP interrupt can be configured to trigger on either of the two conditions below: a. One FIFO period has elapsed (set by mpu_set_sample_rate). b. A tap event has been detected.
mode DMP_INT_GESTURE or DMP_INT_CONTINUOUS. 0 if successful.
References CFG_FIFO_ON_EVENT, DMP_INT_CONTINUOUS, DMP_INT_GESTURE, mpu_write_mem.
int dmp_read_fifo(short *gyro, short *accel, long *quat, unsigned long *timestamp, short *sensors, unsigned char *more)
Get one packet from the FIFO. If sensors does not contain a particular sensor, disregard the data returned to that pointer. sensors can contain a combination of the following flags: INV_X_GYRO, INV_Y_GYRO, INV_Z_GYRO INV_XYZ_GYRO INV_XYZ_ACCEL INV_WXYZ_QUAT If the FIFO has no new data, sensors will be zero. If the FIFO is disabled, sensors will be zero and this function will return a non-zero error code.
gyro Gyro data in hardware units. accel Accel data in hardware units. quat 3-axis quaternion data in hardware units. timestamp Timestamp in milliseconds. sensors Mask of sensors read from FIFO. more Number of remaining packets. 0 if successful.
References decode_gesture, dmp, DMP_FEATURE_6X_LP_QUAT, DMP_FEATURE_ANDROID_ORIENT, DMP_FEATURE_LP_QUAT, DMP_FEATURE_SEND_ANY_GYRO, DMP_FEATURE_SEND_RAW_ACCEL, DMP_FEATURE_TAP, dmp_s::feature_mask, get_ms, INV_WXYZ_QUAT, INV_XYZ_ACCEL, INV_XYZ_GYRO, MAX_PACKET_LENGTH, mpu_read_fifo_stream, mpu_reset_fifo, dmp_s::packet_length, QUAT_MAG_SQ_MAX, QUAT_MAG_SQ_MIN.
Referenced by mpu_dmp_get_data.
int dmp_register_tap_cb(void(*func)(unsigned char, unsigned char))
Register a function to be executed on a tap event. The tap direction is represented by one of the following: TAP_X_UP TAP_X_DOWN TAP_Y_UP TAP_Y_DOWN TAP_Z_UP TAP_Z_DOWN
func Callback function. 0 if successful.
References dmp, dmp_s::tap_cb.
int dmp_register_android_orient_cb(void(*func)(unsigned char))
Register a function to be executed on a android orientation event.
func Callback function. 0 if successful.
References dmp_s::android_orient_cb, dmp.