inv_mpu_dmp_motion_driver.h
TAP_X
TAP_Y
TAP_Z
TAP_XYZ
TAP_X_UP
TAP_X_DOWN
TAP_Y_UP
TAP_Y_DOWN
TAP_Z_UP
TAP_Z_DOWN
ANDROID_ORIENT_PORTRAIT
ANDROID_ORIENT_LANDSCAPE
ANDROID_ORIENT_REVERSE_PORTRAIT
ANDROID_ORIENT_REVERSE_LANDSCAPE
DMP_INT_GESTURE
DMP_INT_CONTINUOUS
DMP_FEATURE_TAP
DMP_FEATURE_ANDROID_ORIENT
DMP_FEATURE_LP_QUAT
DMP_FEATURE_PEDOMETER
DMP_FEATURE_6X_LP_QUAT
DMP_FEATURE_GYRO_CAL
DMP_FEATURE_SEND_RAW_ACCEL
DMP_FEATURE_SEND_RAW_GYRO
DMP_FEATURE_SEND_CAL_GYRO
INV_WXYZ_QUAT
int dmp_load_motion_driver_firmware(void)
Load the DMP with this image.
0 if successful.
References DMP_CODE_SIZE, dmp_memory, DMP_SAMPLE_RATE, mpu_load_firmware, sStartAddress.
Referenced by mpu_dmp_init.
int dmp_set_fifo_rate(unsigned short rate)
Set DMP output rate. Only used when DMP is on.
rate Desired fifo rate (Hz). 0 if successful.
References CFG_6, D_0_22, DINAAA, DINAAB, DINADF, DINAF1, DINAF2, DINAFE, dmp, DMP_SAMPLE_RATE, dmp_s::fifo_rate, mpu_write_mem.
Referenced by mpu_dmp_init.
int dmp_get_fifo_rate(unsigned short *rate)
Get DMP output rate.
rate Current fifo rate (Hz). 0 if successful.
References dmp, dmp_s::fifo_rate.
int dmp_enable_feature(unsigned short mask)
Enable DMP features. The following #define's are used in the input mask: DMP_FEATURE_TAP DMP_FEATURE_ANDROID_ORIENT DMP_FEATURE_LP_QUAT DMP_FEATURE_6X_LP_QUAT DMP_FEATURE_GYRO_CAL DMP_FEATURE_SEND_RAW_ACCEL DMP_FEATURE_SEND_RAW_GYRO NOTE: DMP_FEATURE_LP_QUAT and DMP_FEATURE_6X_LP_QUAT are mutually exclusive. NOTE: DMP_FEATURE_SEND_RAW_GYRO and DMP_FEATURE_SEND_CAL_GYRO are also mutually exclusive.
mask Mask of features to enable. 0 if successful.
References CFG_15, CFG_20, CFG_27, CFG_ANDROID_ORIENT_INT, CFG_GYRO_RAW_DATA, D_0_104, DINA20, DINA80, DINA90, DINAC0, DINAC2, dmp, dmp_enable_6x_lp_quat, dmp_enable_gyro_cal, dmp_enable_lp_quat, DMP_FEATURE_6X_LP_QUAT, DMP_FEATURE_ANDROID_ORIENT, DMP_FEATURE_GYRO_CAL, DMP_FEATURE_LP_QUAT, DMP_FEATURE_PEDOMETER, DMP_FEATURE_SEND_ANY_GYRO, DMP_FEATURE_SEND_CAL_GYRO, DMP_FEATURE_SEND_RAW_ACCEL, DMP_FEATURE_TAP, dmp_set_shake_reject_thresh, dmp_set_shake_reject_time, dmp_set_shake_reject_timeout, dmp_set_tap_axes, dmp_set_tap_count, dmp_set_tap_thresh, dmp_set_tap_time, dmp_set_tap_time_multi, dmp_s::feature_mask, GYRO_SF, mpu_reset_fifo, mpu_write_mem, dmp_s::packet_length, TAP_XYZ.
Referenced by mpu_dmp_init.
int dmp_get_enabled_features(unsigned short *mask)
Get list of currently enabled DMP features.
Mask of enabled features. 0 if successful.
References dmp, dmp_s::feature_mask.
int dmp_set_interrupt_mode(unsigned char mode)
Specify when a DMP interrupt should occur. A DMP interrupt can be configured to trigger on either of the two conditions below: a. One FIFO period has elapsed (set by mpu_set_sample_rate). b. A tap event has been detected.
mode DMP_INT_GESTURE or DMP_INT_CONTINUOUS. 0 if successful.
References CFG_FIFO_ON_EVENT, DMP_INT_CONTINUOUS, DMP_INT_GESTURE, mpu_write_mem.
int dmp_set_orientation(unsigned short orient)
Push gyro and accel orientation to the DMP. The orientation is represented here as the output of inv_orientation_matrix_to_scalar.
orient Gyro and accel orientation in body frame. 0 if successful.
References DINA0C, DINA26, DINA2C, DINA36, DINA46, DINA4C, DINA56, DINA66, DINA6C, DINA76, DINAC9, DINACD, dmp, FCFG_1, FCFG_2, FCFG_3, FCFG_7, mpu_write_mem, dmp_s::orient.
Referenced by mpu_dmp_init.
int dmp_set_gyro_bias(long *bias)
Push gyro biases to the DMP. Because the gyro integration is handled in the DMP, any gyro biases calculated by the MPL should be pushed down to DMP memory to remove 3-axis quaternion drift. NOTE: If the DMP-based gyro calibration is enabled, the DMP will overwrite the biases written to this location once a new one is computed.
bias Gyro biases in q16. 0 if successful.
References D_EXT_GYRO_BIAS_X, D_EXT_GYRO_BIAS_Y, D_EXT_GYRO_BIAS_Z, dmp, GYRO_SF, mpu_write_mem, dmp_s::orient.
Referenced by run_self_test.
int dmp_set_accel_bias(long *bias)
Push accel biases to the DMP. These biases will be removed from the DMP 6-axis quaternion.
bias Accel biases in q16. 0 if successful.
References D_ACCEL_BIAS, dmp, mpu_get_accel_sens, mpu_write_mem, dmp_s::orient.
Referenced by run_self_test.
int dmp_register_tap_cb(void(*func)(unsigned char, unsigned char))
Register a function to be executed on a tap event. The tap direction is represented by one of the following: TAP_X_UP TAP_X_DOWN TAP_Y_UP TAP_Y_DOWN TAP_Z_UP TAP_Z_DOWN
func Callback function. 0 if successful.
References dmp, dmp_s::tap_cb.
int dmp_set_tap_thresh(unsigned char axis, unsigned short thresh)
Set tap threshold for a specific axis.
axis 1, 2, and 4 for XYZ accel, respectively. thresh Tap threshold, in mg/ms. 0 if successful.
References D_1_36, D_1_40, D_1_44, DMP_SAMPLE_RATE, DMP_TAP_THX, DMP_TAP_THY, DMP_TAP_THZ, mpu_get_accel_fsr, mpu_write_mem, TAP_X, TAP_XYZ, TAP_Y, TAP_Z.
Referenced by dmp_enable_feature.
int dmp_set_tap_axes(unsigned char axis)
Set which axes will register a tap.
axis 1, 2, and 4 for XYZ, respectively. 0 if successful.
References D_1_72, mpu_write_mem, TAP_X, TAP_Y, TAP_Z.
Referenced by dmp_enable_feature.
int dmp_set_tap_count(unsigned char min_taps)
Set minimum number of taps needed for an interrupt.
min_taps Minimum consecutive taps (1-4). 0 if successful.
References D_1_79, mpu_write_mem.
Referenced by dmp_enable_feature.
int dmp_set_tap_time(unsigned short time)
Set length between valid taps.
time Milliseconds between taps. 0 if successful.
References DMP_SAMPLE_RATE, DMP_TAPW_MIN, mpu_write_mem.
Referenced by dmp_enable_feature.
int dmp_set_tap_time_multi(unsigned short time)
Set max time between taps to register as a multi-tap.
time Max milliseconds between taps. 0 if successful.
References D_1_218, DMP_SAMPLE_RATE, mpu_write_mem.
Referenced by dmp_enable_feature.
int dmp_set_shake_reject_thresh(long sf, unsigned short thresh)
Set shake rejection threshold. If the DMP detects a gyro sample larger than thresh, taps are rejected.
sf Gyro scale factor. thresh Gyro threshold in dps. 0 if successful.
References D_1_92, mpu_write_mem.
Referenced by dmp_enable_feature.
int dmp_set_shake_reject_time(unsigned short time)
Set shake rejection time. Sets the length of time that the gyro must be outside of the threshold set by gyro_set_shake_reject_thresh before taps are rejected. A mandatory 60 ms is added to this parameter.
time Time in milliseconds. 0 if successful.
References D_1_90, DMP_SAMPLE_RATE, mpu_write_mem.
Referenced by dmp_enable_feature.
int dmp_set_shake_reject_timeout(unsigned short time)
Set shake rejection timeout. Sets the length of time after a shake rejection that the gyro must stay inside of the threshold before taps can be detected again. A mandatory 60 ms is added to this parameter.
time Time in milliseconds. 0 if successful.
References D_1_88, DMP_SAMPLE_RATE, mpu_write_mem.
Referenced by dmp_enable_feature.
int dmp_register_android_orient_cb(void(*func)(unsigned char))
Register a function to be executed on a android orientation event.
func Callback function. 0 if successful.
References dmp_s::android_orient_cb, dmp.
int dmp_enable_lp_quat(unsigned char enable)
Generate 3-axis quaternions from the DMP. In this driver, the 3-axis and 6-axis DMP quaternion features are mutually exclusive.
enable 1 to enable 3-axis quaternion. 0 if successful.
References CFG_LP_QUAT, DINBC0, DINBC2, DINBC4, DINBC6, mpu_reset_fifo, mpu_write_mem.
Referenced by dmp_enable_feature.
int dmp_enable_6x_lp_quat(unsigned char enable)
Generate 6-axis quaternions from the DMP. In this driver, the 3-axis and 6-axis DMP quaternion features are mutually exclusive.
enable 1 to enable 6-axis quaternion. 0 if successful.
References CFG_8, DINA20, DINA28, DINA30, DINA38, mpu_reset_fifo, mpu_write_mem.
Referenced by dmp_enable_feature.
int dmp_get_pedometer_step_count(unsigned long *count)
Get current step count.
count Number of steps detected. 0 if successful.
References D_PEDSTD_STEPCTR, mpu_read_mem.
int dmp_set_pedometer_step_count(unsigned long count)
Overwrite current step count. WARNING: This function writes to DMP memory and could potentially encounter a race condition if called while the pedometer is enabled.
count New step count. 0 if successful.
References D_PEDSTD_STEPCTR, mpu_write_mem.
int dmp_get_pedometer_walk_time(unsigned long *time)
Get duration of walking time.
time Walk time in milliseconds. 0 if successful.
References D_PEDSTD_TIMECTR, mpu_read_mem.
int dmp_set_pedometer_walk_time(unsigned long time)
Overwrite current walk time. WARNING: This function writes to DMP memory and could potentially encounter a race condition if called while the pedometer is enabled.
time New walk time in milliseconds.
References D_PEDSTD_TIMECTR, mpu_write_mem.
int dmp_enable_gyro_cal(unsigned char enable)
Calibrate the gyro data in the DMP. After eight seconds of no motion, the DMP will compute gyro biases and subtract them from the quaternion output. If dmp_enable_feature is called with DMP_FEATURE_SEND_CAL_GYRO, the biases will also be subtracted from the gyro output.
enable 1 to enable gyro calibration. 0 if successful.
References CFG_MOTION_BIAS, mpu_write_mem.
Referenced by dmp_enable_feature.
int dmp_read_fifo(short *gyro, short *accel, long *quat, unsigned long *timestamp, short *sensors, unsigned char *more)
Get one packet from the FIFO. If sensors does not contain a particular sensor, disregard the data returned to that pointer. sensors can contain a combination of the following flags: INV_X_GYRO, INV_Y_GYRO, INV_Z_GYRO INV_XYZ_GYRO INV_XYZ_ACCEL INV_WXYZ_QUAT If the FIFO has no new data, sensors will be zero. If the FIFO is disabled, sensors will be zero and this function will return a non-zero error code.
gyro Gyro data in hardware units. accel Accel data in hardware units. quat 3-axis quaternion data in hardware units. timestamp Timestamp in milliseconds. sensors Mask of sensors read from FIFO. more Number of remaining packets. 0 if successful.
References decode_gesture, dmp, DMP_FEATURE_6X_LP_QUAT, DMP_FEATURE_ANDROID_ORIENT, DMP_FEATURE_LP_QUAT, DMP_FEATURE_SEND_ANY_GYRO, DMP_FEATURE_SEND_RAW_ACCEL, DMP_FEATURE_TAP, dmp_s::feature_mask, get_ms, INV_WXYZ_QUAT, INV_XYZ_ACCEL, INV_XYZ_GYRO, MAX_PACKET_LENGTH, mpu_read_fifo_stream, mpu_reset_fifo, dmp_s::packet_length, QUAT_MAG_SQ_MAX, QUAT_MAG_SQ_MIN.
Referenced by mpu_dmp_get_data.