mpu6050.h
MPU_SELF_TESTX_REG
MPU_SELF_TESTY_REG
MPU_SELF_TESTZ_REG
MPU_SELF_TESTA_REG
MPU_SAMPLE_RATE_REG
MPU_CFG_REG
MPU_GYRO_CFG_REG
MPU_ACCEL_CFG_REG
MPU_MOTION_DET_REG
MPU_FIFO_EN_REG
MPU_I2CMST_CTRL_REG
MPU_I2CSLV0_ADDR_REG
MPU_I2CSLV0_REG
MPU_I2CSLV0_CTRL_REG
MPU_I2CSLV1_ADDR_REG
MPU_I2CSLV1_REG
MPU_I2CSLV1_CTRL_REG
MPU_I2CSLV2_ADDR_REG
MPU_I2CSLV2_REG
MPU_I2CSLV2_CTRL_REG
MPU_I2CSLV3_ADDR_REG
MPU_I2CSLV3_REG
MPU_I2CSLV3_CTRL_REG
MPU_I2CSLV4_ADDR_REG
MPU_I2CSLV4_REG
MPU_I2CSLV4_DO_REG
MPU_I2CSLV4_CTRL_REG
MPU_I2CSLV4_DI_REG
MPU_I2CMST_STA_REG
MPU_INTBP_CFG_REG
MPU_INT_EN_REG
MPU_INT_STA_REG
MPU_ACCEL_XOUTH_REG
MPU_ACCEL_XOUTL_REG
MPU_ACCEL_YOUTH_REG
MPU_ACCEL_YOUTL_REG
MPU_ACCEL_ZOUTH_REG
MPU_ACCEL_ZOUTL_REG
MPU_TEMP_OUTH_REG
MPU_TEMP_OUTL_REG
MPU_GYRO_XOUTH_REG
MPU_GYRO_XOUTL_REG
MPU_GYRO_YOUTH_REG
MPU_GYRO_YOUTL_REG
MPU_GYRO_ZOUTH_REG
MPU_GYRO_ZOUTL_REG
MPU_I2CSLV0_DO_REG
MPU_I2CSLV1_DO_REG
MPU_I2CSLV2_DO_REG
MPU_I2CSLV3_DO_REG
MPU_I2CMST_DELAY_REG
MPU_SIGPATH_RST_REG
MPU_MDETECT_CTRL_REG
MPU_USER_CTRL_REG
MPU_PWR_MGMT1_REG
MPU_PWR_MGMT2_REG
MPU_FIFO_CNTH_REG
MPU_FIFO_CNTL_REG
MPU_FIFO_RW_REG
MPU_DEVICE_ID_REG
MPU_ADDR
u8 MPU_Init(void)
初始化MPU6050
0,成功
References delay_ms, MPU_ADDR, MPU_DEVICE_ID_REG, MPU_FIFO_EN_REG, MPU_INT_EN_REG, MPU_INTBP_CFG_REG, MPU_PWR_MGMT1_REG, MPU_PWR_MGMT2_REG, MPU_Read_Byte, MPU_Set_Accel_Fsr, MPU_Set_Gyro_Fsr, MPU_Set_Rate, MPU_USER_CTRL_REG, MPU_Write_Byte.
u8 MPU_Write_Len(u8 addr, u8 reg, u8 len, u8 *buf)
IIC连续写
addr 器件地址 reg 寄存器地址 len 写入长度 *buf 数据区 0,设置成功
References mpu6050IIC.
u8 MPU_Read_Len(u8 addr, u8 reg, u8 len, u8 *buf)
IIC连续读
addr 器件地址 reg 寄存器地址 len 读取长度 *buf 读取数据区 0,设置成功
References mpu6050IIC.
Referenced by MPU_Get_Accelerometer, MPU_Get_Gyroscope, MPU_Get_Temperature.
u8 MPU_Write_Byte(u8 reg, u8 data)
IIC写一个字节
reg 寄存器地址 data 数据 0,设置成功
References mpu6050IIC, MPU_ADDR.
Referenced by MPU_Init, MPU_Set_Accel_Fsr, MPU_Set_Gyro_Fsr, MPU_Set_LPF, MPU_Set_Rate.
u8 MPU_Read_Byte(u8 reg)
IIC读一个字节
reg 寄存器地址 0,设置成功
References mpu6050IIC, MPU_ADDR.
Referenced by MPU_Init.
u8 MPU_Set_Gyro_Fsr(u8 fsr)
设置MPU6050陀螺仪传感器满量程范围
fsr 0,±250dps 1,±500dps 2,±1000dps 3,±2000dps 0,设置成功
References MPU_GYRO_CFG_REG, MPU_Write_Byte.
Referenced by MPU_Init.
u8 MPU_Set_Accel_Fsr(u8 fsr)
设置MPU6050加速度传感器满量程范围
fsr 0,±2g 1,±4g 2,±8g 3,±16g 0,设置成功
References MPU_ACCEL_CFG_REG, MPU_Write_Byte.
Referenced by MPU_Init.
u8 MPU_Set_LPF(u16 lpf)
设置MPU6050的数字低通滤波器
lpf 数字低通滤波频率(Hz) 0,设置成功
References MPU_CFG_REG, MPU_Write_Byte.
Referenced by MPU_Set_Rate.
u8 MPU_Set_Rate(u16 rate)
设置MPU6050的采样率(假定Fs=1KHz)
rate 4~1000(Hz) 0,设置成功
References MPU_SAMPLE_RATE_REG, MPU_Set_LPF, MPU_Write_Byte.
Referenced by MPU_Init.
u8 MPU_Set_Fifo(u8 sens)
short MPU_Get_Temperature(void)
得到温度值
温度值(扩大了100倍)
References MPU_ADDR, MPU_Read_Len, MPU_TEMP_OUTH_REG.
u8 MPU_Get_Gyroscope(short *gx, short *gy, short *gz)
得到陀螺仪值(原始值)
gx 陀螺仪x轴的原始读数(带符号) gy 陀螺仪y轴的原始读数(带符号) gx 陀螺仪z轴的原始读数(带符号) 0,设置成功
References MPU_ADDR, MPU_GYRO_XOUTH_REG, MPU_Read_Len.
u8 MPU_Get_Accelerometer(short *ax, short *ay, short *az)
得到加速度值(原始值)
ax 陀螺仪a轴的原始读数(带符号) ay 陀螺仪a轴的原始读数(带符号) ax 陀螺仪a轴的原始读数(带符号) 0,设置成功
References MPU_ACCEL_XOUTH_REG, MPU_ADDR, MPU_Read_Len.